### ISSUE TITLE
Working with remote comfy instance.

### ISSUE THREAD

**Issue by gitgud5000** [NimaNzrii/comfyui-photoshop#1]
By creating a tunnel I'm able to connect to the node...

The problem arises because it expects the file system to be local, so the `Photoshop_import` method fails when trying to save the temp file. Do you have any idea what the approach should be to modify it so that it's agnostic to local/remote comfy  installation?

**Comment by FugueSegue** [comment]
This is good node. But the problem I have is that my Wacom Cintiq only has 6GB VRAM. It's not powerful enough to do live painting with SD. I built a separate computer to do all my SD rendering and I connect to it via LAN.

This node does not communicate via LAN. I see that this is the first issue posted here. I believe that it is the most important issue.

**Comment by sraney** [comment]
I can agree completely with this,  having the ability to connect ComfyUI to the the 'remote' system running Photoshop would be make this almost perfect.
