### ISSUE TITLE
Help! Connection problem

### ISSUE THREAD

**Issue by DDZ0920** [NimaNzrii/comfyui-photoshop#101]
First, I want to say this is a great plugin, very useful! However, I've encountered a problem:

The local ComfyUI address 127.0.0.1:8188 works very well, but when I use a listening address like 1.2.3.4:50070, ComfyUI is not recognized. In the PS plugin, it shows "Host application disallows WebView." I can't solve this issue. Is there any good solution? Thank you.
<img width="609" alt="image" src="https://github.com/NimaNzrii/comfyui-photoshop/assets/131282694/a494d0c9-bdad-49b8-8f23-0114ca7e38c9">
<img width="289" alt="image" src="https://github.com/NimaNzrii/comfyui-photoshop/assets/131282694/9b29a6e8-787e-4b2b-8e7b-b1a908e00edf">

**Comment by NimaNzrii** [comment]
Unfortunately this will only work on local ips

**Comment by razv23** [comment]
> Unfortunately this will only work on local ips

Hi! Are you planning to make it work on remote computers as well at some point? 
Thanks for your work, btw

**Comment by DDZ0920** [comment]
> Unfortunately this will only work on local ips

thx for reply! its a very good plugin, looking forward to more upgrade! 👍👍👍
