### ISSUE TITLE
connection problem?

### ISSUE THREAD

**Issue by KillyTheNetTerminal** [NimaNzrii/comfyui-photoshop#102]
![image](https://github.com/NimaNzrii/comfyui-photoshop/assets/120438550/5dd0e6f2-cf83-4fb8-be71-7a8a8ca12617)

**Comment by NimaNzrii** [comment]
Could you please send me the lig file of your ComfyUi terminal?

**Comment by KillyTheNetTerminal** [comment]
hi! where can I find it?

**Comment by KillyTheNetTerminal** [comment]
(comf) C:\Users\WarMa\OneDrive\Escritorio\SD\comfyuai\ComfyUI>python main.py --directml --lowvram --force-upcast-attenti
on
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-06-14 07:54:52.384907
** Platform: Windows
** Python version: 3.10.0 (tags/v3.10.0:b494f59, Oct  4 2021, 19:00:18) [MSC v.1929 64 bit (AMD64)]
** Python executable: C:\Users\WarMa\OneDrive\Escritorio\SD\comfyuai\ComfyUI\comf\Scripts\python.exe
** Log path: C:\Users\WarMa\OneDrive\Escritorio\SD\comfyuai\ComfyUI\comfyui.log

Prestartup times for custom nodes:
   2.6 seconds: C:\Users\WarMa\OneDrive\Escritorio\SD\comfyuai\ComfyUI\custom_nodes\ComfyUI-Manager

Using directml with device:
Total VRAM 1024 MB, total RAM 32688 MB
pytorch version: 2.2.1+cpu
Set vram state to: LOW_VRAM
Device: privateuseone
VAE dtype: torch.float32
Using sub quadratic optimization for cross attention, if you have memory or speed issues try using: --use-split-cross-attention
### Loading: ComfyUI-Manager (V2.38)
### ComfyUI Revision: 2247 [605e64f6] | Released on '2024-06-12'
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
WARNING: You are using pip version 21.2.3; however, version 24.0 is available.
You should consider upgrading via the 'C:\Users\WarMa\OneDrive\Escritorio\SD\comfyuai\ComfyUI\comf\Scripts\python.exe -m pip install --upgrade pip' command.
_PS_ All packages are installed.
_PS_ backend_path C:\Users\WarMa\OneDrive\Escritorio\SD\comfyuai\ComfyUI\custom_nodes\comfyui-photoshop\Backend.py
_PS_ Plugin is not updated, installing. . .

_PS_ Installed plugin in C:\Users\WarMa\AppData\Roaming\Adobe\UXP\Plugins\External and updated PS.json

_PS_ RESTART YOUR PHOTOSHOP AND LAUNCH THE PLUGIN

_PS_ Starting server...
WARNING: Ignoring invalid distribution -illow (c:\users\warma\appdata\local\programs\python\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -illow (c:\users\warma\appdata\local\programs\python\python310\lib\site-packages)
WARNING: Skipping photoshop as it is not installed.
WARNING: Ignoring invalid distribution -illow (c:\users\warma\appdata\local\programs\python\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -illow (c:\users\warma\appdata\local\programs\python\python310\lib\site-packages)
Found existing installation: photoshop-connection 0.2.0
Uninstalling photoshop-connection-0.2.0:
  Would remove:
    c:\users\warma\appdata\local\programs\python\python310\lib\site-packages\photoshop\*
    c:\users\warma\appdata\local\programs\python\python310\lib\site-packages\photoshop_connection-0.2.0.dist-info\*
Proceed (Y/n)? Y
  Successfully uninstalled photoshop-connection-0.2.0
WARNING: Ignoring invalid distribution -illow (c:\users\warma\appdata\local\programs\python\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -illow (c:\users\warma\appdata\local\programs\python\python310\lib\site-packages)
Collecting photoshop-connection
  Using cached photoshop_connection-0.2.0-py3-none-any.whl (21 kB)
Requirement already satisfied: jinja2<3.1.0 in c:\users\warma\appdata\local\programs\python\python310\lib\site-packages (from photoshop-connection) (3.0.3)
Requirement already satisfied: cryptography<40.0.0,>=39.0.1 in c:\users\warma\appdata\local\programs\python\python310\lib\site-packages (from photoshop-connection) (39.0.2)
Requirement already satisfied: cffi>=1.12 in c:\users\warma\appdata\local\programs\python\python310\lib\site-packages (from cryptography<40.0.0,>=39.0.1->photoshop-connection) (1.16.0)
Requirement already satisfied: pycparser in c:\users\warma\appdata\local\programs\python\python310\lib\site-packages (from cffi>=1.12->cryptography<40.0.0,>=39.0.1->photoshop-connection) (2.22)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\warma\appdata\local\programs\python\python310\lib\site-packages (from jinja2<3.1.0->photoshop-connection) (2.1.3)
WARNING: Ignoring invalid distribution -illow (c:\users\warma\appdata\local\programs\python\python310\lib\site-packages)
Installing collected packages: photoshop-connection
WARNING: Ignoring invalid distribution -illow (c:\users\warma\appdata\local\programs\python\python310\lib\site-packages)
Successfully installed photoshop-connection-0.2.0
WARNING: Ignoring invalid distribution -illow (c:\users\warma\appdata\local\programs\python\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -illow (c:\users\warma\appdata\local\programs\python\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -illow (c:\users\warma\appdata\local\programs\python\python310\lib\site-packages)
WARNING: You are using pip version 21.2.3; however, version 24.0 is available.
You should consider upgrading via the 'C:\Users\WarMa\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000002712243FD90>
Traceback (most recent call last):
  File "C:\Users\WarMa\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\WarMa\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\WarMa\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 745, in call_soon
    self._check_closed()
  File "C:\Users\WarMa\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
[comfyui_controlnet_aux] | INFO -> Using ckpts path: C:\Users\WarMa\OneDrive\Escritorio\SD\comfyuai\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts
[comfyui_controlnet_aux] | INFO -> Using symlinks: False
[comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider']
C:\Users\WarMa\OneDrive\Escritorio\SD\comfyuai\ComfyUI\custom_nodes\comfyui_controlnet_aux\node_wrappers\dwpose.py:26: UserWarning: DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly
  warnings.warn("DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly")
Efficiency Nodes: Attempting to add Control Net options to the 'HiRes-Fix Script' Node (comfyui_controlnet_aux add-on)...Success!

Import times for custom nodes:
   0.0 seconds: C:\Users\WarMa\OneDrive\Escritorio\SD\comfyuai\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds: C:\Users\WarMa\OneDrive\Escritorio\SD\comfyuai\ComfyUI\custom_nodes\prompt_injection
   0.0 seconds: C:\Users\WarMa\OneDrive\Escritorio\SD\comfyuai\ComfyUI\custom_nodes\ComfyUI-TCD
   0.0 seconds: C:\Users\WarMa\OneDrive\Escritorio\SD\comfyuai\ComfyUI\custom_nodes\ComfyUI-Photopea
   0.0 seconds: C:\Users\WarMa\OneDrive\Escritorio\SD\comfyuai\ComfyUI\custom_nodes\efficiency-nodes-comfyui
   0.0 seconds: C:\Users\WarMa\OneDrive\Escritorio\SD\comfyuai\ComfyUI\custom_nodes\ComfyUI_essentials
   0.3 seconds: C:\Users\WarMa\OneDrive\Escritorio\SD\comfyuai\ComfyUI\custom_nodes\ComfyUI-Manager
   1.1 seconds: C:\Users\WarMa\OneDrive\Escritorio\SD\comfyuai\ComfyUI\custom_nodes\comfyui_controlnet_aux
  12.8 seconds: C:\Users\WarMa\OneDrive\Escritorio\SD\comfyuai\ComfyUI\custom_nodes\comfyui-photoshop

Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: C:\Users\WarMa\OneDrive\Escritorio\SD\comfyuai\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
_PS_ Node found in workflow: ('127.0.0.1', 61384)
got prompt
Error in is_changed_file for C:\Users\WarMa\OneDrive\Escritorio\SD\comfyuai\ComfyUI\input\PS_canvas.png: [Errno 2] No such file or directory: 'C:\\Users\\WarMa\\OneDrive\\Escritorio\\SD\\comfyuai\\ComfyUI\\input\\PS_canvas.png'
Error in is_changed_file for C:\Users\WarMa\OneDrive\Escritorio\SD\comfyuai\ComfyUI\input\PS_mask.png: [Errno 2] No such file or directory: 'C:\\Users\\WarMa\\OneDrive\\Escritorio\\SD\\comfyuai\\ComfyUI\\input\\PS_mask.png'
_PS_ photoshop Not Connected
nodepath C:\Users\WarMa\OneDrive\Escritorio\SD\comfyuai\ComfyUI\custom_nodes\comfyui-photoshop
Prompt executed in 0.05 seconds
_PS_ photoshop Not Connected

**Comment by NimaNzrii** [comment]
Could you please send your log file?
Cause it should wrok even on the first node

**Comment by KillyTheNetTerminal** [comment]
it works in the first node too. Where I could find that log file?

**Comment by NimaNzrii** [comment]
Cool , so you solved the problem by installing that package manualy. Right?

Before it , even the Photoshop plugin didn't worked?

I eant to fix it for everyone, so your info will help me a lot

**Comment by Chengifan** [comment]
Hello, I have updated the latest version of the plug-in, but it doesn't work anymore. When I click on the "Run" button, the screen in the plug-in doesn't respond. The version before June 8 can run correctly, but after the update, this version can't be used. How can I solve this problem? I saw this question and it seems to be the same problem as mine. When I connect to phohoshop, only a small black square is displayed.

**Comment by KillyTheNetTerminal** [comment]
Error in is_changed_file for C:\Users\WarMa\OneDrive\Escritorio\SD\comfyuai\ComfyUI\input\PS_canvas.png: [Errno 2] No such file or directory: 'C:\\Users\\WarMa\\OneDrive\\Escritorio\\SD\\comfyuai\\ComfyUI\\input\\PS_canvas.png'
Error in is_changed_file for C:\Users\WarMa\OneDrive\Escritorio\SD\comfyuai\ComfyUI\input\PS_mask.png: [Errno 2] No such file or directory: 'C:\\Users\\WarMa\\OneDrive\\Escritorio\\SD\\comfyuai\\ComfyUI\\input\\PS_mask.png' (always make a reference to those files)

**Comment by KillyTheNetTerminal** [comment]
![image](https://github.com/NimaNzrii/comfyui-photoshop/assets/120438550/d1647619-9769-4961-956c-07e61c5db6d9)

**Comment by KillyTheNetTerminal** [comment]
![image](https://github.com/NimaNzrii/comfyui-photoshop/assets/120438550/1c2814e1-dcbb-4154-b2fb-0579d76c0b9d)

**Comment by KillyTheNetTerminal** [comment]
nodepath C:\Users\WarMa\OneDrive\Escritorio\SD\comfyuai\ComfyUI\custom_nodes\comfyui-photoshop
Prompt executed in 0.26 seconds
The images do not seem to leave Photoshop and save them in the input folder of comfyui

**Comment by KillyTheNetTerminal** [comment]
![image](https://github.com/NimaNzrii/comfyui-photoshop/assets/120438550/9f6117b6-3637-45c9-9363-509652f4aa12)
Okaayyy... now working 
![image](https://github.com/NimaNzrii/comfyui-photoshop/assets/120438550/a346692c-d8d0-4e1e-b1ac-ab7877775ab1)
I install this
