### ISSUE TITLE
inpaint

### ISSUE THREAD

**Issue by 907590629** [NimaNzrii/comfyui-photoshop#104]
inpaint：我在ps中用套索工具 无法创建蒙版；
outpaint：我用剪辑工具扩大选区后无法用移动工具选取扩大后的选取。
这两个问题是否与我的ps不是正版有关系呢？？我的版本是 25.5.0  不是正版

**Comment by LiJT** [comment]
Same!!!!

**Comment by 907590629** [comment]
> 的！！！！

兄弟 加个v 沟通   haike931

**Comment by QL-boy** [comment]
> inpaint：我在ps中用套索工具 无法创建蒙版； outpaint：我用剪辑工具扩大选区后无法用移动工具选取扩大后的选取。 这两个问题是否与我的ps不是正版有关系呢？？我的版本是 25.5.0 不是正版

经测试 photoshop 的语言需要切换为英文，然后重启一下就可以正常使用了

**Comment by NimaNzrii** [comment]
Hey guys , your problem should be fixed right now , pleas update the node and re install the latest version of the plugin to fix the masking option ❤️

**Comment by NimaNzrii** [comment]
# Fixed in V1.5.0 ✨
this problem should be fixed in ver 1.5.0
please update plugin and the node and let me know if it helped
