### ISSUE TITLE
the problem，please watch the video

### ISSUE THREAD

**Issue by 907590629** [NimaNzrii/comfyui-photoshop#107]
https://github.com/NimaNzrii/comfyui-photoshop/assets/43062860/40959554-5eae-4258-9949-10fbeffe50ab

[Diagnostics-1718412112.log](https://github.com/user-attachments/files/15845048/Diagnostics-1718412112.log)

**Comment by NimaNzrii** [comment]
this problem should be fixed in latest ver
update and let me know
