### ISSUE TITLE
[WinError 10054] An existing connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by junaid3d** [NimaNzrii/comfyui-photoshop#108]
The latest photoshop plugin installed in the directory:
C:\Users\user pc\AppData\Roaming\Adobe\UXP\Plugins\External\3e6d64e0_1.4.0

Photoshop version: 24.6

ComfyUI and comfyui-photoshop updated today. 
ComfyUI address: http://127.0.0.1:8188/

Error in comfui:
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "D:\AI\Python\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\AI\Python\lib\asyncio\proactor_events.py", line 165, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

Photoshop port 49494 is active:
C:\Users\user pc>netstat -an | find "49494"
  TCP    0.0.0.0:49494          0.0.0.0:0              LISTENING

![Screenshot_1664](https://github.com/NimaNzrii/comfyui-photoshop/assets/131003205/8ac46ea8-3532-4aa1-a803-d52dbb016f3c)
![Screenshot_1665](https://github.com/NimaNzrii/comfyui-photoshop/assets/131003205/3ba44bc2-d395-46bb-bf99-0b2eac1439f2)

**Comment by NimaNzrii** [comment]
Are you using old method or new one , the remote connection method has nothing to do with the plugin

So for the plugin you should use the first nude in the list

**Comment by NimaNzrii** [comment]
If it's nit working please sebd me your log files

**Comment by junaid3d** [comment]
`[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-06-16 12:54:33.288350
** Platform: Windows
** Python version: 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
** Python executable: R:\AI\ComfyUI\Scripts\python.exe
** Log path: R:\AI\ComfyUI\ComfyUI\comfyui.log
[ComfyUI-Manager] Logging failed: [WinError 32] The process cannot access the file because it is being used by another process: 'comfyui.log' -> 'comfyui.prev.log'
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-06-16 12:54:33.293336
** Platform: Windows
** Python version: 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
** Python executable: R:\AI\ComfyUI\Scripts\python.exe
** Log path: R:\AI\ComfyUI\ComfyUI\comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: R:\AI\ComfyUI\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds: R:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager-main
   1.7 seconds: R:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 12287 MB, total RAM 32618 MB
pytorch version: 2.3.1+cu121
xformers version: 0.0.26.post1
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3060 : cudaMallocAsync
VAE dtype: torch.bfloat16
Using xformers cross attention
Adding extra search path checkpoints R:\AI\StableDiffusion\models
Adding extra search path clip R:\AI\StableDiffusion\CLIP
Adding extra search path clip_vision R:\AI\StableDiffusion\CLIP
Adding extra search path configs R:\AI\StableDiffusion\models
Adding extra search path controlnet R:\AI\StableDiffusion\controlnets/Models
Adding extra search path embeddings R:\AI\StableDiffusion\embeddings
Adding extra search path loras R:\AI\StableDiffusion\Lora
Adding extra search path vae R:\AI\StableDiffusion\vae
Web extensions folder found at R:\AI\ComfyUI\ComfyUI\web\extensions\ComfyLiterals
Adding R:\AI\ComfyUI\ComfyUI\custom_nodes to sys.path
Efficiency Nodes: Attempting to add Control Net options to the 'HiRes-Fix Script' Node (comfyui_controlnet_aux add-on)...Success!
Loaded Efficiency nodes from R:\AI\ComfyUI\ComfyUI\custom_nodes\efficiency-nodes-comfyui
Loaded ControlNetPreprocessors nodes from R:\AI\ComfyUI\ComfyUI\custom_nodes\comfyui_controlnet_aux
Loaded AdvancedControlNet nodes from R:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
Could not find AnimateDiff nodes
Loaded IPAdapter nodes from R:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
Could not find VideoHelperSuite nodes
### Loading: ComfyUI-Impact-Pack (V5.11.4)
### Loading: ComfyUI-Impact-Pack (Subpack: V0.6)
### Loading: ComfyUI-Impact-Pack (V5.11.4)
Loaded ImpactPack nodes from R:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack[Impact Pack] Wildcards loading done.

[Impact Pack] Wildcards loading done.
### Loading: ComfyUI-Impact-Pack (V5.11.4)
[Impact Pack] Wildcards loading done.### Loading: ComfyUI-Inspire-Pack (V0.75.2)

Total VRAM 12287 MB, total RAM 32618 MB
pytorch version: 2.3.1+cu121
xformers version: 0.0.26.post1
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3060 : cudaMallocAsync
VAE dtype: torch.bfloat16
### Loading: ComfyUI-Manager (V2.36.1)
### ComfyUI Revision: 2250 [5eb98f00] | Released on '2024-06-13'
### Loading: ComfyUI-Manager (V2.36.1)
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] Some features are restricted due to your ComfyUI being outdated.
### ComfyUI Revision: 2250 [5eb98f00] | Released on '2024-06-13'
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json

[notice] A new release of pip is available: 23.0.1 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip
_PS_ All packages are installed.
_PS_ backend_path R:\AI\ComfyUI\ComfyUI\custom_nodes\comfyui-photoshop\Backend.py
Failed to auto update `Quality of Life Suit`
QualityOfLifeSuit_Omar92_DIR: R:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-QualityOfLifeSuit_Omar92
  File "R:\AI\ComfyUI\ComfyUI\custom_nodes\comfyui-photoshop\Backend.py", line 50
    adobe_plugins_storage = os.path.expanduser('C:\Users\user pc\AppData\Roaming\Adobe\UXP\Plugins\External')
                                                                                                            ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
[ReActor] - STATUS - Running v0.5.0-b3 in ComfyUI
Torch version: 2.3.1+cu121
[comfy_mtb] | INFO -> loaded 78 nodes successfuly

[rgthree] Loaded 39 exciting nodes.
[rgthree] Will use rgthree's optimized recursive execution.

WAS Node Suite: OpenCV Python FFMPEG support is enabled
WAS Node Suite Warning: `ffmpeg_bin_path` is not set in `R:\AI\ComfyUI\ComfyUI\custom_nodes\was-node-suite-comfyui\was_suite_config.json` config file. Will attempt to use system ffmpeg binaries if available.
WAS Node Suite: Finished. Loaded 213 nodes successfully.

        "Success is not in what you have, but who you are." - Bo Bennett


Import times for custom nodes:
   0.0 seconds: R:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
   0.0 seconds: R:\AI\ComfyUI\ComfyUI\custom_nodes\dequality.py
   0.0 seconds: R:\AI\ComfyUI\ComfyUI\custom_nodes\efficiency-nodes-comfyui
   0.0 seconds: R:\AI\ComfyUI\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds: R:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Logic
   0.0 seconds: R:\AI\ComfyUI\ComfyUI\custom_nodes\sdxl_prompt_styler
   0.0 seconds: R:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-CascadeResolutions
   0.0 seconds: R:\AI\ComfyUI\ComfyUI\custom_nodes\cg-use-everywhere
   0.0 seconds: R:\AI\ComfyUI\ComfyUI\custom_nodes\sd-perturbed-attention
   0.0 seconds: R:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Eagle-PNGInfo
   0.0 seconds: R:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
   0.0 seconds: R:\AI\ComfyUI\ComfyUI\custom_nodes\comfyui_controlnet_aux
   0.0 seconds: R:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI_restart_sampling
   0.0 seconds: R:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyLiterals
   0.0 seconds: R:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI_essentials
   0.0 seconds: R:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-QualityOfLifeSuit_Omar92
   0.0 seconds: R:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
   0.0 seconds: R:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
   0.0 seconds: R:\AI\ComfyUI\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds: R:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-KJNodes
   0.0 seconds: R:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved
   0.0 seconds: R:\AI\ComfyUI\ComfyUI\custom_nodes\comfy-image-saver
   0.0 seconds: R:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI_TensorRT
   0.1 seconds: R:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Inspire-Pack
   0.1 seconds: R:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyI2I
   0.1 seconds: R:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI_smZNodes
   0.4 seconds: R:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager
   0.4 seconds: R:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager-main
   0.8 seconds: R:\AI\ComfyUI\ComfyUI\custom_nodes\comfyui-art-venture
   0.9 seconds: R:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI_InstantID
   1.1 seconds: R:\AI\ComfyUI\ComfyUI\custom_nodes\comfyui-reactor-node
   1.3 seconds: R:\AI\ComfyUI\ComfyUI\custom_nodes\comfyui-photoshop
   2.1 seconds: R:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-SUPIR
   2.1 seconds: R:\AI\ComfyUI\ComfyUI\custom_nodes\was-node-suite-comfyui
   4.1 seconds: R:\AI\ComfyUI\ComfyUI\custom_nodes\comfy_mtb

Starting server

To see the GUI go to: http://127.0.0.1:8188`

**Comment by junaid3d** [comment]
I installed the plugin into the C:\Users\user pc\AppData\Roaming\Adobe\UXP\Plugins\External folder and this is the error:
![Screenshot_1667](https://github.com/NimaNzrii/comfyui-photoshop/assets/131003205/c8d3b255-76c1-44c4-9307-3da126ed61e5)

**Comment by NimaNzrii** [comment]
> I installed the plugin into the C:\Users\user pc\AppData\Roaming\Adobe\UXP\Plugins\External folder and this is the error: ![Screenshot_1667](https://private-user-images.githubusercontent.com/131003205/340074351-c8d3b255-76c1-44c4-9307-3da126ed61e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg1MjUyNzQsIm5iZiI6MTcxODUyNDk3NCwicGF0aCI6Ii8xMzEwMDMyMDUvMzQwMDc0MzUxLWM4ZDNiMjU1LTc2YzEtNDRjNC05MzA3LTNkYTEyNmVkNjFlNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxNlQwODAyNTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ODk4YzM4YTNiZGY5Yzc1ZmU2ZjBjNTVjYzVlMTZiNDgzYWYxYzE3Mzg2NDRlMzRhZWY4N2UyYzY2MDE5YTEzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.saF49mGAqzvNEQ674IBizgNcqrpxV7EKXm81fnEGfWM)

that's because you didn't press start button on the main panel

**Comment by junaid3d** [comment]
`
![Screenshot_1668](https://github.com/NimaNzrii/comfyui-photoshop/assets/131003205/738321c0-2da2-4b11-a94f-f469ebe4ca76)
 I did and another error

**Comment by NimaNzrii** [comment]
> adobe_plugins_storage = os.path.expanduser('C:\Users\user pc\AppData\Roaming\Adobe\UXP\Plugins\External')
> ^
> SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape

you got this error on your log file
this error just got fixed rn 

please update the node and see if it fixed the bug

**Comment by junaid3d** [comment]
It's connected but still has that unicode error:
_PS_ All packages are installed.
_PS_ backend_path R:\AI\ComfyUI\ComfyUI\custom_nodes\comfyui-photoshop\Backend.py
Failed to auto update `Quality of Life Suit`
QualityOfLifeSuit_Omar92_DIR: R:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-QualityOfLifeSuit_Omar92
  File "R:\AI\ComfyUI\ComfyUI\custom_nodes\comfyui-photoshop\Backend.py", line 50
    adobe_plugins_storage = os.path.expanduser('C:\Users\user pc\AppData\Roaming\Adobe\UXP\Plugins\External')
                                                                                                            ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape

![Screenshot_1674](https://github.com/NimaNzrii/comfyui-photoshop/assets/131003205/911c0d6e-a3c5-407c-9d69-108b04e9fa50)

Also, I clicked Send to Layers but it didnt do anything or render.

**Comment by junaid3d** [comment]
The error is gone.

**Comment by junaid3d** [comment]
How to render something now?

**Comment by junaid3d** [comment]
I've also clicked the Render button but it does not render. Connections are fixed now :)

**Comment by NimaNzrii** [comment]
In your setting , in the image proccessing tab , you have 2 undefined for some reason! Can you please put some value like 1024 abd 512 on second one please

**Comment by junaid3d** [comment]
![Screenshot_1676](https://github.com/NimaNzrii/comfyui-photoshop/assets/131003205/ef0a2cd9-4787-4210-bdd2-9f4bfa973220)
I did but the render button does not do anything :(

**Comment by NimaNzrii** [comment]
Please send me your log again 
Full log please

**Comment by junaid3d** [comment]
`[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-06-16 13:57:01.526858
** Platform: Windows
** Python version: 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
** Python executable: R:\AI\ComfyUI\Scripts\python.exe
** Log path: R:\AI\ComfyUI\ComfyUI\comfyui.log
[ComfyUI-Manager] Logging failed: [WinError 32] The process cannot access the file because it is being used by another process: 'comfyui.log' -> 'comfyui.prev.log'
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-06-16 13:57:01.531844
** Platform: Windows
** Python version: 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
** Python executable: R:\AI\ComfyUI\Scripts\python.exe
** Log path: R:\AI\ComfyUI\ComfyUI\comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: R:\AI\ComfyUI\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds: R:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager-main
   1.7 seconds: R:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 12287 MB, total RAM 32618 MB
pytorch version: 2.3.1+cu121
xformers version: 0.0.26.post1
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3060 : cudaMallocAsync
VAE dtype: torch.bfloat16
Using xformers cross attention
Adding extra search path checkpoints R:\AI\StableDiffusion\models
Adding extra search path clip R:\AI\StableDiffusion\CLIP
Adding extra search path clip_vision R:\AI\StableDiffusion\CLIP
Adding extra search path configs R:\AI\StableDiffusion\models
Adding extra search path controlnet R:\AI\StableDiffusion\controlnets/Models
Adding extra search path embeddings R:\AI\StableDiffusion\embeddings
Adding extra search path loras R:\AI\StableDiffusion\Lora
Adding extra search path vae R:\AI\StableDiffusion\vae
Web extensions folder found at R:\AI\ComfyUI\ComfyUI\web\extensions\ComfyLiterals
Adding R:\AI\ComfyUI\ComfyUI\custom_nodes to sys.path
Efficiency Nodes: Attempting to add Control Net options to the 'HiRes-Fix Script' Node (comfyui_controlnet_aux add-on)...Success!
Loaded Efficiency nodes from R:\AI\ComfyUI\ComfyUI\custom_nodes\efficiency-nodes-comfyui
Loaded ControlNetPreprocessors nodes from R:\AI\ComfyUI\ComfyUI\custom_nodes\comfyui_controlnet_aux
Loaded AdvancedControlNet nodes from R:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
Could not find AnimateDiff nodes
Loaded IPAdapter nodes from R:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
Could not find VideoHelperSuite nodes
### Loading: ComfyUI-Impact-Pack (V5.11.4)
### Loading: ComfyUI-Impact-Pack (Subpack: V0.6)
### Loading: ComfyUI-Impact-Pack (V5.11.4)
Loaded ImpactPack nodes from R:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
[Impact Pack] Wildcards loading done.
[Impact Pack] Wildcards loading done.
### Loading: ComfyUI-Impact-Pack (V5.11.4)
[Impact Pack] Wildcards loading done.
### Loading: ComfyUI-Inspire-Pack (V0.75.2)
Total VRAM 12287 MB, total RAM 32618 MB
pytorch version: 2.3.1+cu121
xformers version: 0.0.26.post1
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3060 : cudaMallocAsync
VAE dtype: torch.bfloat16
### Loading: ComfyUI-Manager (V2.36.1)
### ComfyUI Revision: 2250 [5eb98f00] | Released on '2024-06-13'
### Loading: ComfyUI-Manager (V2.36.1)
[ComfyUI-Manager] Some features are restricted due to your ComfyUI being outdated.
### ComfyUI Revision: 2250 [5eb98f00] | Released on '2024-06-13'
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json

[notice] A new release of pip is available: 23.0.1 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip
_PS_ All packages are installed.
_PS_ backend_path R:\AI\ComfyUI\ComfyUI\custom_nodes\comfyui-photoshop\Backend.py
Failed to auto update `Quality of Life Suit`
QualityOfLifeSuit_Omar92_DIR: R:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-QualityOfLifeSuit_Omar92
_PS_ Plugin is not updated, installing. . .
_PS_ Installed plugin in C:\Users\user pc\AppData\Roaming\Adobe\UXP\Plugins\External and updated PS.json
_PS_ RESTART YOUR PHOTOSHOP AND LAUNCH THE PLUGIN
_PS_ server started
[ReActor] - STATUS - Running v0.5.0-b3 in ComfyUI
Torch version: 2.3.1+cu121
[comfy_mtb] | INFO -> loaded 78 nodes successfuly

[rgthree] Loaded 39 magnificent nodes.
[rgthree] Will use rgthree's optimized recursive execution.

WAS Node Suite: OpenCV Python FFMPEG support is enabled
WAS Node Suite Warning: `ffmpeg_bin_path` is not set in `R:\AI\ComfyUI\ComfyUI\custom_nodes\was-node-suite-comfyui\was_suite_config.json` config file. Will attempt to use system ffmpeg binaries if available.
WAS Node Suite: Finished. Loaded 213 nodes successfully.

        "Success is not in what you have, but who you are." - Bo Bennett


Import times for custom nodes:
   0.0 seconds: R:\AI\ComfyUI\ComfyUI\custom_nodes\dequality.py
   0.0 seconds: R:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
   0.0 seconds: R:\AI\ComfyUI\ComfyUI\custom_nodes\efficiency-nodes-comfyui
   0.0 seconds: R:\AI\ComfyUI\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds: R:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-CascadeResolutions
   0.0 seconds: R:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Logic
   0.0 seconds: R:\AI\ComfyUI\ComfyUI\custom_nodes\sdxl_prompt_styler
   0.0 seconds: R:\AI\ComfyUI\ComfyUI\custom_nodes\cg-use-everywhere
   0.0 seconds: R:\AI\ComfyUI\ComfyUI\custom_nodes\sd-perturbed-attention
   0.0 seconds: R:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Eagle-PNGInfo
   0.0 seconds: R:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
   0.0 seconds: R:\AI\ComfyUI\ComfyUI\custom_nodes\comfyui_controlnet_aux
   0.0 seconds: R:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyLiterals
   0.0 seconds: R:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI_restart_sampling
   0.0 seconds: R:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-QualityOfLifeSuit_Omar92
   0.0 seconds: R:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI_essentials
   0.0 seconds: R:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
   0.0 seconds: R:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
   0.0 seconds: R:\AI\ComfyUI\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds: R:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-KJNodes
   0.0 seconds: R:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved
   0.0 seconds: R:\AI\ComfyUI\ComfyUI\custom_nodes\comfy-image-saver
   0.0 seconds: R:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyI2I
   0.0 seconds: R:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI_TensorRT
   0.1 seconds: R:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Inspire-Pack
   0.2 seconds: R:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI_smZNodes
   0.4 seconds: R:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager
   0.4 seconds: R:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager-main
   0.9 seconds: R:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI_InstantID
   1.1 seconds: R:\AI\ComfyUI\ComfyUI\custom_nodes\comfyui-art-venture
   1.1 seconds: R:\AI\ComfyUI\ComfyUI\custom_nodes\comfyui-reactor-node
   1.5 seconds: R:\AI\ComfyUI\ComfyUI\custom_nodes\comfyui-photoshop
   2.1 seconds: R:\AI\ComfyUI\ComfyUI\custom_nodes\was-node-suite-comfyui
   2.1 seconds: R:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-SUPIR
   4.0 seconds: R:\AI\ComfyUI\ComfyUI\custom_nodes\comfy_mtb

Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: R:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
HTTP Request: GET https://api.openai.com/v1/models "HTTP/1.1 401 Unauthorized"
Error: OpenAI API key is invalid OpenAI features wont work for you
QualityOfLifeSuit_Omar92::NSP ready
_PS_ Node found in workflow: ('127.0.0.1', 65041)
_PS_ Photoshop is not connected
imPhotoshop
_PS_ Photoshop Connected: ('127.0.0.1', 65061)`

**Comment by junaid3d** [comment]
![Screenshot_1678](https://github.com/NimaNzrii/comfyui-photoshop/assets/131003205/0e599543-733d-417e-8ae3-4d855aa60089)
Also, presets are not loading

**Comment by NimaNzrii** [comment]
hi brother 
i have updated the plugin and the node again and i hope it works for you

please update the node and re install plugin

**Comment by junaid3d** [comment]
![Screenshot_1679](https://github.com/NimaNzrii/comfyui-photoshop/assets/131003205/aa02a23c-137a-45be-a549-6f4d78758fd4)
hey man, this is awesome. How to send the AI rendering back to the photoshop canvas again so we can draw over it?

**Comment by junaid3d** [comment]
![Screenshot_1680](https://github.com/NimaNzrii/comfyui-photoshop/assets/131003205/bef94f19-a791-45e9-8654-b40037b499e0)
Its basically not taking anything from the photoshop canvas and only rendering the prompt. e.g Cat etc.

**Comment by junaid3d** [comment]
![Screenshot_1682](https://github.com/NimaNzrii/comfyui-photoshop/assets/131003205/363db0e6-7abd-41e3-8318-e581a1ea1685)
Not updating the img2img image from photoshop

**Comment by junaid3d** [comment]
If I add any new element to the canvas or any brush etc. I have to reload the plugin from the panel then render again. Only then it updates.

**Comment by NimaNzrii** [comment]
check my youtube video
