### ISSUE TITLE
Settings: Image Processing Upscale if smaller Downscale if bigger

### ISSUE THREAD

**Issue by randykoala** [NimaNzrii/comfyui-photoshop#109]
What settings options are there for this - if i upscale an image, do i need to have a new canvas to load the larger image size - it always seems to downscale to fit

**Comment by NimaNzrii** [comment]
You can add it as layer on any document, and then double click on your layer thumbnail to see the real size!

**Comment by randykoala** [comment]
Thanks - user error lol :-)
