### ISSUE TITLE
[WinError 10061]

### ISSUE THREAD

**Issue by nadora35** [NimaNzrii/comfyui-photoshop#110]
![Untitled](https://github.com/NimaNzrii/comfyui-photoshop/assets/57017061/a12dc741-8642-43ea-b3fe-1f64ebba79dd)

**Comment by NimaNzrii** [comment]
Which node are u using

**Comment by nadora35** [comment]
> Which node are u using

![Untitled2](https://github.com/NimaNzrii/comfyui-photoshop/assets/57017061/97379e74-3adb-4c32-ac27-0cb03f66ab80)

**Comment by NimaNzrii** [comment]
Dod you tried to enable  remote connection on Photoshop setting? 

Otherwise you can use our Photoshop plugin in your ps 
Which is much more powerful abd easier to Use

**Comment by nadora35** [comment]
Dod you tried to enable remote connection on Photoshop setting?
yes im enable it
i want to test connection and it not happen

**Comment by nadora35** [comment]
![image](https://github.com/NimaNzrii/comfyui-photoshop/assets/57017061/8ec47fe3-aa38-410f-9738-393a994c9860)

**Comment by NimaNzrii** [comment]
So if you using plugin , you should use Photoshop to comfyui first node , not Remote connection one

**Comment by NimaNzrii** [comment]
Then just press the load sd1.5 workflow button on the node

**Comment by nadora35** [comment]
i want to use plugin with my own workflow with my free any thing i want to do

**Comment by nadora35** [comment]
give me screen shoot how to connect nod with defualt workfrlow image to image if you can plz

**Comment by therysin** [comment]
You can use the example workflow @NimaNzrii provided and incorporate your own workflow. Please see the videos posted as well. You have all the information available.

**Comment by nadora35** [comment]
![1](https://github.com/NimaNzrii/comfyui-photoshop/assets/57017061/7ed3cdaf-a241-430b-93f7-2378f299b126)
![2](https://github.com/NimaNzrii/comfyui-photoshop/assets/57017061/d53db1de-816d-4f4a-a852-5c091d23e89a)

**Comment by NimaNzrii** [comment]
Can you please send me your log file @nadora35

**Comment by nadora35** [comment]
[comfyui.log](https://github.com/user-attachments/files/15856551/comfyui.log)

**Comment by NimaNzrii** [comment]
could you please check if this path exist on your device or not?
H:\Data\Packages\ComfyUI\custom_nodes\comfyui-photoshop\Backend.py

this path should be exactly like this
@nadora35

**Comment by nadora35** [comment]
![Uploading 1.png…]()

**Comment by nadora35** [comment]
![1](https://github.com/NimaNzrii/comfyui-photoshop/assets/57017061/3cf8ff87-87d4-4ba6-9fa9-7ca8e6eb495c)

**Comment by nadora35** [comment]
@NimaNzrii  !!!??

**Comment by NimaNzrii** [comment]
Sorry for my late response, could you please test the latest ver

**Comment by nadora35** [comment]
ok i will test it .... thx

**Comment by nadora35** [comment]
![Untitled](https://github.com/NimaNzrii/comfyui-photoshop/assets/57017061/fdb63d6d-5b41-478f-a63c-44b0a33cc1f7)

Now i have this error @NimaNzrii

**Comment by nadora35** [comment]
![1](https://github.com/NimaNzrii/comfyui-photoshop/assets/57017061/77213759-ee5c-44d2-999b-528c9ee6b925)
![2](https://github.com/NimaNzrii/comfyui-photoshop/assets/57017061/f329c767-fba9-454c-98b1-2f5571ab3628)


Firstly, thank you for your effort, your help, and everything, but every time I try to run it, I encounter one problem after another, and every time a different problem... I very much wish to run this add-on because it is very useful for my work, but I have given up on this add-on and its problems. I have tried in various different ways, but nothing works. @NimaNzrii

**Comment by NimaNzrii** [comment]
# Fixed in V1.5.0 ✨
this problem should be fixed in ver 1.5.0
please update plugin and the node and let me know if it helped

**Comment by SmokeyRGB** [comment]
> # Fixed in V1.5.0 ✨
> this problem should be fixed in ver 1.5.0 please update plugin and the node and let me know if it helped

What exactly did you do to fix it? I haven't understood it from the commits but currently batteling the same error
