### ISSUE TITLE
Scheduler

### ISSUE THREAD

**Issue by randykoala** [NimaNzrii/comfyui-photoshop#112]
i have updated everything but am having issues with the Use everywhere connection for the schedular  it appears connected but getting an error KSampler 782:
  - Return type mismatch between linked nodes: scheduler, ['normal', 'karras', 'exponential', 'sgm_uniform', 'simple', 'ddim_uniform'] != ['AYS SVD', 'AYS SDXL', 'AYS SD1', 'ddim_uniform', 'simple', 'sgm_uniform', 'exponential', 'karras', 'normal'].
If i convert the Scheduler back to a widget it works finr

**Comment by NimaNzrii** [comment]
Can you please send me your log file? Are you using any translator node?

**Comment by randykoala** [comment]
[comfyui.log](https://github.com/user-attachments/files/15873073/comfyui.log)
No translator nodes - i did add some of my own created processes but they were working previously and now not even the original txt2img works

**Comment by randykoala** [comment]
![image](https://github.com/NimaNzrii/comfyui-photoshop/assets/8767066/3f727d7c-f14b-4c18-9f8f-17935a2f2b62)

**Comment by NimaNzrii** [comment]
Not working even on default workflow?

You can use the latest version of default workflow by hovering on the main Photoshop node

**Comment by randykoala** [comment]
[mypsd workflow.json](https://github.com/user-attachments/files/15873145/mypsd.workflow.json)

**Comment by randykoala** [comment]
just tried the latest version from this github and still same issue

**Comment by NimaNzrii** [comment]
Will fix it for in an hour

**Comment by NimaNzrii** [comment]
maybe there is some nodes that are preventing anything everywhere to work for u

your workflow working fine for me

im testing your workflow with sd1.5 and my loras ( because my pc cant handle sdxl:( ... ) 
and it seems everything is working

but i think you should not use lcm scheduler for sdxl hyper models

**Comment by randykoala** [comment]
odd - i unpacked your klsampler setting node to the various components and replaced the scheduler with the jps combined Sampler settings and than worked but it didnt work with the node from the Save image with Generation data which you had used maybe i need to reinstall that custom node set - which set is that from?

**Comment by mahougigi** [comment]
I also have this problem

```
* KSampler 755:
  - Return type mismatch between linked nodes: scheduler, ['normal', 'karras', 'exponential', 'sgm_uniform', 'simple', 'ddim_uniform'] != ['normal', 'karras', 'exponential', 'sgm_uniform', 'simple', 'ddim_uniform', 'AYS SD1', 'AYS SDXL', 'AYS SVD']
```

I checked all the nodes updated today and found that the problem was this node

···
efficiency-nodes-comfyui
···

I rolled back today’s update, just go back to 05-31 a5422d6, then It'll be fine.

**Comment by randykoala** [comment]
Sorry i am a bit slow with this git stuff. Is that doing a specific checkout command from the command prompt?

**Comment by NimaNzrii** [comment]
Fixed in the latest version mate
Thanks for your report
