### ISSUE TITLE
Add UTF8 encoding support to the plugin

### ISSUE THREAD

**Issue by mirchik** [NimaNzrii/comfyui-photoshop#113]
![image](https://github.com/NimaNzrii/comfyui-photoshop/assets/10577875/1debbdd2-455c-4364-9529-2c4f4a0c3517)

The default encoding of promt is Windows-1521, but hieroglyphs come to the browser, for example, I write the word in Russian in promt "**женщина**" and this word comes to the ComfyUI scheme in this form "**Р¶РµРЅС‰РёРЅР°**", is it possible to fix it?
![340453205-a6c687b5-297f-458f-97a8-8a88fcbb6793](https://github.com/NimaNzrii/comfyui-photoshop/assets/10577875/a7299c83-0d6c-480a-b1f0-2ccc9c27dd65)
![340453318-1e87ddf5-dcf3-4cec-8410-3e6f0c05838f](https://github.com/NimaNzrii/comfyui-photoshop/assets/10577875/55c99dd3-d7d3-43a5-afba-d1c85b4b2f03)

**Comment by NimaNzrii** [comment]
Done!
Update the node and enjoy!

No need to re install the plugin

**Comment by mirchik** [comment]
great, thank you very much
