### ISSUE TITLE
Error occurred when executing ControlNetApplyAdvanced:

### ISSUE THREAD

**Issue by loztm** [NimaNzrii/comfyui-photoshop#114]
Hello. I updated the plugin and workflow today but got this error (I'm new in all this so I don't know how to fix it)
_________________________________________________________
Error occurred when executing ControlNetApplyAdvanced:

ControlNetApplyAdvanced.apply_controlnet() missing 4 required positional arguments: 'positive', 'negative', 'control_net', and 'image'

File "D:\Programas\comfyui\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\Programas\comfyui\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\Programas\comfyui\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by NimaNzrii** [comment]
Could u please send an screenshot of your workflow
