### ISSUE TITLE
Scheduler cannot be linked, return value does not match

### ISSUE THREAD

**Issue by smalltotal** [NimaNzrii/comfyui-photoshop#117]
I encountered a new problem. It should be that the Scheduler data type does not match and cannot be linked normally. Please see the example picture
![微信截图_20240620135131](https://github.com/NimaNzrii/comfyui-photoshop/assets/45705692/a354e1ec-c7f8-4ce8-b4a1-8ffdad984cd8)
![微信图片_20240620134940](https://github.com/NimaNzrii/comfyui-photoshop/assets/45705692/b2927825-bee4-4c2e-8500-25b89c0a18a7)
![微信截图_20240620135000](https://github.com/NimaNzrii/comfyui-photoshop/assets/45705692/1c08d039-5207-45c1-b71a-b7d33d2441ba)
![微信截图_20240620134650](https://github.com/NimaNzrii/comfyui-photoshop/assets/45705692/515c0dfa-6473-40cd-87cb-b4dd85472208)

**Comment by randykoala** [comment]
Have a look at issue 112 - there is a conflict with efficiency nodes if you have that installed - a rollback should fix this

**Comment by NimaNzrii** [comment]
@randykoala @smalltotal https://openart.ai/workflows/spoonbill_hospitable_34/sd15---comfyui-in-photoshop/lreWarJbqiYPcDXnD8hh

Please trry this version of workflow

**Comment by smalltotal** [comment]
Indeed, the problem was solved by downloading the new workflow. Thank you very much

**Comment by NimaNzrii** [comment]
Fixed in the latest update
