### ISSUE TITLE
Unable to read workflow switch

### ISSUE THREAD

**Issue by liulsg** [NimaNzrii/comfyui-photoshop#118]
PS version: v25
Comfyui Version: [2f360ae8]
All other functions are normal.
The latest for workflow.
![image](https://github.com/NimaNzrii/comfyui-photoshop/assets/97494068/75a61e8a-e7dd-44a9-afaa-862b2adf2a89)

**Comment by NimaNzrii** [comment]
Could you please take an screenshot of your workflow 

Are you on mac?

**Comment by liulsg** [comment]
windows11
I used the workflow you provided, I just changed the model and nothing else.

![image](https://github.com/NimaNzrii/comfyui-photoshop/assets/97494068/22c5d744-1247-42c7-a99d-780d7cea2193)

**Comment by liulsg** [comment]
[workflow-sd15---comfyui-in-photoshop-lreWarJbqiYPcDXnD8hh-spoonbill_hospitable_34-openart.ai.json](https://github.com/user-attachments/files/15943874/workflow-sd15---comfyui-in-photoshop-lreWarJbqiYPcDXnD8hh-spoonbill_hospitable_34-openart.ai.json)
This is the workflow I downloaded.

**Comment by NimaNzrii** [comment]
it seems smt changed the name of the green node under 🔹photoshop node 
the name should be "⚙️ Render Setting" for green node and "📁 WorkFlows" for the blue node


i will try to use another method to fix it for next update

**Comment by NimaNzrii** [comment]
hey brother . the problem should be fixed now

update the node and enjoy

no need to update plugin or workflow

**Comment by liulsg** [comment]
Thank you for your work, I only upgraded the nodes, one of them is already displayed correctly, and the other is not displayed correctly.
![image](https://github.com/NimaNzrii/comfyui-photoshop/assets/97494068/cf8c9c9b-3215-48bb-85a0-3e1f177d7963)

**Comment by liulsg** [comment]
It seems that if I copy the name you provide, I can read it.

**Comment by liulsg** [comment]
Plugin version: [617ccea] 
1.comfyui English version: Only one of them can be loaded, but if the name is copied, all can be displayed.   
2. comfyui is converted to non-English mode by plug-in: only one of them can be loaded, even if the name is changed as required, only one will be displayed.  
 Plugin location ([AIGODLIKE-ComfyUI-Translation](https://github.com/AIGODLIKE/AIGODLIKE-ComfyUI-Translation)) 

 Note: comfyui English version to non-English version--> The name of the switch will change automatically.   Also I think this is great because you can switch node workflows in photoshop.  I'll just use the report to give you feedback.

**Comment by KINGLIFER** [comment]
So what is the fix?

**Comment by NimaNzrii** [comment]
@liulsg @KINGLIFER 
### thank you for your reoprts

**Fixed**
Update the node and enjoy

no need to update plugin or workflow

**Comment by liulsg** [comment]
@NimaNzrii 
Preferences are already displayed correctly, but I see that the code is still the title name of the search.
Here's a suggestion for you:
Add two text input boxes to the accept node, which correspond to the ID of the switch node respectively. Users can input them themselves. This may be more reliable than automatic retrieval of the title, because the name of the switch node seems to change.
Switching between languages causes node names to change, but node IDs are relatively fixed (unless deleted and added).
