### ISSUE TITLE
After the update, can you post a video explaining how to use it?

### ISSUE THREAD

**Issue by laitianwen** [NimaNzrii/comfyui-photoshop#12]

**Comment by laitianwen** [comment]
path“C:\\Users\\user\\AppData\\Roaming\\Adobe\\UXP\\PluginsStorage\\PHSP\\25\\External\\3e6d64e0\\PluginData”
I open path  no“3e6d64e0\\PluginData”

**Comment by NimaNzrii** [comment]
is there any chance to let me connect more to you to fix this error for you?
its so important for me to make it run correctly for you

**Comment by laitianwen** [comment]
This is my error code：

Error occurred when executing 🔹Photoshop ComfyUI Plugin:

Failed to load configuration after 5 attempts.

File "E:\sd\comfyui\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "E:\sd\comfyui\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "E:\sd\comfyui\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "E:\sd\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-photoshop\node-Photoshop.py", line 31, in PS_Execute
self.loadConfig()
File "E:\sd\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-photoshop\node-Photoshop.py", line 73, in loadConfig
self.loadConfig(retry_count + 1)
File "E:\sd\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-photoshop\node-Photoshop.py", line 73, in loadConfig
self.loadConfig(retry_count + 1)
File "E:\sd\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-photoshop\node-Photoshop.py", line 73, in loadConfig
self.loadConfig(retry_count + 1)
[Previous line repeated 1 more time]
File "E:\sd\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-photoshop\node-Photoshop.py", line 75, in loadConfig
raise Exception("Failed to load configuration after 5 attempts.")

**Comment by laitianwen** [comment]
I think there's something wrong with the loading path. Does that have anything to do with my Photoshop Beta? As I said above, my path is missing files,

**Comment by NimaNzrii** [comment]
can you send me the data inside this file plz: 
ComfyUI\custom_nodes\comfyui-photoshop\data.json

**Comment by laitianwen** [comment]
{"dataDir": "C:\\Users\\user\\AppData\\Roaming\\Adobe\\UXP\\PluginsStorage\\PHSP\\25\\External\\3e6d64e0\\PluginData"}

**Comment by laitianwen** [comment]
![1714757056983](https://github.com/NimaNzrii/comfyui-photoshop/assets/149393667/4f8cc4ea-3c58-453e-b661-32c56a284952)
I'm missing this file

**Comment by laitianwen** [comment]
![1714757166263](https://github.com/NimaNzrii/comfyui-photoshop/assets/149393667/b64cc555-5ced-4934-8758-902226fff938)
Can I use this file?  “PHSPbeta ”

**Comment by NimaNzrii** [comment]
Is the plugin loading successfuly on your photoshop?

**Comment by laitianwen** [comment]
![Uploading 1714757292037.jpg…]()

**Comment by NimaNzrii** [comment]
Are you using 2 photoshop rn?

**Comment by laitianwen** [comment]
好像截图加载不出来，但是我很肯定插件安装成功了

**Comment by laitianwen** [comment]
It looks like the screenshot didn't load, but I'm pretty sure the plug-in was installed successfully

**Comment by laitianwen** [comment]
![1714757457400](https://github.com/NimaNzrii/comfyui-photoshop/assets/149393667/fe797b39-d4a4-4705-bcc2-8a71d7a5a83e)

**Comment by NimaNzrii** [comment]
Great , i found the bug , thank you a lot for your reply , i will trxt you as soon as possible after fixing it

It seems the beta version of photoshop is using another path.


You can test these things: 
1-Close both Photoshops
2-Open your beta photoshop and run the plugin
3- press on get started on your plugin
4- fully close your comfyui and run it again

Plz tell me the result 

I'm trying to install beta version of Photoshop to see if i have the same issue or not❤️

**Comment by laitianwen** [comment]
oook,I'll try

**Comment by laitianwen** [comment]
Cool! !! It's working, and the interface is amazing，thank U!
Cool! !! It's working, and the interface is amazing，thank U!

江离
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "NimaNzrii/comfyui-photoshop"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月5日(星期天) 凌晨0:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [NimaNzrii/comfyui-photoshop] After the update, can you post a video explaining how to use it? (Issue #12)





 
Closed #12 as completed.

**Comment by laitianwen** [comment]
There's a small issue, I'm not even sure if it's an issue, I painted a mask in ComfyUI, set it to auto-crop and enlarge to 1024, then rendered it, and finally scaled it back to the original image, which ensures the details of the mask area. However, when I drew a mask in Photoshop and sent it to ComfyUI, the mask area wasn't cropped and enlarged, but the entire image was scaled, not just the mask area, which didn't enlarge and render my mask The picture of the cat has not been automatically cropped and scaled：




江离
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "NimaNzrii/comfyui-photoshop"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月5日(星期天) 凌晨0:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [NimaNzrii/comfyui-photoshop] After the update, can you post a video explaining how to use it? (Issue #12)





 
Closed #12 as completed.

**Comment by NimaNzrii** [comment]
I'm so sorry i couldn't really understand.
Is there anyway to show it using a picture or something?

**Comment by laitianwen** [comment]
ok,I'll send you a comparison later




江离
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "NimaNzrii/comfyui-photoshop"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月5日(星期天) 中午1:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [NimaNzrii/comfyui-photoshop] After the update, can you post a video explaining how to use it? (Issue #12)





 
I'm so sorry i couldn't really understand.
 Is there anyway to show it using a picture or something?

**Comment by okneu** [comment]
I'm sorry to revive this closed issue but I'm on a Mac and I'm getting a similar error:


```
Error occurred when executing 🔹Photoshop ComfyUI Plugin:

Failed to load directory after 5 attempts.
🔴 Make sure you have installed and started the Photoshop Plugin Succesfully.
🔴 otherwise you can restart your photosop and your plugin to Fix this problem

File "/Users/neu/AI/ComfyUI/ComfyUI/execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/neu/AI/ComfyUI/ComfyUI/execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/neu/AI/ComfyUI/ComfyUI/execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/neu/AI/ComfyUI/ComfyUI/custom_nodes/comfyui-photoshop/node-Photoshop.py", line 33, in PS_Execute
self.loadConfig()
File "/Users/neu/AI/ComfyUI/ComfyUI/custom_nodes/comfyui-photoshop/node-Photoshop.py", line 75, in loadConfig
self.loadConfig(retry_count + 1)
File "/Users/neu/AI/ComfyUI/ComfyUI/custom_nodes/comfyui-photoshop/node-Photoshop.py", line 75, in loadConfig
self.loadConfig(retry_count + 1)
File "/Users/neu/AI/ComfyUI/ComfyUI/custom_nodes/comfyui-photoshop/node-Photoshop.py", line 75, in loadConfig
self.loadConfig(retry_count + 1)
[Previous line repeated 1 more time]
File "/Users/neu/AI/ComfyUI/ComfyUI/custom_nodes/comfyui-photoshop/node-Photoshop.py", line 77, in loadConfig
raise Exception("Failed to load directory after 5 attempts. \n 🔴 Make sure you have installed and started the Photoshop Plugin Succesfully. \n 🔴 otherwise you can restart your photosop and your plugin to Fix this problem")
```
I checked the content of the ComfyUI\custom_nodes\comfyui-photoshop\data.json file and it is `{ "dataDir": "" }`
Is this correct for MacOS? I haven't been able to make the plugin work after 2 installations following your step-by-step guide, if you can help me I would be very grateful!

**Comment by okneu** [comment]
After some searching, I found the path for my MacOS installation of the plugin and modified the data.json file to this `{ "dataDir": "/Users/neu/Library/Application Support/Adobe/UXP/PluginsStorage/PHSPBETA/25/External/3e6d64e0/PluginData" }`
It is still not working but now gives me a completly different error:
```
Error occurred when executing LoraLoader:

'NoneType' object has no attribute 'lower'

File "/Users/neu/AI/ComfyUI/ComfyUI/execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/neu/AI/ComfyUI/ComfyUI/execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/neu/AI/ComfyUI/ComfyUI/execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/neu/AI/ComfyUI/ComfyUI/nodes.py", line 609, in load_lora
lora = comfy.utils.load_torch_file(lora_path, safe_load=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/neu/AI/ComfyUI/ComfyUI/comfy/utils.py", line 13, in load_torch_file
if ckpt.lower().endswith(".safetensors"):
^^^^^^^^^^
```
