### ISSUE TITLE
Remote Connection Unable to Connect

### ISSUE THREAD

**Issue by huameiwei-vc** [NimaNzrii/comfyui-photoshop#120]
<img width="605" alt="image" src="https://github.com/NimaNzrii/comfyui-photoshop/assets/125441847/647587ff-7549-433a-8c79-c0c185df27dd">
I have a mac locally and it is very slow and is connectable.
But when I use an online gpu server, I can't connect.

**Comment by EpicMulletGuy** [comment]
I can get the ComfyUI WebApp working on another local machine, but the "ComfyUI IP Address" won't connect. Fresh ComfyUI installed with --listen 0.0.0.0 argument no other changes. Port forwarding rules in place and firewall (the ComfuUI server is loading fine on other machines on the network).  Not sure what else to try its showing up within photoshop fine on the WebApp just not the Server connect.

**Comment by TweetyToul** [comment]
Same issue here. local server is up and reachable. tried all variations i can think of

**Comment by FugueSegue** [comment]
I am having the same problem. My ComfyUI running the most recent version of the comfyui-photoshop workflow seems to work and all of the custom nodes and models are installed. My ComfyUI is running on a computer with an RTX A5000 that is completely dedicated to running only SD software. I installed the plug-in for Photoshop on my workstation. My Photoshop is the most recent version and is not pirated. I cannot connect Photoshop with ComfyUI.

**Comment by huameiwei-vc** [comment]
The comfyui I run online, it doesn't always run on port 8188, and the URL basically doesn't come with a port number, I checked the photoshop extension and it has port 8188 in it, I tried to change it and run it, and as usual, it doesn't connect

**Comment by EpicMulletGuy** [comment]
Did a little more digging.

used --listen 127.0.0.1 and also --listen 0.0.0.0 in the comfyui config, no change, could still connect both on local machine and none local using EXTERNALIP:8188 on web browser. Same situation the plugin and comfy both work fine on local machine zero issues. On none local machine however only the browser comfy works in and the photoshops app browser. The server does not connect. I noticed though the workflow was missing when i connected on the none local machine and had to reload it i hoped this would solve the issue but nope. 

I discovered this in the terminal window. It always defaults to 127.0.0.1 regardless what you put for --listen or server URL you connect to that works. When going to 127.0.0.1:8188 the workflow is again gone "no workflow". I figured i would just reload it again from that URL and maybe it would all work. Nope.. Tried restarting photoshop and doing it in random order but still nothing. Even with the workflow showing in the webapp within photoshop still nothing.  It's as if the workflow is constantly being wiped so it can never connect as the workflow is essentially unloaded 100% of the time. Loading it in the webapp or browser just makes a separate instance of it to the "server". So the "server" is not seeing any workflow and one cant be loaded. I am not sure if there if a comfyUI config to force the same workflow as default maybe this would solve the issue? Or maybe some code can be added to force load the workflow on the "server" window? 

![Screenshot 2024-07-01 070059](https://github.com/NimaNzrii/comfyui-photoshop/assets/21079119/b7b78423-3cf0-43e6-bbbf-48b69d84a787)

**Comment by guyuehu2304** [comment]
I hope the author will improve it as soon as possible, everyone is waiting

**Comment by jtc-jtc** [comment]
I am having the same/similar issue running photoshop plugin 1.4.3 on MacOS 14.5. Comfyui on windows local network machine. Photoshop plugin can successfully connect to the comfyui on local network but the Photoshop remote connection node can not find the plugin. 
![CleanShot 2024-07-09 at 15 07 10@2x](https://github.com/NimaNzrii/comfyui-photoshop/assets/30127464/69c0d1f8-8943-465a-8996-c44ab9c4d97e)
![CleanShot 2024-07-09 at 15 03 57@2x](https://github.com/NimaNzrii/comfyui-photoshop/assets/30127464/4445c537-988f-4fde-b5b8-188da0e5adae)

**Comment by huameiwei-vc** [comment]
New version 1.50, still can't connect to this https://z2l954n7-8080.usw3.devtunnels.ms

**Comment by NimaNzrii** [comment]
Bro This is only for local gpus for now!

But i have added it on beta version and will launch it soon

**Comment by EpicMulletGuy** [comment]
> Bro This is only for local gpus for now!
> 
> But i have added it on beta version and will launch it soon

thanks for the update look forward to seeing it all working :) It is a fantastic plugin btw.

**Comment by NimaNzrii** [comment]
# Check out the latest video to fix

https://www.youtube.com/watch?v=9wGixLsRH-I
<img width="1280" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNnVjQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--41a4c054363f5f0869c10dacf3957cfd0013acec/image.png" alt="image.png" />
