### ISSUE TITLE
Everywhere3 vs Everywhere?

### ISSUE THREAD

**Issue by randykoala** [NimaNzrii/comfyui-photoshop#122]
In trying to create a process for the new latent vision "mad scientist" i had an issue where the mad scientist node has two image inputs, one for positive and one for negative - however to stop the negative_image picking up the beam from the IMG and Mask use everywhere node i replaced it with the Anything Everywhere? node. Then by renaming the negative image input to none and mask to none i managed to prevent the automatic connection. I think it would be better to use the ? node for any other nodes that have multiple inputs 
![image](https://github.com/NimaNzrii/comfyui-photoshop/assets/8767066/c0dcee2c-77d1-4775-a2e9-d2f53012d4b3)
![image](https://github.com/NimaNzrii/comfyui-photoshop/assets/8767066/a8e34e77-9142-41de-a6bc-0669812c6ee5)

**Comment by NimaNzrii** [comment]
Kinda agree with you, i think your method is much easier to use and learn
