### ISSUE TITLE
LoadLorasFromPrompt ...

### ISSUE THREAD

**Issue by Torcelllo** [NimaNzrii/comfyui-photoshop#125]
... is not available! ComfyUI as backend.

![lOADlORAfROMpROMPT](https://github.com/NimaNzrii/comfyui-photoshop/assets/114806454/65d5fa9d-cce4-4aed-88f1-7bb22f479a0c)

Win 10, PS Beta

**Comment by NimaNzrii** [comment]
wait what?
is that an error from your comfy or ps?

**Comment by Torcelllo** [comment]
Comfy
