### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by BenderBlender** [NimaNzrii/comfyui-photoshop#13]
In the morning, something else was working (transferring the image to the comfy, but not back). And now it has stopped working altogether.
![image](https://github.com/NimaNzrii/comfyui-photoshop/assets/116355906/51942d22-cbfb-4173-b64d-27eb9898a7ce)

**Comment by NimaNzrii** [comment]
is there any chance to let me connect more to you to fix this error for you?
its so important for me to make it run correctly for you guys
