### ISSUE TITLE
This is really great.

### ISSUE THREAD

**Issue by naiyansui2023** [NimaNzrii/comfyui-photoshop#14]
This is really great. He can work now. But now I have a problem? The model won't load and the slider doesn't show the numbers

![微信截图_20240504230858](https://github.com/NimaNzrii/comfyui-photoshop/assets/130981007/7af1dfa0-6d2e-41e9-b0f3-a5ab46b2e7d0)
![微信截图_20240504230915](https://github.com/NimaNzrii/comfyui-photoshop/assets/130981007/fe8677c2-5fa6-4e9c-a601-667e4949326f)

**Comment by NimaNzrii** [comment]
Which browser are you using , can you try different browser for comfyui?

**Comment by NimaNzrii** [comment]
> This is really great. He can work now. But now I have a problem? The model won't load and the slider doesn't show the numbers
> 
> ![微信截图_20240504230858](https://private-user-images.githubusercontent.com/130981007/327957328-7af1dfa0-6d2e-41e9-b0f3-a5ab46b2e7d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4NzgxNDEsIm5iZiI6MTcxNDg3Nzg0MSwicGF0aCI6Ii8xMzA5ODEwMDcvMzI3OTU3MzI4LTdhZjFkZmEwLTZkMmUtNDFlOS1iMGYzLWE1YWI0NmIyZTdkMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwNVQwMjU3MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZTBmZjM5MGY1NTQ3ZDU3YjUyNTE1ZjNmZDg3ZGRiNzlhYzhjZThjNTEyYTI3ZjY1OWZiMzc4MzU4MzhmZTBlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5Zc40UZKNgpL3DoNUI4mRqKY2cYRbr6Ki6D8IPBFl5E) ![微信截图_20240504230915](https://private-user-images.githubusercontent.com/130981007/327957332-fe8677c2-5fa6-4e9c-a601-667e4949326f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4NzgxNDEsIm5iZiI6MTcxNDg3Nzg0MSwicGF0aCI6Ii8xMzA5ODEwMDcvMzI3OTU3MzMyLWZlODY3N2MyLTVmYTYtNGU5Yy1hNjAxLTY2N2U0OTQ5MzI2Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwNVQwMjU3MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZmE5ZWU5NGU0OTlkNjM5YjcyMjliYjAyOGRlNDU5YmY1YTA0MmM1ZjFmODgxZDEyYmRmZjFkMzFjNzhlYmQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.mbcGIrELZgD3aLMRzUoJK34FquedkJn53Rj4QCLnBcs)

Which browser are you using , can you try different browser for comfyui?

**Comment by naiyansui2023** [comment]
> > 这真的很棒。他现在可以工作了。但现在我有问题了吗？模型无法加载，滑块不显示数字

> 您使用的是哪种浏览器，您可以尝试不同的浏览器吗？

我用的是edge

**Comment by naiyansui2023** [comment]
> > This is really great. He can work now. But now I have a problem? The model won't load and the slider doesn't show the numbers
> > ![微信截图_20240504230858](https://private-user-images.githubusercontent.com/130981007/327957328-7af1dfa0-6d2e-41e9-b0f3-a5ab46b2e7d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4NzgxNDEsIm5iZiI6MTcxNDg3Nzg0MSwicGF0aCI6Ii8xMzA5ODEwMDcvMzI3OTU3MzI4LTdhZjFkZmEwLTZkMmUtNDFlOS1iMGYzLWE1YWI0NmIyZTdkMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwNVQwMjU3MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZTBmZjM5MGY1NTQ3ZDU3YjUyNTE1ZjNmZDg3ZGRiNzlhYzhjZThjNTEyYTI3ZjY1OWZiMzc4MzU4MzhmZTBlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5Zc40UZKNgpL3DoNUI4mRqKY2cYRbr6Ki6D8IPBFl5E) ![微信截图_20240504230915](https://private-user-images.githubusercontent.com/130981007/327957332-fe8677c2-5fa6-4e9c-a601-667e4949326f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4NzgxNDEsIm5iZiI6MTcxNDg3Nzg0MSwicGF0aCI6Ii8xMzA5ODEwMDcvMzI3OTU3MzMyLWZlODY3N2MyLTVmYTYtNGU5Yy1hNjAxLTY2N2U0OTQ5MzI2Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwNVQwMjU3MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZmE5ZWU5NGU0OTlkNjM5YjcyMjliYjAyOGRlNDU5YmY1YTA0MmM1ZjFmODgxZDEyYmRmZjFkMzFjNzhlYmQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.mbcGIrELZgD3aLMRzUoJK34FquedkJn53Rj4QCLnBcs)
> 
> Which browser are you using , can you try different browser for comfyui?

I'm using the edge.

**Comment by NimaNzrii** [comment]
> > > This is really great. He can work now. But now I have a problem? The model won't load and the slider doesn't show the numbers
> > > ![微信截图_20240504230858](https://private-user-images.githubusercontent.com/130981007/327957328-7af1dfa0-6d2e-41e9-b0f3-a5ab46b2e7d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4NzgxNDEsIm5iZiI6MTcxNDg3Nzg0MSwicGF0aCI6Ii8xMzA5ODEwMDcvMzI3OTU3MzI4LTdhZjFkZmEwLTZkMmUtNDFlOS1iMGYzLWE1YWI0NmIyZTdkMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwNVQwMjU3MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZTBmZjM5MGY1NTQ3ZDU3YjUyNTE1ZjNmZDg3ZGRiNzlhYzhjZThjNTEyYTI3ZjY1OWZiMzc4MzU4MzhmZTBlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5Zc40UZKNgpL3DoNUI4mRqKY2cYRbr6Ki6D8IPBFl5E) ![微信截图_20240504230915](https://private-user-images.githubusercontent.com/130981007/327957332-fe8677c2-5fa6-4e9c-a601-667e4949326f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4NzgxNDEsIm5iZiI6MTcxNDg3Nzg0MSwicGF0aCI6Ii8xMzA5ODEwMDcvMzI3OTU3MzMyLWZlODY3N2MyLTVmYTYtNGU5Yy1hNjAxLTY2N2U0OTQ5MzI2Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwNVQwMjU3MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZmE5ZWU5NGU0OTlkNjM5YjcyMjliYjAyOGRlNDU5YmY1YTA0MmM1ZjFmODgxZDEyYmRmZjFkMzFjNzhlYmQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.mbcGIrELZgD3aLMRzUoJK34FquedkJn53Rj4QCLnBcs)
> > 
> > 
> > Which browser are you using , can you try different browser for comfyui?
> 
> I'm using the edge.
does the play button queue your comfyui?

can you test it wit another browser?

**Comment by naiyansui2023** [comment]
> > > > This is really great. He can work now. But now I have a problem? The model won't load and the slider doesn't show the numbers
> > > > ![微信截图_20240504230858](https://private-user-images.githubusercontent.com/130981007/327957328-7af1dfa0-6d2e-41e9-b0f3-a5ab46b2e7d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4NzgxNDEsIm5iZiI6MTcxNDg3Nzg0MSwicGF0aCI6Ii8xMzA5ODEwMDcvMzI3OTU3MzI4LTdhZjFkZmEwLTZkMmUtNDFlOS1iMGYzLWE1YWI0NmIyZTdkMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwNVQwMjU3MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZTBmZjM5MGY1NTQ3ZDU3YjUyNTE1ZjNmZDg3ZGRiNzlhYzhjZThjNTEyYTI3ZjY1OWZiMzc4MzU4MzhmZTBlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5Zc40UZKNgpL3DoNUI4mRqKY2cYRbr6Ki6D8IPBFl5E) ![微信截图_20240504230915](https://private-user-images.githubusercontent.com/130981007/327957332-fe8677c2-5fa6-4e9c-a601-667e4949326f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4NzgxNDEsIm5iZiI6MTcxNDg3Nzg0MSwicGF0aCI6Ii8xMzA5ODEwMDcvMzI3OTU3MzMyLWZlODY3N2MyLTVmYTYtNGU5Yy1hNjAxLTY2N2U0OTQ5MzI2Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwNVQwMjU3MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZmE5ZWU5NGU0OTlkNjM5YjcyMjliYjAyOGRlNDU5YmY1YTA0MmM1ZjFmODgxZDEyYmRmZjFkMzFjNzhlYmQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.mbcGIrELZgD3aLMRzUoJK34FquedkJn53Rj4QCLnBcs)
> > > 
> > > 
> > > Which browser are you using , can you try different browser for comfyui?
> > 
> > 
> > I'm using the edge.
> > does the play button queue your comfyui?
> 
> can you test it wit another browser?

I tried to use chrome and the result is still the same, all the processes are normal and work, but the model can't be loaded to show inside photoshop
![Uploading d1as21ad1.png…]()

**Comment by lzhfdwu007** [comment]
One of the problems I had was the same as this one
My browser is also Edge

**Comment by NimaNzrii** [comment]
# Fixed in V1.5.0 ✨
this problem should be fixed in ver 1.5.0
please update plugin and the node and let me know if it helped
