### ISSUE TITLE
IMPORT FAILED

### ISSUE THREAD

**Issue by huameiwei-vc** [NimaNzrii/comfyui-photoshop#146]
1.50导入失败，以前的版本在本地可用。
不知道是否缺少一些本地依赖。
网络gpu主机也无法导入。
无法测试这种链接：https://c6fvd0f8-8080.usw3.devtunnels.ms是否可用

**Comment by ialhabbal** [comment]
Same problem.

**Comment by NimaNzrii** [comment]
@ialhabbal @huameiwei-vc 
# fixed

Update the node and enjoy 

Thank you for your patience
