### ISSUE TITLE
restarting

### ISSUE THREAD

**Issue by magimyster** [NimaNzrii/comfyui-photoshop#149]
after installing the extension if I restart it gives me this error: 

Restarting... [Legacy Mode]

C:\AI\ComfyUI_windows_portable\python_embeded\python.exe: can't open file 'C:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-photoshop\ComfyUI\main.py': [Error 2] No such file or directory

**Comment by NimaNzrii** [comment]
Wow that's kinda strange, will check it

**Comment by NimaNzrii** [comment]
# Fixed

thank you so much for your report🌱

**Comment by magimyster** [comment]
> # Fixed
> thank you so much for your report🌱

perfect! thank you!
