### ISSUE TITLE
connecting Comfyui and Photoshop

### ISSUE THREAD

**Issue by candlelighttx** [NimaNzrii/comfyui-photoshop#150]
![comfyui-1](https://github.com/user-attachments/assets/da6dff90-4c9b-4a9a-996c-5d4200f7fe48)
![photoshop-1](https://github.com/user-attachments/assets/9ce4a211-5981-4632-9360-7e36476d6390)
![photoshop-2](https://github.com/user-attachments/assets/149fa923-6927-4ee3-aba9-d82f2e195c84)
![stability-matrix-1](https://github.com/user-attachments/assets/4e8df95e-af9f-4eb5-84dc-700fa9d1f2c0)

Hello, Please See screenshots attached.
On Windows 11 desktop, I am connected to comfyui via stability Matrix http://127.0.0.1:8188/
I can see the comfyui photoshop workflow nodes in photoshop.
There is a red warning Comfyui IP address 127.0.0.1 “NOT Connected”.
Need help connecting comfyui and photoshop. Thanks!

**Comment by 907590629** [comment]
i have same issue

**Comment by feeaa** [comment]
i have same issue

**Comment by NimaNzrii** [comment]
Are guys all using stability matrix?

**Comment by mccabedd** [comment]
Finally got it to work. Here is what I did...

1) Uninstalled Photoshop with the AdobeCreativeCloudCleanerTool and then reinstalled Photoshop to the latest version.
2) Instead of manually unpacking the 3e6d64e0_PS.ccx file with 7zip, and copying to the plugins folder, used the suggested zxp_uxp installer.
3) Updated all my ComfyUI nodes
4) Used the latest workflow

Voila! All good :)

**Comment by pcarpenter-comfy** [comment]
Running comyfui on M2 mac and experiencing "# PS: PS not connected" error plugin loaded.  all models and required files added and updated also tried above fix by mccabedd. still not working 
![Screenshot 2024-07-30 at 5 05 09 PM](https://github.com/user-attachments/assets/7ac7b276-831a-4e45-9181-fac85a497ff0)
on the photoshop side and
![Screenshot 2024-07-30 at 5 06 24 PM](https://github.com/user-attachments/assets/82e282a6-0a6a-43d7-b65f-f26b380073fd)
on the comfyui side..  any help would be awesome excited to try this plugin

**Comment by mk230580** [comment]
> Finally got it to work. Here is what I did...
> 
> 1. Uninstalled Photoshop with the AdobeCreativeCloudCleanerTool and then reinstalled Photoshop to the latest version.
> 2. Instead of manually unpacking the 3e6d64e0_PS.ccx file with 7zip, and copying to the plugins folder, used the suggested zxp_uxp installer.
> 3. Updated all my ComfyUI nodes
> 4. Used the latest workflow
> 
> Voila! All good :)

It's work for me, Thanks @mccabedd

**Comment by pcarpenter-comfy** [comment]
> > Finally got it to work. Here is what I did...
> > 
> > 1. Uninstalled Photoshop with the AdobeCreativeCloudCleanerTool and then reinstalled Photoshop to the latest version.
> > 2. Instead of manually unpacking the 3e6d64e0_PS.ccx file with 7zip, and copying to the plugins folder, used the suggested zxp_uxp installer.
> > 3. Updated all my ComfyUI nodes
> > 4. Used the latest workflow
> > 
> > Voila! All good :)
> 
> It's work for me, Thanks @mccabedd

[mk230580](https://github.com/mk230580) are you running on a mac
