### ISSUE TITLE
Inpaint-CropAndStitch lots of masks

### ISSUE THREAD

**Issue by mirchik** [NimaNzrii/comfyui-photoshop#155]
https://github.com/lquesada/ComfyUI-Inpaint-CropAndStitch/issues/23

Is it possible to fix this problem, through your wonderful plugin it is not possible to use the Inpaint-CropAndStitch node, the author of this repository noted that the problem is in your plugin.

**Comment by NimaNzrii** [comment]
Hi this problem has been fixed in latest ver

**Comment by mirchik** [comment]
У меня стоит последняя версия, но данная проблема присутствует, пользоваться нодой CropAndStitch не получается.

**Comment by NimaNzrii** [comment]
can y you preview the mask you getting from photoshop node and send me the image please?
from v1.6.0

**Comment by mirchik** [comment]
![image](https://github.com/user-attachments/assets/4e660cac-3321-48fa-bcc8-414c6f67d696)

**Comment by mirchik** [comment]
![image](https://github.com/user-attachments/assets/bb7fde15-8866-47a4-94ae-a71711b391fd)

**Comment by mirchik** [comment]
> Можно ли предварительно просмотреть маску, которую вы создали из Photoshop Node, и отправить мне изображение, пожалуйста? из версии 1.6.0

the mask turns out to be correct, the colors are 000000 and ffffff, but it's still an error. If you save the mask and image with the Preview Image node and slip them separately, then everything works, but directly from Photoshop Node, then there is an error.

**Comment by NimaNzrii** [comment]
Will try this node in 5 min

**Comment by NimaNzrii** [comment]
# Fixed

Thank you for your report ❤️❤️

You Helped this project so much

**Comment by NimaNzrii** [comment]
Don't forget to update the node 
( No need to re-install plugin)
