### ISSUE TITLE
关于运行中没有报错，但是卡在采样器环节的错误

### ISSUE THREAD

**Issue by langrenlaile** [NimaNzrii/comfyui-photoshop#156]
Hello, Nima Nazari. I just started learning COMFYUI. I saw your PS-COMFYUI workflow and I think it is very good. However, I have installed it from 1.4 to 1.6.5 and followed your deployment process. However, it always gets stuck at the sampler. I don't know why. Only the sinple fast upscale can run. Others are stuck at the sampler. Hope you can help me. Thank you.
![360截图20240719005828266](https://github.com/user-attachments/assets/e3b58999-9023-4422-94a7-e0bdb857b8c4)

**Comment by NimaNzrii** [comment]
Hi , make sure that only one green group is enable at the time , you can check it by checking the "⚙️" node

**Comment by NimaNzrii** [comment]
And it seems you are using a translator node for your comfyui

Translators will currept the workflows , specially workflows which are using "Anything Everywhere" node

If its possible please delete the translator node

**Comment by NimaNzrii** [comment]
Could you please tell me which translator node are you using?

**Comment by jisdf** [comment]
你把你的界面语言切换回英文就可以了

**Comment by jisdf** [comment]
然后它的全局输入就可以识别到你缺失掉的那些连接

**Comment by 907590629** [comment]
> 然后它的全局输入就可以识别到你缺失掉的那些连接

兄弟 能加个微信吗 交流交流  haike931

**Comment by 907590629** [comment]
兄弟 能加个微信吗 交流交流 haike931

**Comment by langrenlaile** [comment]
Thank you NimaNzrii and everyone. It is indeed a translation problem. I switched back to the English interface and it was OK. It took me a few days. Thank you again.
谢谢NimaNzrii和大家，确实是翻译的问题，切换回英文界面，直接OK，搞了还几天，再次谢谢。

**Comment by jisdf** [comment]
@langrenlaile :)

**Comment by jisdf** [comment]
@907590629 好呀好呀，交流交流
