### ISSUE TITLE
Ps licence popup?

### ISSUE THREAD

**Issue by loztm** [NimaNzrii/comfyui-photoshop#157]
Is it possible to use the plugin and comfyUI, etc with a Photoshop not connected to the Internet? I had to do the trick with the licence popup, and now I don't know if this will work.

**Comment by NimaNzrii** [comment]
It's possible , you don't need internet for it

For installation you can right click on the node and press install ! It will install it offline 

But i highly recommend you to block Photoshops internet in the firewall, you can use https://m.majorgeeks.com/files/details/firewall_app_blocker_(fab).html

**Comment by loztm** [comment]
Sorry, what node? which from all of the nodes?
When I go to settings, it's showing not connected, in the comfyUI ip address. but the address is correct :(

**Comment by NimaNzrii** [comment]
> Sorry, what node? which from all of the nodes? When I go to settings, it's showing not connected, in the comfyUI ip address. but the address is correct :(

![image](https://github.com/user-attachments/assets/908eb4f2-a6ad-4f01-a45a-518b9afa0552)
