### ISSUE TITLE
can not utilize

### ISSUE THREAD

**Issue by hedonggame** [NimaNzrii/comfyui-photoshop#163]
![屏幕截图 2024-07-21 144843](https://github.com/user-attachments/assets/2b940200-4132-4b82-84ed-21de98b55d40)
can not utilize，thank you

**Comment by canyca** [comment]
我也出现这个问题

**Comment by canyca** [comment]
从这里点选不了，但是从工作流中可以去设置

**Comment by MinGoo666** [comment]
1.6和1.65版本无法选择这里了

**Comment by AJbeckliy** [comment]
I have the same problem. Can it be solved now?

**Comment by jisdf** [comment]
Everything works fine for me.

**Comment by wwb1988217** [comment]
我也遇到了这个问题，顺便问一下，大家知道如何把PS里的蒙版信息导出comfyui吗？

**Comment by NimaNzrii** [comment]
Please let me know if you are using the translator node in ComfyUi.

如果您正在使用 ComfyUi 中的翻译器节点，请告诉我 

如果您在 ComfyUi 中使用翻譯器節點，請告訴我

**Comment by AJbeckliy** [comment]
> Please let me know if you are using the translator node in ComfyUi.如果您正在使用 ComfyUi 中的翻译器节点，请告诉我。
> 
> 如果您正在使用 ComfyUi 中的翻译器节点，请告诉我
> 
> 如果您在 ComfyUi 中使用翻譯器節點，請告訴我如果您在 ComfyUi 中使用翻译器节点，请告诉我

Yes, I'm using translation node, 
node project address: https://github.com/AIGODLIKE/AIGODLIKE-ComfyUI-Translation
Is there any way to solve the above problem?
But I suspect it's not the translation node, because I used PS203 and can recognize the grouping options. Unfortunately, version 2023 does not pass the resulting image into Photoshop.
Do you have a Photoshop version that you recommend?

**Comment by NimaNzrii** [comment]
I talked to their devs a lot's of time, but they are not answering me correctly 

Please add an issue for tgem on the link below:
https://github.com/AIGODLIKE/AIGODLIKE-ComfyUI-Translation/issues

**Comment by jisdf** [comment]
我不太明白你的意思，从ps里导出蒙版的意图是什么？

________________________________
发件人: Angelbonny ***@***.***>
发送时间: 2024年7月23日 13:10
收件人: NimaNzrii/comfyui-photoshop ***@***.***>
抄送: jisdf ***@***.***>; Comment ***@***.***>
主题: Re: [NimaNzrii/comfyui-photoshop] can not utilize (Issue #163)


我也遇到了这个问题，顺便问一下，大家知道如何把PS里的蒙版信息导出comfyui吗？

―

**Comment by NimaNzrii** [comment]
## Language Support added✨
update the node and reload the sd1.5 workflow

![Untitled-1](https://github.com/user-attachments/assets/2c069975-0f39-4c6a-a87a-116b9bd58f82)
