### ISSUE TITLE
Photoshop canvas edits not updating plugin

### ISSUE THREAD

**Issue by mccabedd** [NimaNzrii/comfyui-photoshop#168]
I have a new weird problem. As you can see in the attached video, when I create or edit an image in the Photoshop canvas, it is not reflected in the plugin. The edited image updates in the workflow, but not the output.

If I add a positive, again, it seems to completely ignore the image on the Photoshop canvas.

Plugin and workflows are the latest versions (v1.6.5)

I also changed the checkpoint to a Pixar one as the default epicrealism one generated 'questionable' images.

https://github.com/user-attachments/assets/28c5d075-b9a2-4b1d-8ea3-30a2c61981c3

**Comment by artemistang13** [comment]
遇到了同样的问题

> 我遇到了一个新的奇怪问题。正如您在所附视频中看到的，当我在 Photoshop 画布中创建或编辑图像时，它不会反映在插件中。编辑后的图像会在工作流程中更新，但不会更新输出。
> 
> 如果我再次添加正片，它似乎完全忽略了 Photoshop 画布上的图像。
> 
> 插件和工作流程是最新版本（v1.6.5）
> 
> 我还将检查点改为皮克斯的检查点，因为默认的史诗现实主义检查点生成了“可疑”图像。
> 
>  视频_2024-07-23_120247.mp4

遇到了同样的问题

**Comment by NimaNzrii** [comment]
Right click on the ksampler and convert the denoise to input 
Then simply connect `slider` from Photoshop node to ksampler `denoise`

**Comment by artemistang13** [comment]
> 右键单击 ksampler 并将降噪转换为输入然后只需从 Photoshop 节点 连接到 ksampler`slider``denoise`

<img width="1064" alt="image" src="https://github.com/user-attachments/assets/bbcaf9d6-566e-46b2-8f45-915402b7fbce">
<img width="1272" alt="image" src="https://github.com/user-attachments/assets/31afc2f9-600e-410c-bb7c-2f86f48e264c">
No, still.

**Comment by mccabedd** [comment]
Thanks. Converting the denoise widget to input, then connecting the slider from Photoshop node to ksampler denoise worked.
