### ISSUE TITLE
When images are imported from ComfyUI to Photoshop, they automatically adapt to the current canvas and stretch, without maintaining the aspect ratio.

### ISSUE THREAD

**Issue by mmmmmmmmm5** [NimaNzrii/comfyui-photoshop#172]
Here is the translation of your statement into English:

"When images are imported from ComfyUI to Photoshop, they adapt to the current canvas by stretching, without maintaining the aspect ratio.

For example, after I import an image from Photoshop to ComfyUI, if the generated image size is larger or smaller than the imported size, it will automatically stretch the canvas when exported back to Photoshop, without maintaining the aspect ratio. This has caused me a lot of trouble, as I have to manually adjust the alignment using free transform each time.

I hope the developer can update the feature to maintain the aspect ratio of the generated image after import. Thank you very much."

**Comment by mmmmmmmmm5** [comment]
Here is the translation of your statement into English:

"The images I usually work with are of various non-standard sizes, which depend on the selection area in Photoshop. These sizes often cannot be divided evenly by 16, so when they are imported into the sampler, some pixels are cropped, resulting in a size difference of a few to several dozen pixels between the generated image and the original. After exporting, these pixels are stretched to the size of the original image, causing a noticeable misalignment. I have tried using cropping nodes and other methods, but the automatic stretching after export has not yielded satisfactory results."

This translation conveys the technical details and issues you are facing with the software, and it should be clear to someone familiar with graphic design and image processing.

**Comment by randykoala** [comment]
They are imported as smart objects. Double click on the thumbnail in the layers menu and it opens as full resolution

**Comment by charli117** [comment]
I made a fix in this pr #185

**Comment by NimaNzrii** [comment]
## Language Support added✨
update the node and reload the sd1.5 workflow

![Untitled-1](https://github.com/user-attachments/assets/2c069975-0f39-4c6a-a87a-116b9bd58f82)
