### ISSUE TITLE
Ksampler Nodes disconnected

### ISSUE THREAD

**Issue by Xiahussheng** [NimaNzrii/comfyui-photoshop#174]
How should I solve this problem? Should I manually connect these nodes?
<img width="860" alt="PixPin_2024-07-26_17-45-28" src="https://github.com/user-attachments/assets/ff5f1a5c-651b-475c-bc1d-cc704dcaa7df">

**Comment by NimaNzrii** [comment]
Please dont use the translator node! It's changing the whole worlflow input names

Or please make an issues page on https://github.com/AIGODLIKE/AIGODLIKE-ComfyUI-Translation/issues

He has to fix the translator bug with anything Everywhere nodes!

**Comment by Xiahussheng** [comment]
Nailed it，thx a lot

**Comment by qyyxm99** [comment]
老哥，我卸载了这个translator再次放入json到comfyui中，还是出现无连线的情况，请问你是怎么解决的？谢谢回答

**Comment by NimaNzrii** [comment]
## Language Support added✨
update the node and reload the sd1.5 workflow

![Untitled-1](https://github.com/user-attachments/assets/2c069975-0f39-4c6a-a87a-116b9bd58f82)
