### ISSUE TITLE
Please allow custom ports, this is very important, I have several comfyui, I need to customize different ports to suit different needs.Therefore, it is hoped that this plug-in can be more custom ports, rather than fixed 8188

### ISSUE THREAD

**Issue by kenic123** [NimaNzrii/comfyui-photoshop#175]
Please allow custom ports, this is very important, I have several comfyui, I need to customize different ports to suit different needs.Therefore, it is hoped that this plug-in can be more custom ports, rather than fixed 8188。I'm sure many people use different ports。

**Comment by NimaNzrii** [comment]
done!

check the latest update
