### ISSUE TITLE
Only img to img is working

### ISSUE THREAD

**Issue by therysin** [NimaNzrii/comfyui-photoshop#177]
After your last updates, everything is completely broken. Selecting the different methods such as inpainting etc seems to not work properly anymore, the nodes in the latest workflow seem to stay deactivated for every method except img to img. 

This was a great plugin for me before these updates. Also whenever you have an update, it never seems to be able to update directly from comfyui manager, there's always issues.

EDIT: After multiple reloads and restarts of comfyui and photoshop, things seem to be working.

**Comment by NimaNzrii** [comment]
You can still use the old workflow 
Tell me if it worked for you
