### ISSUE TITLE
I am experiencing connection issues between Photoshop (PS) and COMFYUI. Additionally, is there a way to prevent images from being sent at a low default resolution?

### ISSUE THREAD

**Issue by KKGGGG** [NimaNzrii/comfyui-photoshop#178]
Firstly, thank you to the author for providing the plugin. Currently, I'm encountering connection issues between Photoshop (PS) and COMFYUI. I've looked at some other questions and answers and found that the issue might be due to a translation plugin, but even after disabling it, the problem persists. However, the most pressing issue is that the image resolution is being compressed too much when sending from PS to COMFYUI. I've tried adjusting the values, but they don't seem to have any effect. This means that the plugin is effectively unusable until the connection issue is resolved.

Would it be possible for the author to consider changing the default send resolution to match the current canvas or rectangular selection resolution in PS? This would at least make the plugin usable while we work on resolving the connection issues.
![微信截图_20240728081617](https://github.com/user-attachments/assets/fbc5d2f9-6d14-4c85-a808-cfde795add7f)
![微信截图_20240728081502](https://github.com/user-attachments/assets/e787bc76-822f-4be1-a84e-d6ca91f29907)
![微信截图_20240728081426](https://github.com/user-attachments/assets/199a97af-6d6b-4699-8bfc-2d8934012b28)

**Comment by KKGGGG** [comment]
@NimaNzrii

**Comment by KKGGGG** [comment]
Or, could the author provide some temporary solutions to address this resolution issue? I tried looking into the code to adjust the file transmission values, but was unsuccessful.

**Comment by NimaNzrii** [comment]
## Language Support added✨
update the node and reload the sd1.5 workflow

![Untitled-1](https://github.com/user-attachments/assets/2c069975-0f39-4c6a-a87a-116b9bd58f82)
