### ISSUE TITLE
能否支持自定义模型

### ISSUE THREAD

**Issue by lzhfdwu007** [NimaNzrii/comfyui-photoshop#18]
我看有指定特定的模型，是否支持使用者使用本机已经存在的其他模型？

**Comment by NimaNzrii** [comment]
I couldn't really understand

**Comment by lzhfdwu007** [comment]
After introducing the two nodes “photoshop remete conection” and “sendto photoshop plugin”, the following error message is obtained
Error occurred when executing 🔹Photoshop ComfyUI Plugin:

Failed to load directory after 5 attempts.
🔴 Make sure you have installed and started the Photoshop Plugin Succesfully.
🔴 otherwise you can restart your photosop and your plugin to Fix this problem

File "D:\ComfyUI\ComfyUI\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\ComfyUI\ComfyUI\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\ComfyUI\ComfyUI\execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\ComfyUI\ComfyUI\custom_nodes\comfyui-photoshop\node-Photoshop.py", line 31, in PS_Execute
self.loadConfig()
File "D:\ComfyUI\ComfyUI\custom_nodes\comfyui-photoshop\node-Photoshop.py", line 73, in loadConfig
self.loadConfig(retry_count + 1)
File "D:\ComfyUI\ComfyUI\custom_nodes\comfyui-photoshop\node-Photoshop.py", line 73, in loadConfig
self.loadConfig(retry_count + 1)
File "D:\ComfyUI\ComfyUI\custom_nodes\comfyui-photoshop\node-Photoshop.py", line 73, in loadConfig
self.loadConfig(retry_count + 1)
[Previous line repeated 1 more time]
File "D:\ComfyUI\ComfyUI\custom_nodes\comfyui-photoshop\node-Photoshop.py", line 75, in loadConfig
raise Exception("Failed to load directory after 5 attempts. \n 🔴 Make sure you have installed and started the Photoshop Plugin Succesfully. \n 🔴 otherwise you can restart your photosop and your plugin to Fix this problem")

**Comment by lzhfdwu007** [comment]
I saw that the “photoshop remete conection” node has “server” and “port” settings, but I didn't see these two options in your youtube video. How should I set them? Could you tell me?

**Comment by NimaNzrii** [comment]
did you tried update comfyui node?
because this problem fixed for many users after last update

**Comment by lzhfdwu007** [comment]
> did you tried update comfyui node? because this problem fixed for many users after last update

I have upgraded the entire node using the GIT PULL command, but the problem still exists

**Comment by NimaNzrii** [comment]
Please use the comfyui manager and use try fix abd try update instead

**Comment by lzhfdwu007** [comment]
> Please use the comfyui manager and use try fix abd try update instead

I tried this and got worse results
The node failed to load directly. The error code of the entire startup process is as follows:
[The error code of the entire startup process.txt](https://github.com/NimaNzrii/comfyui-photoshop/files/15276571/The.error.code.of.the.entire.startup.process.txt)
![屏幕截图 2024-05-10 230944](https://github.com/NimaNzrii/comfyui-photoshop/assets/144492780/67d83b5b-51d4-4e29-8a10-176aa2237aba)
