### ISSUE TITLE
can't use preset 

### ISSUE THREAD

**Issue by Woo-ya** [NimaNzrii/comfyui-photoshop#182]
I can't use preset ,this tell me "couldn't load"
![Snipaste_2024-07-30_11-33-11](https://github.com/user-attachments/assets/7d3a2105-f708-4b64-aaba-4c9e30de029c)

**Comment by Xiahussheng** [comment]
refresh  your comfyui page

**Comment by yhf1407** [comment]
The same problem, which was used well yesterday, can not be used today, can not be solved by refreshing, and can not be solved by reloading

**Comment by yhf1407** [comment]
Now that you've found the reason, you can just roll back the version to July 21st

**Comment by NimaNzrii** [comment]
fixed in latest version guys
