### ISSUE TITLE
# PS: PS not connected"

### ISSUE THREAD

**Issue by pcarpenter-comfy** [NimaNzrii/comfyui-photoshop#183]
Running comyfui on M2 mac and experiencing "# PS: PS not connected" error plugin loaded. all models and required files added and updated also tried above fix by mccabedd in issue [https://github.com/NimaNzrii/comfyui-photoshop/issues/150](url) . still not working
on the photoshop side 
![Screenshot 2024-07-30 at 5 05 09 PM](https://github.com/user-attachments/assets/a07803a5-d57d-4197-978b-5a0494ed2d23)

and on the comfyui side
![Screenshot 2024-07-30 at 5 06 24 PM](https://github.com/user-attachments/assets/a260e6b7-a973-4d89-8fe3-78732ab5162d)

.. any help would be awesome excited to try this plugin

**Comment by loztm** [comment]
same here, I don't know what to do

**Comment by HanZeCoder** [comment]
Facing the same issue here, have tried fixing multiple times. Does anyone have a solve? Some help would be great :)
![Screenshot 2024-07-31 143451](https://github.com/user-attachments/assets/e1b5ac1c-d1d8-4bc9-ae66-273d09125ff8)

**Comment by KPY7030P** [comment]
I have a similar problem in windows, if there is a solution to this, please mark me
![image](https://github.com/user-attachments/assets/2df4249f-bdd8-4e9e-b793-864d54855979)

**Comment by NimaNzrii** [comment]
Guys

Try right clicking on the node and press "🔹 install plugin ..."

**Comment by pcarpenter-comfy** [comment]
just tried   still no luck

Method 1: installed in /Users/xxxxx/Library/Application Support/Adobe/UXP/Plugins/External
Error checking admin status: module 'ctypes' has no attribute 'windll'
Requesting admin privileges...
Failed to request admin privileges: module 'ctypes' has no attribute 'windll'
[Impact Pack] Wildcards loading done

**Comment by chentaopisces** [comment]
me too，I used  it ，but today I cant collect COMFYUI ,tell me reson,

**Comment by fancsiko** [comment]
same problem here on an m3 mac. right click and installing from comfyui results in permission error in terminal

**Comment by NimaNzrii** [comment]
## Language Support added✨
update the node and reload the sd1.5 workflow

![Untitled-1](https://github.com/user-attachments/assets/2c069975-0f39-4c6a-a87a-116b9bd58f82)
