### ISSUE TITLE
I uninstalled the translator, but the KSampler connection is still down

### ISSUE THREAD

**Issue by qyyxm99** [NimaNzrii/comfyui-photoshop#186]
I updated the latest 1.6.5, and put the.json file into comfyui, but the ksampler connection is still not

**Comment by qyyxm99** [comment]
![微信截图_20240801114802](https://github.com/user-attachments/assets/53abc57c-1abb-4d73-b870-413b7a3a618d)

**Comment by NimaNzrii** [comment]
in the image you sent everything looks fine

**Comment by bubbl000** [comment]
https://github.com/NimaNzrii/comfyui-photoshop/issues/220#issue-2492698790 解决方式，你忘记修改全局链接里面的文本了

**Comment by NimaNzrii** [comment]
## Language Support added✨
update the node and reload the sd1.5 workflow

![Untitled-1](https://github.com/user-attachments/assets/2c069975-0f39-4c6a-a87a-116b9bd58f82)
