### ISSUE TITLE
Couldn't load

### ISSUE THREAD

**Issue by TerryWen2023** [NimaNzrii/comfyui-photoshop#193]
PS can't load the process switch, you have to switch it manually

**Comment by NimaNzrii** [comment]
try tight clicking on the node and press 🔹 install photoshop plugin ...
![image](https://github.com/user-attachments/assets/676e5e21-0777-4879-93c9-105bf88ce40c)

**Comment by zzinggame** [comment]
I also having this problem, it seem the problem happened with any Photoshop version that using Simplified Chinese
If i use English Photoshop everything fine, but with Simplified Chinese after couple days using this problem happen

**Comment by bubbl000** [comment]
> I also having this problem, it seem the problem happened with any Photoshop version that using other language pack我也遇到这个问题，似乎任何使用其他语言包的 Photoshop 版本都会出现此问题 If i use English Photoshop everything fine, but with Simplified Chinese after couple days using this problem happen如果我使用英文版 Photoshop 一切正常，但使用简体中文版几天后就会出现此问题
https://github.com/NimaNzrii/comfyui-photoshop/issues/220#issue-2492698790  解决方式

**Comment by NimaNzrii** [comment]
## Language Support added✨
update the node and reload the sd1.5 workflow

![Untitled-1](https://github.com/user-attachments/assets/2c069975-0f39-4c6a-a87a-116b9bd58f82)
