### ISSUE TITLE
When the ComfyUI interface is in Chinese (not in English), KSampler encounters an error. It works fine after switching to English.

### ISSUE THREAD

**Issue by anxin0828** [NimaNzrii/comfyui-photoshop#195]
![2024-08-08_23-44-39](https://github.com/user-attachments/assets/8f751174-d027-49be-baf0-8ec33af58bab)
Thank you for providing such an excellent workflow.

There is a minor issue: when the ComfyUI interface is set to Chinese (not in English), KSampler encounters an error. It works normally after switching to English.

The issue seems to be related to the parameters: steps, cfg, sampler, and scheduler. It might be an "anything everywhere" problem, but I'm not sure how to fix it.

**Comment by NimaNzrii** [comment]
this problem is coming from the translator node,

please add a request to the translator node to fix it
or disable chinese lang

**Comment by bubbl000** [comment]
https://github.com/NimaNzrii/comfyui-photoshop/issues/220#issue-2492698790 Solution

**Comment by NimaNzrii** [comment]
## Language Support added✨
update the node and reload the sd1.5 workflow

![Untitled-1](https://github.com/user-attachments/assets/2c069975-0f39-4c6a-a87a-116b9bd58f82)
