### ISSUE TITLE
UnicodeEncodeError: 'cp932' codec can't encode character '\U0001f537' in position 0: illegal multibyte sequence

### ISSUE THREAD

**Issue by za-wa-n-go** [NimaNzrii/comfyui-photoshop#20]
In the case of a Japanese environment in StabilityMatrix/Windows, an error occurs in the subject line and it cannot be used normally.
It would be helpful if you could add the following code to the beginning of the backend script or remove the emojis.

```
import sys
import io
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')
```

**Comment by NimaNzrii** [comment]
Oh thank you for your call
I will do it soon
Did you test your command line?

**Comment by NimaNzrii** [comment]
done
