### ISSUE TITLE
When using on a local area network, prompt: Remote computer refuses network connection

### ISSUE THREAD

**Issue by fanz2286** [NimaNzrii/comfyui-photoshop#200]
May I ask the author, what is the reason for this issue? Thank you for your response

_PS_ error on send2Ps: Cannot connect to host 127.0.0.1:8188 ssl: default [Remote computer rejects network connection.]

I deployed Comfyui on 192.168.3.57, installed Photoshop on MacBook on the local area network, and successfully connected the plugin

**Comment by NimaNzrii** [comment]
check my latest yt video:
[![image](https://github.com/user-attachments/assets/8c8cc2c4-8904-4dfd-b7c7-da9bb9322a01)](https://www.youtube.com/watch?v=9wGixLsRH-I)
