### ISSUE TITLE
（中国玩家）comfyui与Photoshop无法桥接的解决办法之一

### ISSUE THREAD

**Issue by lstzys** [NimaNzrii/comfyui-photoshop#207]
大家好，我来说我是怎么解决，comfyui_Photoshop节点插件与Photoshop2024是如何打通桥接的：
1.安装[ZXP UXP Installer] ：Photoshop的插件安装管理器；
2.安装Creative Cloud：Adobe的管理软件，安装它才能有权限更改adobe系列软件，如果你跳过安装Creative Cloud，可能导致桥接插件安装不到Photoshop的Plug-ins目录，（同下面的第3条，如果你阻止了Creative Cloud联网，会导致Creative Cloud一直卡在：正在初始化Creative Cloud...开了科学上网也没用）；
3.检测电脑是否有软件阻止了Creative Cloud和Photoshop的联网请求，包括hosts.txt文件（最重要的一步！！！！！！）：我发现正是因为第三方软件阻止网络请求才导致了comfyui_Photoshop与Photoshop_2024的桥接不成功；中国玩家常用的有火绒软件的流量监控，还有研几CG系统的冰盾·主动防御系统，更改完规则之后，就能桥接成功了；
![PixPin_2024-08-17_20-13-06](https://github.com/user-attachments/assets/b5a65761-281e-4c87-be6b-4ac7a02dc987)
![PixPin_2024-08-17_20-13-38](https://github.com/user-attachments/assets/d8f1c2e3-4e75-46ad-b7bf-25408e01e839)
![PixPin_2024-08-17_20-13-57](https://github.com/user-attachments/assets/e8e034c4-821b-446a-a1e2-24680f87b335)
4.更改规则完毕后，启动comfyui和Photoshop，Photoshop中的未连接就可变为已连接：
![PixPin_2024-08-17_20-17-45](https://github.com/user-attachments/assets/39db2f6d-6d68-47ab-9a62-1e9535b42fb8)
![PixPin_2024-08-17_20-18-50](https://github.com/user-attachments/assets/693bd351-6502-4135-84ae-8e522e7b3230)
5.感谢你的观看！

**Comment by MinGoo666** [comment]
这样安装还是过于繁琐，直接复制comfyui-Photoshop插件文件夹中的“3e6d64e0”文件夹到到Photoshop的Plug-ins目录即可，或者修改“3e6d64e0_PS.ccx”文件后缀为zip后解压，复制到”Photoshop的Plug-ins目录也可以，亲测有效。

**Comment by huacuoni** [comment]
有汉化包吗？

**Comment by lstzys** [comment]
> 这样安装还是过于繁琐，直接复制comfyui-Photoshop插件文件夹中的“3e6d64e0”文件夹到到Photoshop的Plug-ins目录即可，或者修改“3e6d64e0_PS.ccx”文件后缀为zip后解压，复制到”Photoshop的Plug-ins目录也可以，亲测有效。

我前面也是这样做的，但是我的Photoshop2024是俄罗斯m0nkrus‘a大神的版本，估计被砍了一些东西，导致不安装Creative Cloud就不能获取完整的权限，又不想找其他版本，只能用点笨办法了

**Comment by lstzys** [comment]
> 引用回复

没有，功能太过于简单了，完全没有汉化的必要

**Comment by MinGoo666** [comment]
> > 这样安装还是太过繁琐，直接复制comfyui-Photoshop插件文件夹中的“3e6d64e0”文件夹到Photoshop的Plug-ins目录即可，或者修改“3e6d64e0_PS.ccx”文件后缀为zip后解压，复制到“Photoshop”的插件目录也可以，亲测有效。
> 
> 我前面也是这样做的，但是我的Photoshop2024是俄罗斯m0nkrus的一个大神的版本，估计被砍掉了一些东西，导致不安装Creative Cloud就无法获取完整的权限，又不想找到其他版本，只能用点笨办法了

我用的也是这个PS版本，那么也可以把“3e6d64e0_PS.ccx”文件后缀为zip后解压，复制到“Photoshop”的插件目录，你可以试试

**Comment by MinGoo666** [comment]
> 有汉化包吗？

1.65版本前我自己汉化了，现在的版本我也不知道怎么汉化了，作者重写了代码，不过功能面板也比较简单，确实没有汉化必要了，实在看不懂可以用微信截图翻译一下，大概就知道啥意思了

**Comment by lstzys** [comment]
> > > 这样安装还是太过繁琐，直接复制comfyui-Photoshop插件文件夹中的“3e6d64e0”文件夹到Photoshop的Plug-ins目录即可，或者修改“3e6d64e0_PS.ccx”文件后缀为zip后解压，复制到“Photoshop”的插件目录也可以，亲测有效。
> > 
> > 
> > 我前面也是这样做的，但是我的Photoshop2024是俄罗斯m0nkrus的一个大神的版本，估计被砍掉了一些东西，导致不安装Creative Cloud就无法获取完整的权限，又不想找到其他版本，只能用点笨办法了
> 
> 我用的也是这个PS版本，那么也可以把“3e6d64e0_PS.ccx”文件后缀为zip后解压，复制到“Photoshop”的插件目录，你可以试试

我的问题解决了啊...不用使了，哈哈哈哈哈

**Comment by huacuoni** [comment]
1.4版本在中文设置下，还能加载工作流，1.6之后就要切换到英文才能够加载，现在升级到1.8.2，即使我切换到英文，我的自己加入的工作流就无法加载...有这种情况的吗？

**Comment by NimaNzrii** [comment]
## Language Support added✨
update the node and reload the sd1.5 workflow

![Untitled-1](https://github.com/user-attachments/assets/2c069975-0f39-4c6a-a87a-116b9bd58f82)

**Comment by azuma520** [comment]
> 这样安装还是过于繁琐，直接复制comfyui-Photoshop插件文件夹中的“3e6d64e0”文件夹到到Photoshop的Plug-ins目录即可，或者修改“3e6d64e0_PS.ccx”文件后缀为zip后解压，复制到”Photoshop的Plug-ins目录也可以，亲测有效。

兄弟，你是我的神
