### ISSUE TITLE
Cant connect to Photoshop

### ISSUE THREAD

**Issue by ortizgab** [NimaNzrii/comfyui-photoshop#208]
Hi
I have the plugin installed in Photoshop and the ip is set but it wont connect.
What Im I missing?
Thanx

**Comment by NimaNzrii** [comment]
are you sure that both workflow and photoshop are v1.9.0?

**Comment by ortizgab** [comment]
I updated everything and its working.
Thanx for the follow up



GABRIEL ORTIZ
CEO at GO Studio
Soluciones Web-Audiovisuales
Of (809) 287-7606
Cel (829) 548-7337
www.gabrielortiz.net
