### ISSUE TITLE
Photoshop cannot load presets

### ISSUE THREAD

**Issue by zh2650307** [NimaNzrii/comfyui-photoshop#209]
The plugin is working normally, but the preset keeps failing to load. There is a bug in the plugin, and we hope it can be resolved as soon as possible. Thank you
![QQ截图20240821231743](https://github.com/user-attachments/assets/2b3541b0-abaa-42ad-9f18-1cc90e7e7e76)
![QQ截图20240821231816](https://github.com/user-attachments/assets/2079cab8-542c-4945-bbd5-63621ec26f95)

**Comment by zh2650307** [comment]
1. **Use the English version instead of the translation interface, the nodes will load normally**
2. 
![QQ截图20240822081551](https://github.com/user-attachments/assets/1cf4994a-df8c-4d19-b12d-cb8721919e1f)

**Comment by zh2650307** [comment]
Chinese Compatibility - Solution:
Delete translation plugin: AIGODLIKE-CompfyUI Translation \ zh CN \ zh CN \ Nodes directory all files
![2](https://github.com/user-attachments/assets/4ccae202-882d-4eb1-93d7-bd7224d92658)
![3](https://github.com/user-attachments/assets/25475e31-eaeb-414a-8fe6-b178d9b06207)
![4](https://github.com/user-attachments/assets/35a2ce66-95cb-4ff9-a9fe-fc4f89a01338)

**Comment by zh2650307** [comment]
![Uploading QQ图片20240822165129.png…]()

**Comment by zh2650307** [comment]
**### Perfect compatibility**
![1](https://github.com/user-attachments/assets/4cca99dd-30f4-480a-b832-5268a4ffa5ca)

**Comment by guangxinzhao** [comment]
从哪里下载的1.82呀，我下载的全是1.81，工作流还是1.54，
<img width="282" alt="iShot_2024-08-23_11 59 50" src="https://github.com/user-attachments/assets/155acfae-e7d7-4940-8d1f-8ebbff704d36">

**Comment by huanli11** [comment]
> **### 完美的兼容性** ![1](https://private-user-images.githubusercontent.com/31351031/360358049-4cca99dd-30f4-480a-b832-5268a4ffa5ca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0MjA0MTIsIm5iZiI6MTcyNDQyMDExMiwicGF0aCI6Ii8zMTM1MTAzMS8zNjAzNTgwNDktNGNjYTk5ZGQtMzBmNC00ODBhLWI4MzItNTI2OGE0ZmZhNWNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIzVDEzMzUxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3NWYxOGFkNDRhNTE0MzViYmY1MjFmODFiOWM5MjJjNGZjMjA5MzgyM2FmNWEzYzAyNjYzMTRmMTMwZWIyNWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oqNYe4L6dmAlqkHiILgw272zsKvlEd7E47kPMTXjUQE)

我为什么找不到 v1.8.2    安装几次都是1.8.1   而且 你插件怎么是中文 的

**Comment by yuewusha** [comment]
一样的问题，无法解决

**Comment by zh2650307** [comment]
> 一样的问题，无法解决

我已经提供解决方案：https://github.com/NimaNzrii/comfyui-photoshop/issues/214

**Comment by zh2650307** [comment]
> > **### 完美的兼容性** ![1](https://private-user-images.githubusercontent.com/31351031/360358049-4cca99dd-30f4-480a-b832-5268a4ffa5ca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0MjA0MTIsIm5iZiI6MTcyNDQyMDExMiwicGF0aCI6Ii8zMTM1MTAzMS8zNjAzNTgwNDktNGNjYTk5ZGQtMzBmNC00ODBhLWI4MzItNTI2OGE0ZmZhNWNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIzVDEzMzUxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3NWYxOGFkNDRhNTE0MzViYmY1MjFmODFiOWM5MjJjNGZjMjA5MzgyM2FmNWEzYzAyNjYzMTRmMTMwZWIyNWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oqNYe4L6dmAlqkHiILgw272zsKvlEd7E47kPMTXjUQE)
> 
> 我为什么找不到 v1.8.2 安装几次都是1.8.1 而且 你插件怎么是中文 的

我已经提供解决方案：https://github.com/NimaNzrii/comfyui-photoshop/issues/214

**Comment by NimaNzrii** [comment]
## Language Support added✨
update the node and reload the sd1.5 workflow

![Untitled-1](https://github.com/user-attachments/assets/2c069975-0f39-4c6a-a87a-116b9bd58f82)

**Comment by zh2650307** [comment]
How can I contact you? I want to develop this plugin together
