### ISSUE TITLE
plugin not working

### ISSUE THREAD

**Issue by Darshd994** [NimaNzrii/comfyui-photoshop#21]
Error occurred when executing 🔹Photoshop ComfyUI Plugin:

Failed to load directory after 5 attempts.
🔴 Make sure you have installed and started the Photoshop Plugin Succesfully.
🔴 otherwise you can restart your photosop and your plugin to Fix this problem this is the error m getting

**Comment by NimaNzrii** [comment]
Hi please first load the plugin in your photoshop and pres get started, and then try it again❤️

And please tell me which os are you using

Are you using portable version of comfyui?

**Comment by Darshd994** [comment]
Yes i am using portable version of comfyui
![Screenshot 2024-05-10 122521](https://github.com/NimaNzrii/comfyui-photoshop/assets/120714933/5bce3d53-6e5e-4b75-94f0-c1cd3239ff70)

**Comment by NimaNzrii** [comment]
Did you installed Photoshop on your C drive?

**Comment by Darshd994** [comment]
Yes i did.

**Comment by Darshd994** [comment]
I think the photoshop and comfyui is not connected somehow. even after installing the plugin.
![Screenshot 2024-05-10 122847](https://github.com/NimaNzrii/comfyui-photoshop/assets/120714933/752920fa-0a43-4cc3-acb9-bf5a0e60cf3e)

**Comment by NimaNzrii** [comment]
is it possible for you to send your full comfy Ui log please?

**Comment by Darshd994** [comment]
!!! Exception during processing!!! Failed to load directory after 5 attempts.
 🔴 Make sure you have installed and started the Photoshop Plugin Succesfully.
 🔴 otherwise you can restart your photosop and your plugin to Fix this problem
Traceback (most recent call last):
  File "D:\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-photoshop\node-Photoshop.py", line 70, in loadConfig
    with open(self.configJson, "r") as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'config.json'



some config.json file is missing, i think that's the reason its not working.

**Comment by NimaNzrii** [comment]
for some reason Backend.py is not running in you device
i will put it on emergency and currently working on it

**Comment by NimaNzrii** [comment]
hey could you please update the comfyui node and test it again

then send me the new log of your comfyui
i have added too many log detail to fix it faster so please💖

**Comment by Darshd994** [comment]
Yes doing that right now.

**Comment by Darshd994** [comment]
[comfyui.log](https://github.com/NimaNzrii/comfyui-photoshop/files/15272197/comfyui.log)

**Comment by Darshd994** [comment]
[comfyui.log](https://github.com/NimaNzrii/comfyui-photoshop/files/15272366/comfyui.log)
another one! just for reference

**Comment by NimaNzrii** [comment]
did you restart the comfyui and run the workflow again before sending the log?

it seems there is no new log added
so maybe the node is not updated or maybe you didnt restart the comfui

please uninstall and install the node again

**Comment by Darshd994** [comment]
[comfyui.log](https://github.com/NimaNzrii/comfyui-photoshop/files/15272562/comfyui.log)
This is the latest one.

**Comment by Darshd994** [comment]
[comfyui.log](https://github.com/NimaNzrii/comfyui-photoshop/files/15272604/comfyui.log)
okay i see what you are saying now. yes i have restarted comfyui uninstalled and installed your custome node and tried the workflow again, getting the same error in it. this is that log file

**Comment by Darshd994** [comment]
[comfyui.log](https://github.com/NimaNzrii/comfyui-photoshop/files/15272681/comfyui.log)
Tried it multiple times still getting the error, this is the new log file.  m sorry if i'm not good at explaining things better. m not from the tech background.

**Comment by Darshd994** [comment]
Thanks for putting efforts in solving this.

**Comment by NimaNzrii** [comment]
i'm so sorry for all of your issues

changed too many things on the node 
i hope it helps you

1- Update or re-install the node 
2- re-launch your comfyui
3- i hope it works now


it may cause because of some network restriction or smt like this

on your latest log file 
i can see this error:
An error occurred while running a subprocess: Command '['comfyui-photoshop\\venv\\Scripts\\python.exe', '-m', 'pip', 'install', 'Pillow']' returned non-zero exit status 1.

**Comment by Darshd994** [comment]
![Screenshot 2024-05-10 153240](https://github.com/NimaNzrii/comfyui-photoshop/assets/120714933/1ba7c5ff-8c68-41cf-b540-9ab62cf86ec0)
![Screenshot 2024-05-10 153310](https://github.com/NimaNzrii/comfyui-photoshop/assets/120714933/4a1ec3ce-4cff-4938-9b27-c98bf715ce73)
i have custom node installed, still it shows that missing custom nodes. tried uninstalling from manager itself tried installing it from github directly also, still not working now it just says that nodes are missing, did all of the things you have suggested.

**Comment by NimaNzrii** [comment]
Can i have the log again

**Comment by Darshd994** [comment]
[comfyui.prev.log](https://github.com/NimaNzrii/comfyui-photoshop/files/15273551/comfyui.prev.log)

**Comment by NimaNzrii** [comment]
idk what to say. i changed something again
but im not sure if it fixes your problem

**Comment by barepixels** [comment]
Hello, tried to installed late last night and experience the same problem as [Darshd994](https://github.com/Darshd994)
When ever I restart Confyui  I get this
![ComfyUI](https://github.com/NimaNzrii/comfyui-photoshop/assets/92839033/8ed4b372-2eac-4cec-a552-fd8432d7e865)

**Comment by Ahcool123** [comment]
> 不知道该说什么。我再次更改了一些东西，但我不确定它是否解决了您的问题

非常感谢！我本来是出现了同样的代码错误。但经过一些操作变好了。

**Comment by Ahcool123** [comment]
> 不知道该说什么。我再次更改了一些东西，但我不确定它是否解决了您的问题

Thank you so much! I had the same code error. But after some manipulation, it got better. I share the solution: import the latest downloaded workflow file, and then switch to the English version (because after translation from other countries, the links in the global input will be cut off), so I can work normally.

**Comment by NimaNzrii** [comment]
what do you mean by switching to the English version 
the windows language?

**Comment by Darshd994** [comment]
tried that as well m only using english version. still not working, installed totally new portable comfyui but still not working.

**Comment by barepixels** [comment]
[Darshd994](https://github.com/Darshd994) look at your CMD widow,  did ComfyUI-Inference-Core-Nodes load?

**Comment by Darshd994** [comment]
File "D:\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Inference-Core-Nodes\__init__.py", line 1, in <module>
    from inference_core_nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
ModuleNotFoundError: No module named 'inference_core_nodes'

[2024-05-11 15:07] [Impact Pack] Wildcards loading done.[2024-05-11 15:07] Cannot import D:\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Inference-Core-Nodes module for custom nodes: No module named 'inference_core_nodes'


THis is the error for inference core nodes in the log and below is the screenshot in manager.

![Screenshot 2024-05-11 150925](https://github.com/NimaNzrii/comfyui-photoshop/assets/120714933/17c1c27d-51e3-4734-b31a-035c6468d960)

**Comment by Ahcool123** [comment]
> what do you mean by switching to the English version the windows language?

As a Chinese player, I am using the Chinese translation of ComfyUI. Consequently, the names of node links are also translated. However, the "Global Input" node in your workflow is in English. When I use the Chinese version of ComfyUI, these nodes do not automatically connect.

**Comment by Ahcool123** [comment]
> > what do you mean by switching to the English version the windows language?
> 
> As a Chinese player, I am using the Chinese translation of ComfyUI. Consequently, the names of node links are also translated. However, the "Global Input" node in your workflow is in English. When I use the Chinese version of ComfyUI, these nodes do not automatically connect.

These are indeed issues related to my usage of ComfyUI, and I don't want to take up your time with them. I have resolved them by redefining the names in the "Global Input Node" on my own. Thank you for providing such a great tool. I'm completely in love with it!

**Comment by bubbl000** [comment]
> what do you mean by switching to the English version切换到英文版是什么意思 the windows language? Windows 语言？

![image](https://github.com/NimaNzrii/comfyui-photoshop/assets/108770692/e46ec192-f86a-46f8-aaa2-94890d2b8245)
This, because of the translation node, the node text you preset is inconsistent with the translated node text, so it is equivalent to not connecting to the node

**Comment by NimaNzrii** [comment]
# Fixed ✨

Thank you for your report.💖
Please update the **Comfyui-Photoshop** node inside you **comfyui manager**

and let me know if you had any trouble on running it

@barepixels @bubbl000 @Darshd994 @Ahcool123

**Comment by barepixels** [comment]
I guess it is working now thank you
![Untitled-1](https://github.com/NimaNzrii/comfyui-photoshop/assets/92839033/aca80c18-0e75-42ef-9a1f-2c263469ea84)

But after I press  "render" in PS panel.  The interface switch language

![language](https://github.com/NimaNzrii/comfyui-photoshop/assets/92839033/f74b1966-3cc7-4bba-bfeb-9b3b1e6d32a2)

**Comment by NimaNzrii** [comment]
What a funny test😂😂 i've confused for a second

**Comment by Darshd994** [comment]
thank god
its working now, awesome...
