### ISSUE TITLE
The prompt word cannot be entered in Chinese

### ISSUE THREAD

**Issue by anlin857** [NimaNzrii/comfyui-photoshop#210]
The prompt word cannot be entered in Chinese. Switching input methods will pop up, and there was no problem with the previous version

**Comment by NimaNzrii** [comment]
oh i cant see any problem
![image](https://github.com/user-attachments/assets/31df14b4-9471-4e3e-9768-62a0e7557747)

it might be fixed in ver 1.9.0 which released today
