### ISSUE TITLE
New problem

### ISSUE THREAD

**Issue by huanli11** [NimaNzrii/comfyui-photoshop#211]
![Quicker_20240826_105311](https://github.com/user-attachments/assets/fab0dc56-9fc9-4445-8152-15277bb4f641)
It used to be unable to read ps pictures, yesterday was good, today updated, it is also unable to send ps,
以前是读取不到ps图片，昨天好好的，今天更新了下，就在也发送不到ps了,

**Comment by NimaNzrii** [comment]
Want to get more in touch wuth me to fix this problem sir? 
Dm me on discord and i will fix it fir you and whole community today!

Discord id : NimaNzrii

**Comment by huanli11** [comment]
v1.9.2 Perfect
