### ISSUE TITLE
after V1.5 to V1.6 can't connect 

### ISSUE THREAD

**Issue by shikochi** [NimaNzrii/comfyui-photoshop#213]
HI, I got a problem when update.
After I updated V1.5 to V1.6, the IP cant' connect.
I don't know what happen.
Or should i reInstall the V1.5 version?

**Comment by NimaNzrii** [comment]
Hi, why should we use v1.6 when you have v1.9.0

Please update the plugin and node

**Comment by shikochi** [comment]
sorry,the web app show that is V1.9.0 now
I thought it's 1.6 because the video on the right.
https://www.youtube.com/watch?v=i__ciRbs3VA

how can I update the plugin and node ? or I already updated?
( I updated in the web app before

**Comment by shikochi** [comment]
HI! I fixed it from this issue. I updated the PS node and it works!
https://github.com/NimaNzrii/comfyui-photoshop/issues/131

I'm sorry to bother you for so long. thank you very much!
