### ISSUE TITLE
I found an interesting issue that solves the problem of not being able to load workflows

### ISSUE THREAD

**Issue by bubbl000** [NimaNzrii/comfyui-photoshop#219]
![image](https://github.com/user-attachments/assets/1349d269-817e-41db-b3c8-5ba601b82f90)

This workflow is loaded in the English environment, so these two headings are like this, in this case, ps can load out the workflow

![image](https://github.com/user-attachments/assets/c01c2305-7612-4997-b455-470cc6b47169)

This is after I refreshed the page Translation plugin translates the title into English, in which case ps could not load the workflow
Similarly, in the Chinese environment, the translation plugin will translate into Chinese, in which case ps will not be able to load the workflow

So the inability to load the workflow should not be related to whether the translation plugin is installed or not, but the title works, but how can I prevent the translation plugin from translating it?

**Comment by bubbl000** [comment]
启动comfyui>打开ps并加载插件点击开始（此时没有加载出预设）>刷新comfyui页面>ps插件出现预设
Start comfyui>Open ps and load the plug-in and click start (no presets are loaded at this time)>Refresh the comfyui page>The preset appears for the ps plug-in
![image](https://github.com/user-attachments/assets/0b804b09-a239-41eb-8343-dfe5e1a3ecd8)
注意需要将翻译插件内   \custom_nodes\AIGODLIKE-ComfyUI-Translation\zh-CN\Nodes\rgthree-comfy.json
这段删除
Note that you need to put \custom_nodes\AIGODLIKE-ComfyUI-Translation\zh-CN\Nodes\rgthree-comfy.json in the translation plug-in
Delete this paragraph

**Comment by NimaNzrii** [comment]
no need to do it  anymore
now it will work even on default ver of tranlator node
