### ISSUE TITLE
Solutions for unable to load presets, unable to run, unable to bridge ps

### ISSUE THREAD

**Issue by bubbl000** [NimaNzrii/comfyui-photoshop#220]
![image](https://github.com/user-attachments/assets/69117977-07b9-4f1e-ac30-5ffd7e520a30)
This workflow is loaded in the English environment, so these two headings are like this, in this case, ps can load out the workflow
这个工作流程是在英文环境下加载的，所以这两个标题是这样的，这样的话，ps就可以加载出工作流程
![image](https://github.com/user-attachments/assets/07344383-ab1d-431d-9e8f-bf84370636d9)
This is after I refreshed the page Translation plugin translates the title into English, in which case ps could not load the workflow
这是我刷新页面后翻译插件将标题翻译成英文，在这种情况下 ps 无法加载工作流程
Similarly, in the Chinese environment, the translation plugin will translate into Chinese, in which case ps will not be able to load the workflow
同样，在中国环境中，翻译插件将翻译成中文，在这种情况下，ps 将无法加载工作流

解决方式Solution：

1、启动comfyui>打开ps并加载插件点击开始（此时没有加载出预设）>刷新comfyui页面>ps插件出现预设
Start comfyui>Open ps and load the plug-in and click start (no presets are loaded at this time)>Refresh the comfyui page>The preset appears for the ps plug-in
![image](https://github.com/user-attachments/assets/3e3bd769-3221-4737-add5-ad2adf61410c)

注意需要将翻译插件内   \custom_nodes\AIGODLIKE-ComfyUI-Translation\zh-CN\Nodes\rgthree-comfy.json
这段删除
Note that you need to put \custom_nodes\AIGODLIKE-ComfyUI-Translation\zh-CN\Nodes\rgthree-comfy.json in the translation plug-in
Delete this paragraph

2、无法桥接ps则需要安装UXP
If you cannot bridge ps, you need to install UXP

3、无法运行产生图片报错，请检查模型是否有自己选择，以及全局连线中如果开启了翻译插件，步数，调度器，采样器，是否与对应接口文本一致（大小写）
If it cannot run and generates a picture error, please check whether the model has your own selection, and if the translation plug-in, step number, scheduler, and sampler are enabled in the global connection, whether they are consistent with the corresponding interface text (uppercase and lowercase)

**Comment by NimaNzrii** [comment]
## Language Support added✨
update the node and reload the sd1.5 workflow

![Untitled-1](https://github.com/user-attachments/assets/2c069975-0f39-4c6a-a87a-116b9bd58f82)

**Comment by huanli11** [comment]
我图像生产了 但是ps 插件里不显示  我重装ps和comfyui  都没解决 不知道什么情况
