### ISSUE TITLE
Feature request Request to modify the style and add layer transfer function

### ISSUE THREAD

**Issue by bubbl000** [NimaNzrii/comfyui-photoshop#221]
![image](https://github.com/user-attachments/assets/284205a0-4917-4cbc-9cdc-5195167e12e1)
1. I think the slider part is a bit wide and blocks part of the screen. The button in the upper left corner also blocks the screen. It can be moved to the lower left corner to match the style of the other two buttons. Secondly, I think the function of zooming in on the preview image can be removed because it is almost never used. When zooming in, you basically view it within the canvas, and you can enlarge the picture even if you don’t click on the zoom button and drag the entire frame, so I think this function can be removed.
![image](https://github.com/user-attachments/assets/ec3f90bc-e7c3-40df-992b-227039fba280)
2. Request to add a language switching function at this location, and then provide a text to allow users to translate the text in the UI interface. In this way, even if it is updated in the future, there is no need to translate and update the content again.
3. Request to add a function
![image](https://github.com/user-attachments/assets/86276f74-dc4d-48b3-b53f-614830f84534)
For example, after clicking the added button, this frame will appear, and then clicking the option will get the selected layer, and the layer will be sent to comfyui (you may need to add a new plug-in node, the option is temporarily named comfyui layer)
Then the options in the ps plug-in automatically increase or decrease the options based on how many comfyui layers there are in comfyui.
(This function can be applied to the picture reference function)

**Comment by NimaNzrii** [comment]
amazing ideas! will apply them on v2,
your ideas are great, i really like to share with you the concept of V2 

can you message me in discord?
id: NimaNzrii
