### ISSUE TITLE
comfyui-photoshop1.9.1 中文版

### ISSUE THREAD

**Issue by zh2650307** [NimaNzrii/comfyui-photoshop#222]
安装方法
1.复制Plug-ins目录下文件夹到PS安装目录Plug-ins下
2.复制custom_nodes目录下的文件夹【comfyui-photoshop】到comfyui的【custom_nodes】目录下
﻿
解决预设不显示问题
3.删除comfyui的【custom_nodes】目录下的翻译插件AIGODLIKE-ComfyUI-Translation
4.复制我提供的AIGODLIKE-ComfyUI-Translation插件版本到comfyui的custom_nodes目录下
﻿
[汉化效果演示如下，节点建议大家学习英文版的节点，界面用中文的就行，1.9.1中文插件文件，我免费提供给大家，支持作者的点个赞，感谢NimaNzrii作者。]

下载链接: https://pan.baidu.com/s/11SaKuy76eJjR82vxqTY7RA 提取码: iv7g 

![1](https://github.com/user-attachments/assets/a44187a5-8eb5-4677-8167-b13252a0dd90)
![2](https://github.com/user-attachments/assets/53bc130d-f945-48e7-9be8-a1b2b83d9312)
![3](https://github.com/user-attachments/assets/f1ce9cf7-ac71-49e9-aa58-f8f1cc4f5325)
![4](https://github.com/user-attachments/assets/2ecd43fd-2c1b-4103-b391-1ab0845fec6b)
![5](https://github.com/user-attachments/assets/5cd2070b-a41c-4fab-86b7-0e88de749fb3)
![6](https://github.com/user-attachments/assets/8881973a-dc64-4e8c-bd59-f7aacbb28a99)
![7](https://github.com/user-attachments/assets/d9bc08fd-e443-428f-8a3f-a871a8d11d45)
![8](https://github.com/user-attachments/assets/cff91d4e-837a-4ef7-aff7-27dcf092df75)
![9](https://github.com/user-attachments/assets/bd42bb67-c33a-4d9a-8253-1b1cbd1907d7)
![10](https://github.com/user-attachments/assets/0c63f297-2240-43f0-b1f7-7054a35c22f7)

**Comment by zh2650307** [comment]
需要删除翻译插件，替换成我发的翻译插件，重启comfyui，在ps界面打开comfyui主界面，清掉工作流，重新加载photoshop plugin，载入SD1.5工作流；就会显示了

**Comment by xiaoquanzia** [comment]
十分感谢，完美使用

**Comment by huacuoni** [comment]
为啥我替换了文件，PS插件还是英文界面？

**Comment by NimaNzrii** [comment]
@huacuoni @xiaoquanzia @guangxinzhao @zh2650307 

![image](https://github.com/user-attachments/assets/88ac0060-806c-4e5b-ad9a-f75c85ede6f1)
![image](https://github.com/user-attachments/assets/014210ff-41c2-4643-afba-2acbaea02bd9)

# 官方在版本1.9.2中新增了簡體中文、繁體中文、日文和韓文，現在所有更新都會有翻譯了 

感谢您安装这个插件
🐦‍🔥

**Comment by NimaNzrii** [comment]
![image](https://github.com/user-attachments/assets/2582323f-fe3a-45c6-a375-a72ce7b15d37)

**Comment by kanzifufu** [comment]
> 官方在版本1.9.2中新增了簡體中文、繁體中文、日文和韓文，現在所有更新都會有翻譯了

感谢您的更新修复。但是版本1.9.3中，点击load SD 1.5按钮，仍旧无法自动加载工作流。
