### ISSUE TITLE
1.9.2版本中文版预设无法加载，临时解决办法

### ISSUE THREAD

**Issue by zh2650307** [NimaNzrii/comfyui-photoshop#223]
关于1.9.2中文版，当comfyui为中文语言界面，预设无法加载的解决办法。
解决方法：
需要删除路径custom_nodes\AIGODLIKE-ComfyUI-Translation\zh-CN\Nodes下的所有文件，重启comfyui，重启PS，PS上面重载工作流，就能完美解决。主要原因是插件的节点不兼容，只能等待作者去修复这个问题。

I have reported the bug to the author multiple times, and the author has made great efforts. Thank you for his hard work. The main plugin now supports multiple language versions and solves the problem of real-time rendering freezing bug. Give the author a thumbs up and support！
![QQ截图20240830090210](https://github.com/user-attachments/assets/23c7cb5a-9b44-4861-807f-ed30a0b005ac)
![QQ截图20240830090228](https://github.com/user-attachments/assets/d6e4b4d4-9df3-49e3-a21f-c7fdacf61d1b)

**Comment by zh2650307** [comment]
[sd15_zh-CN.json](https://github.com/user-attachments/files/16809206/sd15_zh-CN.json)
Replace the file with the same name in the directory custom_nodes \ comfyui photoshop \ data \ workflows \

**Comment by balumiisa** [comment]
![image](https://github.com/user-attachments/assets/9071a356-1f03-44a8-a04f-a60f3b638690)
![image](https://github.com/user-attachments/assets/0b916522-312b-4283-81c8-4ae07b7bb52b)
大佬，我这个是咋回事能不能帮我看看啊？

**Comment by sowabcd** [comment]
说明你的photoshop和comfyui没有连接成功。

**Comment by balumiisa** [comment]
> 说明你的photoshop和comfyui没有连接成功。
![image](https://github.com/user-attachments/assets/bbe382a8-b738-42b7-8d1d-7882857ad88c)

怎么检查呢？我看上面显示已经连接了啊~

**Comment by zh2650307** [comment]
我QQ：904489260，todesk，远程给你看一下

**Comment by NimaNzrii** [comment]
Is this a better translation Version?

**Comment by zh2650307** [comment]
yes

**Comment by NimaNzrii** [comment]
Hi , you Right, will fix it tonight 
It seems translator will act differently on each language!

So should fiz it for Chinese ver

**Comment by NimaNzrii** [comment]
# Fixed✅
thank you all for reporting this problem

no need to re install the plugin 
just update the node to fix the problem

**Comment by NimaNzrii** [comment]
修复完成✅
感谢大家报告这个问题

不需要重新安装插件
只需更新节点即可修复问题

@zh2650307 @sowabcd @balumiisa

**Comment by NimaNzrii** [comment]
also please let me know if the translation wants good or want to edit any part

如果翻译不准确或需要修改任何部分，请告诉我。

**Comment by zh2650307** [comment]
ok

**Comment by zh2650307** [comment]
Thank you, sir. You have perfectly solved the problem of default not displaying. There are still some translation issues that need you to improve.
1. The sd15_zh-CN.json translation is not perfect. I have modified it. You can replace it directly. Check the attachment. It is easier for Chinese people to understand.
2. There is also a load sd1.5 preset that can be translated into Chinese strings, which is more user-friendly.
3. There are no Chinese prompt words in the front prompt box, which needs to be fixed; Last time you said that some PS were incompatible, but it didn't really affect it. I tested it on my end and there was no problem.
4. Need Help string, translated into Chinese, 需要帮助?

**Comment by NimaNzrii** [comment]
> ok Message ID: ***@***.***&gt;

Do you have discord? 
Dm me please 
Id : NimaNzrii

**Comment by kanzifufu** [comment]
我点击load sd 1.5按钮工作流不自动加载，删除楼主您提到的文件也如此，不知道是什么问题。

**Comment by Nagiha1234** [comment]
我也有同样的问题存在，请问现在有解决办法了么
