### ISSUE TITLE
can' work in PS 2022

### ISSUE THREAD

**Issue by shikochi** [NimaNzrii/comfyui-photoshop#224]
Hello, I saw in the official website's instructions that PS 2022 is supported, but after installing it, 
I still can't find the comfy option in the PS plugin. 
Does PS 2022 need to be the official version for it to work?

**Comment by NimaNzrii** [comment]
Did you install the la plugin and comfyui node as well?

**Comment by shikochi** [comment]
yes ;(

**Comment by NimaNzrii** [comment]
can u please send me some images?

**Comment by shikochi** [comment]
The plugin also shows as installed on the Adobe CC Manage Plugins page. but it just doesn't appear in PS.
![螢幕擷取畫面 2024-09-02 100515](https://github.com/user-attachments/assets/f351eca4-2d2f-44fd-9db2-e92da9626210)
![螢幕擷取畫面 2024-09-02 100218](https://github.com/user-attachments/assets/42fc41e8-30d9-4f9c-abf3-1c2255e26e8e)
