### ISSUE TITLE
Undefined Ksampler Config nodes in plugin interface

### ISSUE THREAD

**Issue by TorAllex** [NimaNzrii/comfyui-photoshop#230]
`invalid prompt: {'type': 'invalid_prompt', 'message': 'Cannot execute because a node is missing the class_type property.', 'details': "Node ID '#1982'", 'extra_info': {}}`
All OK in ComfyUI, but plugin dont works
![Снимок экрана 2024-09-03 в 02 56 23](https://github.com/user-attachments/assets/454dbf2a-45fc-4174-ab78-2c212fddda4d)
![Снимок экрана 2024-09-03 в 02 57 30](https://github.com/user-attachments/assets/4c12bff1-3208-47cc-9916-8f6ce7449aba)

**Comment by fu-jianhua** [comment]
me too![f16163e7-049c-4bfa-81b7-c656d31ae109](https://github.com/user-attachments/assets/c7c96ce4-d741-446d-958f-b6d60a77f816)

**Comment by NimaNzrii** [comment]
Please send me your comfyui logfile

**Comment by TorAllex** [comment]
> Please send me your comfyui logfile

[comfyui.log](https://github.com/user-attachments/files/16852411/comfyui.log)

**Comment by TorAllex** [comment]
oops. everything is working now

**Comment by halowhoi9** [comment]
Hi, I have the same problem. @TorAllex can you help me maybe?

**Comment by TorAllex** [comment]
> Hi, I have the same problem. @TorAllex can you help me maybe?

I'm not sure of my understanding of the reasons, maybe you should update Comfy

**Comment by letmejustfinishthistaskthanks** [comment]
same issue.

**Comment by yitao2020** [comment]
I also encountered similar problems. I deleted the original KSAMPLECONFIG node.

**Comment by genesis-7** [comment]
I have the same problem need help
