### ISSUE TITLE
After today's update, sending ps failed

### ISSUE THREAD

**Issue by huanli11** [NimaNzrii/comfyui-photoshop#231]
After today's update, sending ps failed

**Comment by NimaNzrii** [comment]
What ver are u using right now

**Comment by huanli11** [comment]
Adobe Photoshop 2024 (v25.11) Multilingual

**Comment by tokenholic** [comment]
Me too, my ps is 24.6.0

**Comment by Tenney95** [comment]
25.9.0 too

**Comment by NimaNzrii** [comment]
# Comfy Bug Fixed
guys in the latest comfy update there was some big problem with workflwos! please update the node one more time and load the workflow again
