### ISSUE TITLE
Photoshop ComfyUI Plugin: NO DATA

### ISSUE THREAD

**Issue by chrislailiru** [NimaNzrii/comfyui-photoshop#232]
text 2 img is OK!

but img 2 img get error as the pic.
![微信截图_20240906112018](https://github.com/user-attachments/assets/89248c51-5147-4155-a9c9-77415d444c6a)

So in this problem, I can not get the picture from t2i to a new layer in PS.

**Comment by Artistic2** [comment]
I also have the same issue. Have you found any solution?

**Comment by Thomas-Liang** [comment]
I have the same issue,i tried to delete the pycache in the following path, it works well.
![ff00e340e67c9e84ed5fc82e7407722](https://github.com/user-attachments/assets/54987ed4-ce11-4242-99c1-467fba2d22e4)

**Comment by chrislailiru** [comment]
> I have the same issue,i tried to delete the pycache in the following path, it works well. ![ff00e340e67c9e84ed5fc82e7407722](https://private-user-images.githubusercontent.com/67848615/366242253-54987ed4-ce11-4242-99c1-467fba2d22e4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxMDUyMjEsIm5iZiI6MTcyNjEwNDkyMSwicGF0aCI6Ii82Nzg0ODYxNS8zNjYyNDIyNTMtNTQ5ODdlZDQtY2UxMS00MjQyLTk5YzEtNDY3ZmJhMmQyMmU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEyVDAxMzUyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1YjU2NGFlZGE2MmFiNTdlYTZiNTRjYjU1ZjI1ZThlNjllNTNlYWZiMzY2NzkwNWM4OWI3YjYyMDk1ZWJmNmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.32tGNoyu414XgFJX8ixtf-YXD9aOrcNfsc2T-8PK-lc)

Still can not get the data...

**Comment by NimaNzrii** [comment]
> > I have the same issue,i tried to delete the pycache in the following path, it works well. ![ff00e340e67c9e84ed5fc82e7407722](https://private-user-images.githubusercontent.com/67848615/366242253-54987ed4-ce11-4242-99c1-467fba2d22e4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxMDUyMjEsIm5iZiI6MTcyNjEwNDkyMSwicGF0aCI6Ii82Nzg0ODYxNS8zNjYyNDIyNTMtNTQ5ODdlZDQtY2UxMS00MjQyLTk5YzEtNDY3ZmJhMmQyMmU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEyVDAxMzUyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1YjU2NGFlZGE2MmFiNTdlYTZiNTRjYjU1ZjI1ZThlNjllNTNlYWZiMzY2NzkwNWM4OWI3YjYyMDk1ZWJmNmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.32tGNoyu414XgFJX8ixtf-YXD9aOrcNfsc2T-8PK-lc)
> 
> Still can not get the data...

You can try deleteing the _pycache_ folder inside py folder as well

Please let me know if it worked for you

**Comment by NimaNzrii** [comment]
# Comfy Bug Fixed
guys in the latest comfy update there was some big problem with workflwos! please update the node one more time and load the workflow again

**Comment by Artistic2** [comment]
![image](https://github.com/user-attachments/assets/d291e3e9-1582-4d16-a056-b5a7196ea8ba)
For me, the issue was fixed by right-clicking and selecting 'Install PS Plugin v1.9.3'.
I had installed the plugin earlier as well from the link, but I don’t know why it worked only after installing it again from the right-click menu.
