### ISSUE TITLE
Images imported from Photoshop to ComfyUI via this plugin have significant quality loss. PNG or JPG?

### ISSUE THREAD

**Issue by TiptopFunk** [NimaNzrii/comfyui-photoshop#239]
i have noticed the image imported from Photoshop Canvas to Comfyui have significant quality loss.
Which lead to bad results in Inpainting, outpainting, and upscaling

What format are the images when export to ComfyUI: PNG or JPG?

As you can see, the original image in photoshop, and the image in ComfyUI gotten from the canvas port. The right one has banding and noise. like jpg artifacts.

![image get from Photoshop Comfyui plugin canvas port, RGB_8 ](https://github.com/user-attachments/assets/3d3a0036-cdb6-4d56-a73d-31f143e391ce)

**Comment by TiptopFunk** [comment]
Update, a temp solution to fix this issue, 
I install another plugin call [Sd-ppp](https://github.com/zombieyang/sd-ppp).
it doesn't suffer from the same issues. I use the SDPPP Get image from photoshop node's RGB output instead of Canvas output.
![Compare](https://github.com/user-attachments/assets/e89ab28b-2529-4d8f-b6df-119855c77372)

![SDPPP](https://github.com/user-attachments/assets/9e62b78f-d7aa-440e-b9ea-3a52b29fbd73)

**Comment by LiJT** [comment]
wow this is so good! Thanks man!

**Comment by LiJT** [comment]
Hi Can I ask why you stick with Nimas version of this plugin instead of just using sdppp? whats the sdppp disadvantage you think it has?

**Comment by TiptopFunk** [comment]
> Hi Can I ask why you stick with Nimas version of this plugin instead of just using sdppp? whats the sdppp disadvantage you think it has?

For Nima's version:

Advantages:

1. It offers established workflows and a more intuitive ui. You can easily switch between different workflows within Photoshop without constantly needing to go back to Chrome.

2. I've built my own SDXL workflow based on Nima's, incorporating features like Text to Image (with or without ControlNet), Image to Image (with or without ControlNet), Asset generation with Layered Diffusion, Background Replacement with Brushnet, Inpainting and Outpainting with ControlNet Union Pro Max or Focoous, Upscaling with Tile, SD3, and Flux as a refiner. This flexibility allows me to switch between workflows seamlessly.

3. You can perform most of your daily image editing tasks directly within Photoshop.

Disadvantage:
When using ControlNet or iPadapter, you still need to go to ComfyUI to manually select the image for these features.

For SDPPP:
1. SDPPP offers greater flexibility, allowing you to directly use different layers for ControlNet or iPadapter. This is a significant advantage, as you can work on your editing within a single PSD file.

2. However, due to its flexibility, you may need to switch between different workflows for various tasks.


I may try to combine Nima's plugin and SDPPP to see if we can achieve a better experience similar to the Krita AI Plugin by Acly.

Why I not just using Krita, because I'm too lazy to learn a new software. haha.

**Comment by LiJT** [comment]
> > Hi Can I ask why you stick with Nimas version of this plugin instead of just using sdppp? whats the sdppp disadvantage you think it has?
> 
> For Nima's version:
> 
> Advantages:
> 
> 1. It offers established workflows and a more intuitive ui. You can easily switch between different workflows within Photoshop without constantly needing to go back to Chrome.
> 2. I've built my own SDXL workflow based on Nima's, incorporating features like Text to Image (with or without ControlNet), Image to Image (with or without ControlNet), Asset generation with Layered Diffusion, Background Replacement with Brushnet, Inpainting and Outpainting with ControlNet Union Pro Max or Focoous, Upscaling with Tile, SD3, and Flux as a refiner. This flexibility allows me to switch between workflows seamlessly.
> 3. You can perform most of your daily image editing tasks directly within Photoshop.
> 
> Disadvantage: When using ControlNet or iPadapter, you still need to go to ComfyUI to manually select the image for these features.
> 
> For SDPPP:
> 
> 1. SDPPP offers greater flexibility, allowing you to directly use different layers for ControlNet or iPadapter. This is a significant advantage, as you can work on your editing within a single PSD file.
> 2. However, due to its flexibility, you may need to switch between different workflows for various tasks.
> 
> I may try to combine Nima's plugin and SDPPP to see if we can achieve a better experience similar to the Krita AI Plugin by Acly.
> 
> Why I not just using Krita, because I'm too lazy to learn a new software. haha.

wow dude awesome insight! thanks and i will have a look at both! Kirta is much much easier to use and dont even need to tinker with the comfyui workflow at all. I truely wish there is system level replacement for PS as well! Thanks anyway! and I hope Nima can fix the color banding issue as well

**Comment by locsmax** [comment]
Wow, this is amazing! I didn’t know about SD-PPP. I recently asked Nima to add a way to select a layer for ControlNet, and this is perfect for that.

I feel like Nima’s tool gives us more control in Photoshop, but the option to select layers is so useful that I think it’s necessary to install SD-PPP as well.

**Comment by NimaNzrii** [comment]
@LiJT @TiptopFunk @locsmax all of these features and more are coming in V2 🙂
