### ISSUE TITLE
Problem with MacStudio M1

### ISSUE THREAD

**Issue by tsevis** [NimaNzrii/comfyui-photoshop#25]
Hi, Thanks for this plug-in. Highly appreciated.
However I couldn't make it run on my MacStudio. This is the error message I am getting.
Thanks in advance.

Error occurred when executing ImageResize+:

'>' not supported between instances of 'str' and 'int'

File "/Users/tsevis/AI/ComfyUI/execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/tsevis/AI/ComfyUI/execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/tsevis/AI/ComfyUI/execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/tsevis/AI/ComfyUI/custom_nodes/ComfyUI_essentials/essentials.py", line 100, in execute
if multiple_of > 1:
^^^^^^^^^^^^^^^

**Comment by NimaNzrii** [comment]
# Fixed ✨

hi, this error should be fixed now
**download the latest version** of the workflow and let me know if it worked

https://openart.ai/workflows/spoonbill_hospitable_34/photoshop-in-comfyui/lreWarJbqiYPcDXnD8hh

**Comment by tsevis** [comment]
Hi Nima,
Thanks so much for your help! It worked perfectly now!
Congratulations for your work and many many thanks for your contribution to the AI Art community.
Have a great weekend.
