### ISSUE TITLE
Missing Node Types: WorkflowKsampler Config

### ISSUE THREAD

**Issue by creation-arts** [NimaNzrii/comfyui-photoshop#258]
Hi! 

This Comfy-Photoshop integration looks awesome! Thank you for this.
First time ever using comfy, installed it through Pinokkio. I installed everything successfully.

I have an issue though.. Probably something on my end, but would love some help or advice.

When I open workflow-sd15 I get a message:

"Missing Node Types" 
WorkflowKsampler Config

But I can't detect or find it when I check for missing custom nodes? 

![Screenshot 2024-10-31 at 18 57 18](https://github.com/user-attachments/assets/8f469324-f151-405e-bc89-3dec44708184)
![Screenshot 2024-10-31 at 18 58 43](https://github.com/user-attachments/assets/712a7d92-7321-4c7f-b0a3-0de10220ef36)

Thank you for your help.

**Comment by GeminiSquishGames** [comment]
I don't get the error unless I try to load the workflow manually which isn't how you use it so it won't load that KSampler config (also it's just a config, not really a full workflow or node) it only sets the config properly when I load it through the main plugin node using load sd 1.5 button:
![image](https://github.com/user-attachments/assets/63ef99f9-f875-4b67-8521-6f0b7fc8075e) then the nodes will all be green.

I think that will at least give you the presets you have selected in that workflow. However I haven't really gotten it to successfully send from photoshop and just get the no data image, which at full denoise will give me an image that follows the prompt, but that's pretty useless. 

https://youtu.be/YD09xpQrNZ4?t=259 The way he explains it here, you should just be able to get that main node to work on it's own, but I sure and sugar can't, just shows no data, even though it's connected in the plugins settings. It's just not picking up the canvas. So there may be other issues if you cannot simply use the node without opening the workflow as well.

**Comment by creation-arts** [comment]
Ah I got it.. thanks. But, yeah same here.. I followed the tutorial, its pretty straight forward, but it I keep getting the "NO DATA" message in the ComfyUI plugin pannel, just like you have. When I go to photoshop and write my prompt, the render button is not working. And when I click presets, it says "Couldn't load". So it looks like the plugin does not connect to Comfy. Is this a Mac thing? Or a Photoshop 2025 thing? Or am I just not doing it right.

Hope someone else can shed some light on this issue. Help would be very much appreciated! Can't wait to use this tool.

**Comment by GeminiSquishGames** [comment]
The difference in the panels is because of a difference in versions from back then I think. I have the blue porpoise too and when I get it connected and have presets it's a chameleon, then it becomes the image I have in the prompt, but still no connection to the photoshop canvas, 😔

Have you tried Krita and it's Comfy plugin by any chance? It works well, actually I was wanting to use them together since I like how easy selecting things and fixing is in photoshop and like how Krita's plugin works in Live mode and my tablet gets along with it better, but ymmv. https://github.com/Acly/krita-ai-diffusion

**Comment by creation-arts** [comment]
Sorry for the late response.. And thank you for mentioning Krita, I haven't got around to test it though. 

I did got myself a brand new computer, windows machine, and tried running the plugin and ComfyUI. At first I had the same problem as before, but then I saw there was an update for the plugin (windows) version 1.9.3 after updating the photoshop connected to to Comfy without any problem.

**Comment by creation-arts** [comment]
Sorry for the late response.. And thank you for mentioning Krita, I haven't got around to test it though. 

I did got myself a brand new computer, windows machine, and tried running the plugin and ComfyUI. At first I had the same problem as before, but then I saw there was an update for the plugin (windows) version 1.9.3 after updating the photoshop connected to to Comfy without any problem.
