### ISSUE TITLE
ImageResize_ + error

### ISSUE THREAD

**Issue by hooknick** [NimaNzrii/comfyui-photoshop#26]
Error occurred when executing ImageResize+:

'>' not supported between instances of 'str' and 'int'

File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-0246\utils.py", line 381, in new_func
res_value = old_func(*final_args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_essentials\essentials.py", line 100, in execute
if multiple_of > 1:
^^^^^^^^^^^^^^^
![error](https://github.com/NimaNzrii/comfyui-photoshop/assets/126495774/7a37764e-62ac-471d-b62f-a0d0c39310c0)

**Comment by NimaNzrii** [comment]
# Fixed

hi, this error should be fixed now
download the latest version of the workflow and let me know if it worked

https://openart.ai/workflows/spoonbill_hospitable_34/photoshop-in-comfyui/lreWarJbqiYPcDXnD8hh

**Comment by hooknick** [comment]
screenshot of new error attached. 
![error2](https://github.com/NimaNzrii/comfyui-photoshop/assets/126495774/5d6f336a-a603-4575-a19e-72e5f41077c6)

**Comment by NimaNzrii** [comment]
https://github.com/NimaNzrii/comfyui-photoshop/assets/148809650/08998edf-7242-42a2-9a0b-247f0d7b334f

# Please Do this and send a screen shot of the red node

**Comment by hooknick** [comment]
attached 
![nodes](https://github.com/NimaNzrii/comfyui-photoshop/assets/126495774/37f77582-7376-43ab-ab25-36b3de0d1279)

**Comment by NimaNzrii** [comment]
could u please clear the screen and add a photoshop to comfyui plugin and see if you can get any image from the node?

**Comment by hooknick** [comment]
yes that worked just fine. example attached. 
![test](https://github.com/NimaNzrii/comfyui-photoshop/assets/126495774/ae7604d4-0eea-44b1-b6d6-d74979fb9804)

**Comment by NimaNzrii** [comment]
![Screenshot_2024-05-11-00-43-20-642_com android chrome](https://github.com/NimaNzrii/comfyui-photoshop/assets/148809650/33022ca1-95c0-49b0-bafd-93c0286bacd8)
Most of the informations are missing, it's Just like a comfyui bug
I hoped i had the same issue 

But idk what should i do for it now

**Comment by hooknick** [comment]
what settings should I use? Maybe because the nodes are grouped when uploading the workflow vs expanded?

**Comment by NimaNzrii** [comment]
Yeah it's probably because of group node, so let me quiqly create an specific json file for you

**Comment by NimaNzrii** [comment]
[workflow - 2024-05-11T010025.886.json](https://github.com/NimaNzrii/comfyui-photoshop/files/15280186/workflow.-.2024-05-11T010025.886.json)
this version should work for you

**Comment by NimaNzrii** [comment]
but if it didnt work again
just test this one instead:
[workflow - 2024-05-11T010144.678.json](https://github.com/NimaNzrii/comfyui-photoshop/files/15280190/workflow.-.2024-05-11T010144.678.json)

please let me know if the first one worked for you

**Comment by hooknick** [comment]
First one did the trick! thank you so much. Not just the support, but the plugin as well.

**Comment by NimaNzrii** [comment]
# Thank you a lot ✨
You helped me to fix this annoying issue
the clean version of the workflow is on this link if you want:

https://openart.ai/workflows/spoonbill_hospitable_34/photoshop-in-comfyui/lreWarJbqiYPcDXnD8hh
