### ISSUE TITLE
plugin black window

### ISSUE THREAD

**Issue by avenir22** [NimaNzrii/comfyui-photoshop#32]
Hi, I get a black plugin window from photoshop even when I have a drawing on a layer, any ideas? I had to install the extension manually because the app to install it (locally) gave me an error. Seems like the plugin is not interacting with photoshop. The only function that works is txt2img. When I first installed the extension I saw the dolphin once. Comfyui is running but it only generates txt2img. "send to layers" doesn't work.

<img width="999" alt="Capturewww" src="https://github.com/NimaNzrii/comfyui-photoshop/assets/66291477/c79bb1e9-57cc-4575-af72-ee90a1f67f19">

<img width="1043" alt="Captureaaa" src="https://github.com/NimaNzrii/comfyui-photoshop/assets/66291477/379aadab-ba6b-4eec-a383-2c81acc3f6da">

**Comment by NimaNzrii** [comment]
what device are you using?
what os are you using?

**Comment by avenir22** [comment]
> what device are you using? what os are you using?

win10, desktop computer, photoshop v24.0

**Comment by bubbl000** [comment]
![image](https://github.com/NimaNzrii/comfyui-photoshop/assets/108770692/555b34a7-679c-4ec0-8407-be073a4fc522)
High probability because it is your place did not modify yourself, you are probably using the ui interface translation, this place you need to change to the corresponding

**Comment by bubbl000** [comment]
High probability because it is your place did not modify yourself, you are probably using the ui interface translation, this place you need to change to the corresponding
![image](https://github.com/NimaNzrii/comfyui-photoshop/assets/108770692/e677acd0-5c4b-4386-9dcf-3dd8819d2e24)
Check if you are using node translation
Check whether the node name is the same as that of the corresponding node

**Comment by avenir22** [comment]
> High probability because it is your place did not modify yourself, you are probably using the ui interface translation, this place you need to change to the corresponding ![image](https://private-user-images.githubusercontent.com/108770692/329804103-e677acd0-5c4b-4386-9dcf-3dd8819d2e24.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0NDk2NjAsIm5iZiI6MTcxNTQ0OTM2MCwicGF0aCI6Ii8xMDg3NzA2OTIvMzI5ODA0MTAzLWU2NzdhY2QwLTVjNGItNDM4Ni05ZGNmLTNkZDg4MTlkMmUyNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxMVQxNzQyNDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZGNkYzU4OTI1MWM4ZTM0NGY0YTUxYzcyNWRiNWE0OTcwMzMwYzUyZTU2ZTdkODVjMmVlMDZjOTBlMDdmNDUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gXdKe3GoKWMl-BvkzYWEpWlJP0EwA5iq_nmyQLzPJ54) Check if you are using node translation Check whether the node name is the same as that of the corresponding node

I didn't modify the workflow, could you explain why this is relevant?

**Comment by bubbl000** [comment]
> > High probability because it is your place did not modify yourself, you are probably using the ui interface translation, this place you need to change to the corresponding Check if you are using node translation Check whether the node name is the same as that of the corresponding node大概率因为是你的地方没有修改自己，你很可能正在用ui界面转换，这个地方你需要换到对应的节点转换 检查节点名称是否与对应节点的名称相同
> 
> I didn't modify the workflow, could you explain why is this relevant?我没有修改工作流程，您能解释一下为什么这很重要吗？

因为你用了翻译，所以节点接口标题被改变了 我发送的图片红圈位置写指明了要传送数据到哪个地方相当于连线
Because you used the translation, the node interface title has been changed The image I sent is circled in red to indicate where I want to send the data to the wire

**Comment by avenir22** [comment]
> > > High probability because it is your place did not modify yourself, you are probably using the ui interface translation, this place you need to change to the corresponding Check if you are using node translation Check whether the node name is the same as that of the corresponding node大概率因为是你的地方没有修改自己，你很可能正在用ui界面转换，这个地方你需要换到对应的节点转换 检查节点名称是否与对应节点的名称相同
> > 
> > 
> > I didn't modify the workflow, could you explain why is this relevant?我没有修改工作流程，您能解释一下为什么这很重要吗？
> 
> 因为你用了翻译，所以节点接口标题被改变了 我发送的图片红圈位置写指明了要传送数据到哪个地方相当于连线 Because you used the translation, the node interface title has been changed The image I sent is circled in red to indicate where I want to send the data to the wire

I'm not using any translation node, I simply installed the workflow as it is.

**Comment by avenir22** [comment]
> what device are you using? what os are you using?

any comments on this? thanks

**Comment by avenir22** [comment]
> > what device are you using? what os are you using?
> 
> win10, desktop computer, photoshop v24.0

any comments on this? thanks

**Comment by NimaNzrii** [comment]
Could you please test if you can get positive and negative prompts?

**Comment by avenir22** [comment]
> Could you please test if you can get positive and negative prompts?

Yes it's generating images using a prompt in both sides photoshop and comfyui. It turns black when I turn down the creative slide. The thing that isn't working is pulling an image from a layer to do img2img, also the "send to layer" isn't working as well.

**Comment by bubbl000** [comment]
> > > > High probability because it is your place did not modify yourself, you are probably using the ui interface translation, this place you need to change to the corresponding Check if you are using node translation Check whether the node name is the same as that of the corresponding node大概率因为是你的地方没有修改自己，你很可能正在用ui界面转换，这个地方你需要换到对应的节点转换 检查节点名称是否与对应节点的名称相同
> > > 
> > > 
> > > I didn't modify the workflow, could you explain why is this relevant?我没有修改工作流程，您能解释一下为什么这很重要吗？
> > 
> > 
> > 因为你用了翻译，所以节点接口标题被改变了 我发送的图片红圈位置写指明了要传送数据到哪个地方相当于连线 Because you used the translation, the node interface title has been changed The image I sent is circled in red to indicate where I want to send the data to the wire
> 
> I'm not using any translation node, I simply installed the workflow as it is.我没有使用任何翻译节点，我只是按原样安装了工作流。
I found that you can generate the picture normally, but the ps can't get it because the place is not connected to
![image](https://github.com/NimaNzrii/comfyui-photoshop/assets/108770692/f0d5f74d-478e-4737-8ee4-c350c641faa9)

**Comment by avenir22** [comment]
> > > > > High probability because it is your place did not modify yourself, you are probably using the ui interface translation, this place you need to change to the corresponding Check if you are using node translation Check whether the node name is the same as that of the corresponding node大概率因为是你的地方没有修改自己，你很可能正在用ui界面转换，这个地方你需要换到对应的节点转换 检查节点名称是否与对应节点的名称相同
> > > > 
> > > > 
> > > > I didn't modify the workflow, could you explain why is this relevant?我没有修改工作流程，您能解释一下为什么这很重要吗？
> > > 
> > > 
> > > 因为你用了翻译，所以节点接口标题被改变了 我发送的图片红圈位置写指明了要传送数据到哪个地方相当于连线 Because you used the translation, the node interface title has been changed The image I sent is circled in red to indicate where I want to send the data to the wire
> > 
> > 
> > I'm not using any translation node, I simply installed the workflow as it is.我没有使用任何翻译节点，我只是按原样安装了工作流。
> > I found that you can generate the picture normally, but the ps can't get it because the place is not connected to

Could you upload the workflow that is working for you?

**Comment by NimaNzrii** [comment]
Could you please send me the log file of your comfyui?

Are you using the portable version of comfyui?

**Comment by avenir22** [comment]
> Could you please send me the log file of your comfyui?
> 
> Are you using the portable version of comfyui?

yes I'm using portable version. How do I generate the log file?

**Comment by avenir22** [comment]
> Could you please send me the log file of your comfyui?
> 
> Are you using the portable version of comfyui?

yes, I'm using portable version.
this is the log file 
[comfyui-log.txt](https://github.com/NimaNzrii/comfyui-photoshop/files/15287128/comfyui-log.txt)

**Comment by avenir22** [comment]
> > Could you please send me the log file of your comfyui?
> > Are you using the portable version of comfyui?
> 
> yes, I'm using portable version. this is the log file [comfyui-log.txt](https://github.com/NimaNzrii/comfyui-photoshop/files/15287128/comfyui-log.txt)

@NimaNzrii do you have any comment on this, thank you :)

**Comment by NimaNzrii** [comment]
It seems Photoshop or maybe antivirus doesn't let the plugin save the canvas in your Photoshop

I'm working on a new method to move data
So it will work 100% for you

But it's not an ez process 
I will notice you when fixed❤️

**Comment by avenir22** [comment]
> It seems Photoshop or maybe antivirus doesn't let the plugin save the canvas in your Photoshop
> 
> I'm working on a new method to move data So it will work 100% for you
> 
> But it's not an ez process I will notice you when fixed❤️

ok, great, thank you!

**Comment by bubbl000** [comment]
[单图改光照 (1) (1).json](https://github.com/NimaNzrii/comfyui-photoshop/files/15297755/1.1.json)
I've only changed it a little bit, and I've used a translation, so you'll have to make your own changes

**Comment by bubbl000** [comment]
![image](https://github.com/NimaNzrii/comfyui-photoshop/assets/108770692/50a88884-5a1d-4924-a8e8-ce488f0088c8)
Connect like this~~ I don't know how to change the name of this node, so I can only connect it directly with a wire

**Comment by avenir22** [comment]
) Connect like this~~ I don't know how to change the name of this node, so I can only connect it directly with a wire

didn't work, thanks for trying. It's always better to have a working workflow

**Comment by bubbl000** [comment]
> > <img alt="image" width="54.140625" height="21" src="https://private-user-images.githubusercontent.com/108770692/330141063-50a88884-5a1d-4924-a8e8-ce488f0088c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2NDQ5MDgsIm5iZiI6MTcxNTY0NDYwOCwicGF0aCI6Ii8xMDg3NzA2OTIvMzMwMTQxMDYzLTUwYTg4ODg0LTVhMWQtNDkyNC1hOGU4LWNlNDg4ZjAwODhjOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxM1QyMzU2NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZDU0OWE4MDgwZjkyN2M4OWNjMjVmZWY0NDBjMGU5ODFmOTczMDRhMzYwMTJjMDg0ODlmODk4NzU5MDJmODRhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.r1DWb_OEf2lykRCkNpDRxrZflCjVaT9gQM5SW83bYDI"> Connect like this~~ I don't know how to change the name of this node, so I can only connect it directly with a wire <img alt="image" width="54.140625" height="21" src="https://private-user-images.githubusercontent.com/108770692/330141063-50a88884-5a1d-4924-a8e8-ce488f0088c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2NDQ5MDgsIm5iZiI6MTcxNTY0NDYwOCwicGF0aCI6Ii8xMDg3NzA2OTIvMzMwMTQxMDYzLTUwYTg4ODg0LTVhMWQtNDkyNC1hOGU4LWNlNDg4ZjAwODhjOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxM1QyMzU2NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZDU0OWE4MDgwZjkyN2M4OWNjMjVmZWY0NDBjMGU5ODFmOTczMDRhMzYwMTJjMDg0ODlmODk4NzU5MDJmODRhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.r1DWb_OEf2lykRCkNpDRxrZflCjVaT9gQM5SW83bYDI"> 这样连接~~不知道怎么改这个节点的名字，只能直接用电线连接
> 
> > <img alt="image" width="54.140625" height="21" src="https://private-user-images.githubusercontent.com/108770692/330141063-50a88884-5a1d-4924-a8e8-ce488f0088c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2NDQ5MDgsIm5iZiI6MTcxNTY0NDYwOCwicGF0aCI6Ii8xMDg3NzA2OTIvMzMwMTQxMDYzLTUwYTg4ODg0LTVhMWQtNDkyNC1hOGU4LWNlNDg4ZjAwODhjOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxM1QyMzU2NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZDU0OWE4MDgwZjkyN2M4OWNjMjVmZWY0NDBjMGU5ODFmOTczMDRhMzYwMTJjMDg0ODlmODk4NzU5MDJmODRhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.r1DWb_OEf2lykRCkNpDRxrZflCjVaT9gQM5SW83bYDI"> Connect like this~~ I don't know how to change the name of this node, so I can only connect it directly with a wire <img alt="image" width="54.140625" height="21" src="https://private-user-images.githubusercontent.com/108770692/330141063-50a88884-5a1d-4924-a8e8-ce488f0088c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2NDQ5MDgsIm5iZiI6MTcxNTY0NDYwOCwicGF0aCI6Ii8xMDg3NzA2OTIvMzMwMTQxMDYzLTUwYTg4ODg0LTVhMWQtNDkyNC1hOGU4LWNlNDg4ZjAwODhjOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxM1QyMzU2NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZDU0OWE4MDgwZjkyN2M4OWNjMjVmZWY0NDBjMGU5ODFmOTczMDRhMzYwMTJjMDg0ODlmODk4NzU5MDJmODRhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.r1DWb_OEf2lykRCkNpDRxrZflCjVaT9gQM5SW83bYDI"> 这样连接~~不知道怎么改这个节点的名字，只能直接用电线连接
> 
> Why did you chnaged the workflow? It's not working well on this modified one你为什么要修改工作流程？它在这个修改后的版本上效果不佳

Because if I don't connect, the generated image won't be transferred to the ps plugin, and now the flow node is the generated result is not passed to the output to the ps node, so I need to connect, and then try this plugin, of course, in the end I won't use it, I haven't experienced this completely, because I haven't figured out how to put the image of the ps extension into the ps layer

**Comment by bubbl000** [comment]
> > <img alt="image" width="54.140625" height="21" src="https://private-user-images.githubusercontent.com/108770692/330141063-50a88884-5a1d-4924-a8e8-ce488f0088c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2NDQ5MDgsIm5iZiI6MTcxNTY0NDYwOCwicGF0aCI6Ii8xMDg3NzA2OTIvMzMwMTQxMDYzLTUwYTg4ODg0LTVhMWQtNDkyNC1hOGU4LWNlNDg4ZjAwODhjOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxM1QyMzU2NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZDU0OWE4MDgwZjkyN2M4OWNjMjVmZWY0NDBjMGU5ODFmOTczMDRhMzYwMTJjMDg0ODlmODk4NzU5MDJmODRhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.r1DWb_OEf2lykRCkNpDRxrZflCjVaT9gQM5SW83bYDI"> Connect like this~~ I don't know how to change the name of this node, so I can only connect it directly with a wire <img alt="image" width="54.140625" height="21" src="https://private-user-images.githubusercontent.com/108770692/330141063-50a88884-5a1d-4924-a8e8-ce488f0088c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2NDQ5MDgsIm5iZiI6MTcxNTY0NDYwOCwicGF0aCI6Ii8xMDg3NzA2OTIvMzMwMTQxMDYzLTUwYTg4ODg0LTVhMWQtNDkyNC1hOGU4LWNlNDg4ZjAwODhjOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxM1QyMzU2NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZDU0OWE4MDgwZjkyN2M4OWNjMjVmZWY0NDBjMGU5ODFmOTczMDRhMzYwMTJjMDg0ODlmODk4NzU5MDJmODRhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.r1DWb_OEf2lykRCkNpDRxrZflCjVaT9gQM5SW83bYDI"> 这样连接~~不知道怎么改这个节点的名字，只能直接用电线连接
> 
> > <img alt="image" width="54.140625" height="21" src="https://private-user-images.githubusercontent.com/108770692/330141063-50a88884-5a1d-4924-a8e8-ce488f0088c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2NDQ5MDgsIm5iZiI6MTcxNTY0NDYwOCwicGF0aCI6Ii8xMDg3NzA2OTIvMzMwMTQxMDYzLTUwYTg4ODg0LTVhMWQtNDkyNC1hOGU4LWNlNDg4ZjAwODhjOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxM1QyMzU2NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZDU0OWE4MDgwZjkyN2M4OWNjMjVmZWY0NDBjMGU5ODFmOTczMDRhMzYwMTJjMDg0ODlmODk4NzU5MDJmODRhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.r1DWb_OEf2lykRCkNpDRxrZflCjVaT9gQM5SW83bYDI"> Connect like this~~ I don't know how to change the name of this node, so I can only connect it directly with a wire <img alt="image" width="54.140625" height="21" src="https://private-user-images.githubusercontent.com/108770692/330141063-50a88884-5a1d-4924-a8e8-ce488f0088c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2NDQ5MDgsIm5iZiI6MTcxNTY0NDYwOCwicGF0aCI6Ii8xMDg3NzA2OTIvMzMwMTQxMDYzLTUwYTg4ODg0LTVhMWQtNDkyNC1hOGU4LWNlNDg4ZjAwODhjOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxM1QyMzU2NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZDU0OWE4MDgwZjkyN2M4OWNjMjVmZWY0NDBjMGU5ODFmOTczMDRhMzYwMTJjMDg0ODlmODk4NzU5MDJmODRhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.r1DWb_OEf2lykRCkNpDRxrZflCjVaT9gQM5SW83bYDI"> 这样连接~~不知道怎么改这个节点的名字，只能直接用电线连接
> 
> Why did you chnaged the workflow? It's not working well on this modified one你为什么要修改工作流程？它在这个修改后的版本上效果不佳
After figuring out how to put the generated image into the PS layer, I'll take a look at how to output each different process to the PS node, so far I feel that the plugin you wrote is better than the previous Comfyui PS, both in terms of UI design and the way of using it!!!

**Comment by locsmax** [comment]
https://github.com/NimaNzrii/comfyui-photoshop/issues/85#issuecomment-2152149278

**Comment by NimaNzrii** [comment]
# Fixed in V1.5.0 ✨
this problem should be fixed in ver 1.5.0
please update plugin and the node and let me know if it helped
