### ISSUE TITLE
FR: Random button

### ISSUE THREAD

**Issue by noembryo** [NimaNzrii/comfyui-photoshop#33]
Just a feature request for the lazy between us..
A small random button next to the "Render".
Because I keep pressing the "Star" button and then the randomize until I get a satisfying render.
We can cut these clicks in half! 🎆 🍾 🥳

**Comment by NimaNzrii** [comment]
I will figure out a way for it
Thanks for your ux advice

Actually i did it on my pre realeaed version 😂❤️
But for some reason deleted

**Comment by noembryo** [comment]
> But for some reason deleted

It happens all the time, isn't it.. 😄

**Comment by zxtmzxtm** [comment]
There is no change in the image, why is that?
![ComfyUI_temp_eybnl_00003_](https://github.com/NimaNzrii/comfyui-photoshop/assets/166407992/3f55ec1d-1bd8-404f-a723-473d33819bf2)

![ComfyUI_temp_eybnl_00003_](https://github.com/NimaNzrii/comfyui-photoshop/assets/166407992/23f538ff-a8ba-4464-948e-ad91508e5f80)
