### ISSUE TITLE
please lead me to make things works

### ISSUE THREAD

**Issue by lightshepherd** [NimaNzrii/comfyui-photoshop#35]
Hai thanks for make this plugin happen, i can't wait to try it, but i got some problems, i'm already install the requirement files, and also the photoshop plugin, enable remote connections and put 12341234 as password

first i launch my PS 2024 then run main.py to start comfyui, 
place image on the layer then select img2img and placing prompt and hit render

and got this line  on cmd :

Starting server

To see the GUI go to: http://127.0.0.1:8188
_PS_ Photoshop launched('127.0.0.1', 50317)
_PS_ comfyUi Not Connected
FETCH DATA from: D:\comfy ui\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json
_PS_ Photoshop node added('127.0.0.1', 50334)
got prompt
Failed to validate prompt for output 1157:
* ImageResize+ 1677:5:
  - Value not in list: interpolation: 'True' not in ['nearest', 'bilinear', 'bicubic', 'area', 'nearest-exact', 'lanczos']
  - Value not in list: condition: 'lanczos' not in ['always', 'downscale if bigger', 'upscale if smaller']
Output will be ignored
Failed to validate prompt for output 1428:
* CheckpointLoaderSimple 1074:
  - Value not in list: ckpt_name: 'epicrealism_naturalSinRC1VAE_2.safetensors' not in ['LCM_Dreamshaper_v7_4k.safetensors', 'epicrealism_naturalSinRC1VAE.safetensors', 'epicrealism_pureEvolutionV5-inpainting.safetensors', 'juggernautXL_v8Rundiffusion.safetensors', 'realismEngineSDXL_v30VAE.safetensors']
* LoraLoader 1392:
  - Value not in list: lora_name: 'lcm\SD1.5\pytorch_lora_weights.safetensors' not in ['add_detail.safetensors', 'balloonz-sdxl.safetensors', 'lcm-lora-sdv1-5.safetensors', 'lcm-lora-sdxl.safetensors', 'pytorch_lora_weights.safetensors']
* SDXLPromptStyler 1677:4:
  - Value not in list: log_prompt: 'False' not in ['No', 'Yes']
Output will be ignored
Failed to validate prompt for output 1661:
Output will be ignored
[rgthree] Using rgthree's optimized recursive execution.
[rgthree] First run patching recursive_output_delete_if_changed and recursive_will_execute.
[rgthree] Note: If execution seems broken due to forward ComfyUI changes, you can disable the optimization from rgthree settings in ComfyUI.
!!! Exception during processing!!! 'NoneType' object has no attribute 'lower'
Traceback (most recent call last):
  File "D:\comfy ui\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "D:\comfy ui\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "D:\comfy ui\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "D:\comfy ui\ComfyUI\nodes.py", line 516, in load_checkpoint
    out = comfy.sd.load_checkpoint_guess_config(ckpt_path, output_vae=True, output_clip=True, embedding_directory=folder_paths.get_folder_paths("embeddings"))
  File "D:\comfy ui\ComfyUI\comfy\sd.py", line 446, in load_checkpoint_guess_config
    sd = comfy.utils.load_torch_file(ckpt_path)
  File "D:\comfy ui\ComfyUI\comfy\utils.py", line 13, in load_torch_file
    if ckpt.lower().endswith(".safetensors"):
AttributeError: 'NoneType' object has no attribute 'lower'

Prompt executed in 0.53 seconds
got prompt
Failed to validate prompt for output 1157:
* ImageResize+ 1677:5:
  - Value not in list: interpolation: 'True' not in ['nearest', 'bilinear', 'bicubic', 'area', 'nearest-exact', 'lanczos']
  - Value not in list: condition: 'lanczos' not in ['always', 'downscale if bigger', 'upscale if smaller']
Output will be ignored
Failed to validate prompt for output 1428:
* CheckpointLoaderSimple 1074:
  - Value not in list: ckpt_name: 'epicrealism_naturalSinRC1VAE_2.safetensors' not in ['LCM_Dreamshaper_v7_4k.safetensors', 'epicrealism_naturalSinRC1VAE.safetensors', 'epicrealism_pureEvolutionV5-inpainting.safetensors', 'juggernautXL_v8Rundiffusion.safetensors', 'realismEngineSDXL_v30VAE.safetensors']
* LoraLoader 1392:
  - Value not in list: lora_name: 'lcm\SD1.5\pytorch_lora_weights.safetensors' not in ['add_detail.safetensors', 'balloonz-sdxl.safetensors', 'lcm-lora-sdv1-5.safetensors', 'lcm-lora-sdxl.safetensors', 'pytorch_lora_weights.safetensors']
* SDXLPromptStyler 1677:4:
  - Value not in list: log_prompt: 'False' not in ['No', 'Yes']
Output will be ignored
Failed to validate prompt for output 1661:
Output will be ignored
[rgthree] Using rgthree's optimized recursive execution.
!!! Exception during processing!!! 'NoneType' object has no attribute 'lower'
Traceback (most recent call last):
  File "D:\comfy ui\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "D:\comfy ui\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "D:\comfy ui\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "D:\comfy ui\ComfyUI\nodes.py", line 516, in load_checkpoint
    out = comfy.sd.load_checkpoint_guess_config(ckpt_path, output_vae=True, output_clip=True, embedding_directory=folder_paths.get_folder_paths("embeddings"))
  File "D:\comfy ui\ComfyUI\comfy\sd.py", line 446, in load_checkpoint_guess_config
    sd = comfy.utils.load_torch_file(ckpt_path)
  File "D:\comfy ui\ComfyUI\comfy\utils.py", line 13, in load_torch_file
    if ckpt.lower().endswith(".safetensors"):
AttributeError: 'NoneType' object has no attribute 'lower'

Prompt executed in 0.06 seconds

need your guidance, thanks

**Comment by NimaNzrii** [comment]
Hi , it seems your workflow is a little bit old

 please download the latest version of the workflow over here:
https://openart.ai/workflows/-/-/lreWarJbqiYPcDXnD8hh#comment-2WOMOf3kiWzTLGWYGdFu

You are getting an error on the sdxl promptstyler which has been removed from the workflow since it made some issues  like this

**Comment by lightshepherd** [comment]
i try to update with new workflow but still got problem, then i try to check this list on your openart.ai
![node list](https://github.com/NimaNzrii/comfyui-photoshop/assets/153082813/cae09365-30ac-48e3-8f33-24f3f9bf024e)

then try to install costume nodes, then somehow it worked now, thanks
