### ISSUE TITLE
 (IMPORT FAILED) comfyui-photoshop

### ISSUE THREAD

**Issue by eflin1** [NimaNzrii/comfyui-photoshop#36]
trough manager    installed the plugin,   and its listed as installed , however    workflow shows  Plugin not installed.
I tried the  "Try Fix" but it tells me "Import Failed "

**Comment by NimaNzrii** [comment]
# Fixed ✨

Thank you for your report.💖
Please update the **Comfyui-Photoshop** node inside you **comfyui manager**

and let me know if you had any trouble on running it
