### ISSUE TITLE
Import Failed

### ISSUE THREAD

**Issue by magejosh** [NimaNzrii/comfyui-photoshop#4]
I keep seeing module not found 'Photoshop' in the terminal and import failed on this node. I removed almost all other custom nodes except those required by the workflow from your video. Not sure what i'm doing wrong.

  File "D:\GitHub\ComfyUI\custom_nodes\comfyui-photoshop\photoshop.py", line 6, in <module>
    from photoshop import PhotoshopConnection
ModuleNotFoundError: No module named 'photoshop'

Cannot import D:\GitHub\ComfyUI\custom_nodes\comfyui-photoshop module for custom nodes: No module named 'photoshop'

**Comment by NimaNzrii** [comment]
Could you please take a picture of sitemap folder inside of you embed python?

**Comment by magejosh** [comment]
Yeah, that's likely the culprit and makes sense. I just removed the other custom nodes but didn't clean the venv i'm using. I'll give that a shot and report results.

**Comment by magejosh** [comment]
![image](https://github.com/NimaNzrii/comfyui-photoshop/assets/76418140/74def9f9-a1e8-4faf-9865-c1cc51abdb46)
Well deleted my venv, created a new one, installed correct torch for cuda11.8 on my windows 10 pc. Still getting that same import photoshop error. 
![image](https://github.com/NimaNzrii/comfyui-photoshop/assets/76418140/fc1699a7-f727-4415-8203-35e47e771975)

**Comment by d23lygjdpzok** [comment]
我的问题跟你一样
