### ISSUE TITLE
PS plug-in related issues and failed to obtain comfyui node information

### ISSUE THREAD

**Issue by bubbl000** [NimaNzrii/comfyui-photoshop#40]
1‘ps: Try to left-click, right-click and drag, but you can't put the picture into the canvas
2’In comfyui, you can't read the mask picture, width and height, and the information of the slider, and the prompt word can be read

ps2023

**Comment by bubbl000** [comment]
![image](https://github.com/NimaNzrii/comfyui-photoshop/assets/108770692/964aff22-921d-4c5e-a749-659e9c9dce45)

**Comment by bubbl000** [comment]
The width and length may have become 512 because the canvas information is not available

**Comment by NimaNzrii** [comment]
# Fixed in V1.5.0 ✨
this problem should be fixed in ver 1.5.0
please update plugin and the node and let me know if it helped
