### ISSUE TITLE
MacBook (IMPORT FAILED)

### ISSUE THREAD

**Issue by ebigtm** [NimaNzrii/comfyui-photoshop#42]
Hi Im on mac M3 and everything is installed but your custom node refuses to be imported, tried to download it from the git but nothing helps, any ideas?

**Comment by NimaNzrii** [comment]
Could you please send me your log file?

**Comment by ebigtm** [comment]
you are awesome thanks for the quick reply :)
[comfyui.log](https://github.com/NimaNzrii/comfyui-photoshop/files/15287768/comfyui.log)
here it is , thanks again!

**Comment by NimaNzrii** [comment]
# Fixed in V1.5.0 ✨
this problem should be fixed in ver 1.5.0
please update plugin and the node and let me know if it helped
