### ISSUE TITLE
just a white output in photoshop!

### ISSUE THREAD

**Issue by kotaxyz** [NimaNzrii/comfyui-photoshop#49]
hello there ,thanks alot for your efforts for making this awesome tool !
i have some issues regarding using it when i use it in photoshop it only outputs white image the only tab working is text2img also send to layer dosnt work i dont have any issues in the comfyui log , i recorded a vid showing the issue 

https://github.com/NimaNzrii/comfyui-photoshop/assets/105466290/e96b05dd-d8ae-48d3-99d1-2ed87470d94d

**Comment by NimaNzrii** [comment]
Hi , please send a screenshot from your ComfyUi

**Comment by NimaNzrii** [comment]
# Fixed in V1.5.0 ✨
this problem should be fixed in ver 1.5.0
please update plugin and the node and let me know if it helped
