### ISSUE TITLE
Denoise slider doesn't work

### ISSUE THREAD

**Issue by matroxI** [NimaNzrii/comfyui-photoshop#51]
Currently I am using Adobe Photoshop Version: 25.6.0 20240312.r.433 2bfcbf1 x64
And changing the slider on the right (responsible for Denoise, as I understand it) does not change anything.

_Originally posted by @matroxI in https://github.com/NimaNzrii/comfyui-photoshop/issues/47#issuecomment-2109588534_

**Comment by bubbl000** [comment]
How to put the image on the ps plug-in into the ps layer？

**Comment by NimaNzrii** [comment]
# Fixed in V1.5.0 ✨
this problem should be fixed in ver 1.5.0
please update plugin and the node and let me know if it helped
