### ISSUE TITLE
ComfyUI & Photoshop not connecting

### ISSUE THREAD

**Issue by keyvvision** [NimaNzrii/comfyui-photoshop#53]
I have configured everything as per the tutorial but it seems that the system cannot recognise the plugin installed on Photoshop even If it get started as it should, I always have this error popping out:

Error occurred when executing 🔹Photoshop ComfyUI Plugin: Failed to load directory after 5 attempts. 🔴 Make sure you have installed and started the Photoshop Plugin Succesfully. 🔴 otherwise you can restart your photosop and your plugin to Fix this problem File "/Users/christopheregbutu/AI/ComfyUI/execution.py", line 151, in recursive_execute output_data, output_ui = get_output_data(obj, input_data_all) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/Users/christopheregbutu/AI/ComfyUI/execution.py", line 81, in get_output_data return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/Users/christopheregbutu/AI/ComfyUI/execution.py", line 74, in map_node_over_list results.append(getattr(obj, func)(**slice_dict(input_data_all, i))) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/Users/christopheregbutu/AI/ComfyUI/custom_nodes/comfyui-photoshop/node-Photoshop.py", line 33, in PS_Execute self.loadConfig() File "/Users/christopheregbutu/AI/ComfyUI/custom_nodes/comfyui-photoshop/node-Photoshop.py", line 75, in loadConfig self.loadConfig(retry_count + 1) File "/Users/christopheregbutu/AI/ComfyUI/custom_nodes/comfyui-photoshop/node-Photoshop.py", line 75, in loadConfig self.loadConfig(retry_count + 1) File "/Users/christopheregbutu/AI/ComfyUI/custom_nodes/comfyui-photoshop/node-Photoshop.py", line 75, in loadConfig self.loadConfig(retry_count + 1) [Previous line repeated 1 more time] File "/Users/christopheregbutu/AI/ComfyUI/custom_nodes/comfyui-photoshop/node-Photoshop.py", line 77, in loadConfig raise Exception("Failed to load directory after 5 attempts. \n 🔴 Make sure you have installed and started the Photoshop Plugin Succesfully. \n 🔴 otherwise you can restart your photosop and your plugin to Fix this problem")

Can please someone help me? Thanks

**Comment by mancin87** [comment]
same here mbp m1, sonoma 14.1 photoshop 25.7

**Comment by maagi** [comment]
Same here. MacBookPro M1 Sonoma 142.1 Photoshop 25.9.0 / Photoshop Beta 25.10.0

**Comment by NimaNzrii** [comment]
# Fixed in V1.5.0 ✨
this problem should be fixed in ver 1.5.0
please update plugin and the node and let me know if it helped
