### ISSUE TITLE
Help please 

### ISSUE THREAD

**Issue by Michael2Miller** [NimaNzrii/comfyui-photoshop#55]
To be honest with you ai am using a cracked version of Photoshop because i can't afford to pay for a subscription 
Can I use this method and would it work,  I'm talking about the connection between comfy UI and Photoshop
If it's not I wish if you can find a solution for those who can't afford to pay for Photoshop subscription

**Comment by NimaNzrii** [comment]
yes you can do it
just login to your adobe creative cloud ( you will not get banned )
and then install the ccx file using zxp uxp installer

somebody did it before you and it worked

**Comment by Michael2Miller** [comment]
I tried a lot but I couldn't download the workflow from open art website, I wish if you can put it here on github or if you can guide me how to download it it would be great thank you for your fast replying

**Comment by noembryo** [comment]
> just login to your adobe creative cloud ( you will not get banned )
> and then install the ccx file using zxp uxp installer

You can also extract the contents of the ccx (it's just a zip file with a different extension) in, a let's say "ComfyUI for Photoshop"  folder, and move this folder to your Photoshop's "Plugins" folder..

**Comment by NimaNzrii** [comment]
> > just login to your adobe creative cloud ( you will not get banned )
> > and then install the ccx file using zxp uxp installer
> 
> You can also extract the contents of the ccx (it's just a zip file with a different extension) in, a let's say "ComfyUI for Photoshop" folder, and move this folder to your Photoshop's "Plugins" folder..

you are a copy version of me :))))))) thank you for all of your answers

**Comment by NimaNzrii** [comment]
# Fixed in V1.5.0 ✨
this problem should be fixed in ver 1.5.0
please update plugin and the node and let me know if it helped
