### ISSUE TITLE
Connection problem

### ISSUE THREAD

**Issue by Michael2Miller** [NimaNzrii/comfyui-photoshop#57]
I have a question I tried a lot to connect Photoshop to comfy ui but I couldn't
Notice: I'm using comfy ui on kaggle Jupiter notebooks
Is there a way to connect it together I mean Photoshop on my local computer and comfy on kaggle Jupiter notebook?

**Comment by cardenluo** [comment]
it can get picture from PS, but not send bact to PS ; could you give me some sugesstion.
![image](https://github.com/NimaNzrii/comfyui-photoshop/assets/133877069/87960861-eb30-4365-8e04-d11b94d5dd5d)
Prompt executed in 2.24 seconds
_PS_ Photoshop Not Connected
_PS_ Photoshop Not Connected
got prompt
Failed to validate prompt for output 4:
* (prompt):
  - Required input is missing: mask
* MaskPreview+ 4:
  - Required input is missing: mask
Output will be ignored
[rgthree] Using rgthree's optimized recursive execution.
_PS_ Photoshop Not Connected
Prompt executed in 0.31 seconds
_PS_ Photoshop Not Connected
got prompt
[rgthree] Using rgthree's optimized recursive execution.
_PS_ Photoshop Not Connected
Prompt executed in 0.24 seconds
_PS_ Photoshop Not Connected
got prompt
[rgthree] Using rgthree's optimized recursive execution.
_PS_ Photoshop Not Connected
Prompt executed in 0.24 seconds
_PS_ Photoshop Not Connected

**Comment by cardenluo** [comment]
![image](https://github.com/NimaNzrii/comfyui-photoshop/assets/133877069/4f61386e-6b60-46fa-af4e-e49127f05a26)

**Comment by cardenluo** [comment]
i change the code to match the port, but  the port will change  again after run.
![image](https://github.com/NimaNzrii/comfyui-photoshop/assets/133877069/8bfaa267-d8f6-4ab7-88b7-d84fc5fbb813)

**Comment by bubbl000** [comment]
What is your Photoshop version? Why can't my Photoshop get pictures

**Comment by bubbl000** [comment]
> it can get picture from PS, but not send bact to PS ; could you give me some sugesstion.它可以从 PS 获取图片，但不能将 bact 发送到 PS ;你能给我一些建议吗？ ![image](https://private-user-images.githubusercontent.com/133877069/331649289-87960861-eb30-4365-8e04-d11b94d5dd5d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5NzczNTcsIm5iZiI6MTcxNTk3NzA1NywicGF0aCI6Ii8xMzM4NzcwNjkvMzMxNjQ5Mjg5LTg3OTYwODYxLWViMzAtNDM2NS04ZTA0LWQxMWI5NGQ1ZGQ1ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxN1QyMDE3MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMjUxZjE0OGZjOGY5MTlhZTg0NjI5MjMxYzY1Mjc3NzM4ZGJlZThmZDkzYThlYjkzZjViZWVlYjcwODdhZmE4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1Q4TcGZcNl1sS42tWKry3mYnFUOrCpBvMcyznLQCz18) Prompt executed in 2.24 seconds提示在 2.24 秒内执行 _PS_ Photoshop Not ConnectedPS Photoshop 未连接 _PS_ Photoshop Not ConnectedPS Photoshop 未连接 got prompt 得到提示 Failed to validate prompt for output 4:无法验证输出 4 的提示：
> 
> * (prompt):
>   
>   * Required input is missing: mask
> * MaskPreview+ 4:
>   
>   * Required input is missing: mask缺少必需的输入：掩码
>     Output will be ignored输出将被忽略
>     [rgthree] Using rgthree's optimized recursive execution.[RG三]使用 rgthree 优化的递归执行。
>     _PS_ Photoshop Not ConnectedPS Photoshop 未连接
>     Prompt executed in 0.31 seconds提示在 0.31 秒内执行
>     _PS_ Photoshop Not ConnectedPS Photoshop 未连接
>     got prompt 得到提示
>     [rgthree] Using rgthree's optimized recursive execution.[RG三]使用 rgthree 优化的递归执行。
>     _PS_ Photoshop Not ConnectedPS Photoshop 未连接
>     Prompt executed in 0.24 seconds提示在 0.24 秒内执行
>     _PS_ Photoshop Not ConnectedPS Photoshop 未连接
>     got prompt 得到提示
>     [rgthree] Using rgthree's optimized recursive execution.[RG三]使用 rgthree 优化的递归执行。
>     _PS_ Photoshop Not ConnectedPS Photoshop 未连接
>     Prompt executed in 0.24 seconds提示在 0.24 秒内执行
>     _PS_ Photoshop Not ConnectedPS Photoshop 未连接

What is your Photoshop version? Why can't my Photoshop get pictures

**Comment by cardenluo** [comment]
ps 25.6

F:\ComfyUI_Windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-05-18 15:02:01.466907
** Platform: Windows
** Python version: 3.11.8 (tags/v3.11.8:db85d51, Feb  6 2024, 22:03:32) [MSC v.1937 64 bit (AMD64)]
