### ISSUE TITLE
Group control cannot be loaded, how to solve this problem

### ISSUE THREAD

**Issue by rong7932** [NimaNzrii/comfyui-photoshop#61]
![12](https://github.com/NimaNzrii/comfyui-photoshop/assets/61302333/078b467a-6ba3-4b2c-a574-ea04a905d988)

Group control cannot be loaded, how to solve this problem

**Comment by noembryo** [comment]
If the ComfyUI is finished loading, and you have a browser tab open with it, try to refresh it (press F5).
This help me on some occasions..

**Comment by rong7932** [comment]
> If ComfyUI has finished loading, and you have a browser tab open, try refreshing it (press F5). This has helped me in some cases.

Refreshing, reloading, etc. doesn't work

**Comment by NimaNzrii** [comment]
Your problem is on connecting your ps or comfy to the Back-End

Which with the new changes it should be fix on next version

I will dm you after realease

**Comment by NimaNzrii** [comment]
# Fixed in V1.5.0 ✨
this problem should be fixed in ver 1.5.0
please update plugin and the node and let me know if it helped
