### ISSUE TITLE
FR: Snap preview window

### ISSUE THREAD

**Issue by noembryo** [NimaNzrii/comfyui-photoshop#62]
Just a small convenient feature request.
When resizing the preview window of the plugin inside Photoshop, it will help if it snapped in the correct ratio, if it got really close to it.
Just putting it here as an issue for a todo reference.. 😉

**Comment by NimaNzrii** [comment]
i want to send you the new version to you for test.
can you send me your email address if you want?

i already add this feature for next ver

**Comment by noembryo** [comment]
noembryo@gmail.com

**Comment by NimaNzrii** [comment]
im actually trying to find some users to test the new version

because of the huge changes in the backend for performance boosting

if u want i would be so happy to send you
just send me your email if you agree to test the beta ver

**Comment by noembryo** [comment]
> if u want i would be so happy to send you
> just send me your email if you agree to test the beta ver

I already wrote my email a couple of messages back, and after some time I edit it out (for the fear of spammer bots)
It's still in the edit history and in you email notifications from GitHub.
If you like I can re-write it.. 😃

**Comment by NimaNzrii** [comment]
oh sorry i didnt know about this limitation

you can fill this form then:
https://forms.gle/Qg7TN9zk5r3q4zSL8

**Comment by noembryo** [comment]
Any news?
