### ISSUE TITLE
Problems encountered and suggestions

### ISSUE THREAD

**Issue by rong7932** [NimaNzrii/comfyui-photoshop#67]
This is an excellent plugin! Thank you for creating and providing it! In the future, more and more people will like and use it. At least for me, a post-production photographer, it is tremendously helpful! I believe that with continuous optimization, it will greatly improve my work efficiency! Your workflow has some connection issues, but this is not a big problem, as I can reconnect them myself. However, the plugin currently encounters the following issues:

Issue 1: Photoshop and ComfyUI successfully link, but the green, blue, and disabled group functions cannot be loaded, making it impossible to switch in Photoshop. I hope this can be resolved promptly!

Issue 2: The Photoshop plugin's prompt text input box cannot input non-English characters because when typing in other languages, the window automatically hides the input box, which seems to be an animation bug. Although you can paste other language texts into it, it still cannot transmit non-English text information to ComfyUI. (For example, I am from China, and my English is not very good, so I habitually input Chinese and add text translation nodes in my workflow to improve efficiency. Because of this, I discovered that even when I paste Chinese into the Photoshop plugin and click transmit, ComfyUI receives an empty input without content and cannot transmit non-English text!)

Issue 3: This should be considered a personal suggestion. It feels like more input options from KSampler could be integrated into the plugin. Maybe your workflow doesn't use these inputs, like steps, scheduler, and sampler, as they might already be fixed in your workflow. However, if the plugin could include these inputs, it would offer more choices and make it more convenient for users to customize their workflows. Providing input interfaces would leave the use of these options to the user's discretion. One last suggestion is to separate the input and image output areas in the plugin for better convenience. (For example, clicking Randomize in the PS plugin currently covers the image output window, which affects the experience. I have made a simple interface for reference, hoping it can be helpful. I mean no offense; I just really like your plugin and want to offer some suggestions for improvement. I hope it becomes even better!)

![11](https://github.com/NimaNzrii/comfyui-photoshop/assets/61302333/3c872593-5c27-4a02-9955-96715c0fe3a4)
![22](https://github.com/NimaNzrii/comfyui-photoshop/assets/61302333/8f960bd5-1876-42c9-bfa0-54fc9894416f)

**Comment by NimaNzrii** [comment]
I am very happy to have professional users like you.  Your every word will affect the next update, I read all the messages and included almost all the user requests in the next version, it is now in the testing stage, the changes you requested for the UI are a bit complicated, so this update  It is applied in a different way, definitely, more accessible and more professional.  Considering your level of professionalism and your expectations, I think you will be very surprised for the next update.

**Comment by Ahcool123** [comment]
> I am very happy to have professional users like you. Your every word will affect the next update, I read all the messages and included almost all the user requests in the next version, it is now in the testing stage, the changes you requested for the UI are a bit complicated, so this update It is applied in a different way, definitely, more accessible and more professional. Considering your level of professionalism and your expectations, I think you will be very surprised for the next update.

The author's Photoshop plugin interface is impressively minimalistic, and I absolutely love it. So much so that I tried to express my gratitude by buying them a coffee through a donation website, only to find out that it doesn't accommodate payments from China. I sincerely wish the author would consider uploading their YouTube content onto Bilibili, China's equivalent of YouTube. Doing so could significantly expand your Chinese audience, and rest assured, I'm eager to support you financially in any way I can.

**Comment by rong7932** [comment]
> 我很高兴有像您这样的专业用户。你的每一个字都会影响下一次更新，我阅读了所有的消息，并在下一个版本中包含了几乎所有的用户请求，现在处于测试阶段，您请求的 UI 更改有点复杂，所以这次更新它以不同的方式应用，当然，更易于访问和更专业。考虑到您的专业水平和期望，我想您会对下一次更新感到非常惊讶。

Looking forward to your next releases and be the first to be notified

**Comment by bubbl000** [comment]
![image](https://github.com/NimaNzrii/comfyui-photoshop/assets/108770692/ccf2912a-b1aa-4598-a6e2-098280f2c638)
I think the deleted part can not be displayed in the ps plug-in, after all, when we use ps, the process has already been debutted in comfyui, in this case, we will focus more on the operation in ps rather than debugging the value. Perhaps in ps more just re-perform the build or change the weights and the rest of the complex operations can be done entirely in comfyui

**Comment by bubbl000** [comment]
> This is an excellent plugin! Thank you for creating and providing it! In the future, more and more people will like and use it. At least for me, a post-production photographer, it is tremendously helpful! I believe that with continuous optimization, it will greatly improve my work efficiency! Your workflow has some connection issues, but this is not a big problem, as I can reconnect them myself. However, the plugin currently encounters the following issues:这是一个很棒的插件！感谢您创建并提供它！未来，将会有越来越多的人喜欢并使用它。至少对于我这个后期摄影师来说，这是非常有帮助的！相信随着不断的优化，一定会大大提高我的工作效率！您的工作流程存在一些连接问题，但这不是一个大问题，因为我可以自己重新连接它们。然而，该插件目前遇到以下问题：
> 
> Issue 1: Photoshop and ComfyUI successfully link, but the green, blue, and disabled group functions cannot be loaded, making it impossible to switch in Photoshop. I hope this can be resolved promptly!
> 
> Issue 2: The Photoshop plugin's prompt text input box cannot input non-English characters because when typing in other languages, the window automatically hides the input box, which seems to be an animation bug. Although you can paste other language texts into it, it still cannot transmit non-English text information to ComfyUI. (For example, I am from China, and my English is not very good, so I habitually input Chinese and add text translation nodes in my workflow to improve efficiency. Because of this, I discovered that even when I paste Chinese into the Photoshop plugin and click transmit, ComfyUI receives an empty input without content and cannot transmit non-English text!)
> 
> Issue 3: This should be considered a personal suggestion. It feels like more input options from KSampler could be integrated into the plugin. Maybe your workflow doesn't use these inputs, like steps, scheduler, and sampler, as they might already be fixed in your workflow. However, if the plugin could include these inputs, it would offer more choices and make it more convenient for users to customize their workflows. Providing input interfaces would leave the use of these options to the user's discretion. One last suggestion is to separate the input and image output areas in the plugin for better convenience. (For example, clicking Randomize in the PS plugin currently covers the image output window, which affects the experience. I have made a simple interface for reference, hoping it can be helpful. I mean no offense; I just really like your plugin and want to offer some suggestions for improvement. I hope it becomes even better!)
> 
> ![11](https://private-user-images.githubusercontent.com/61302333/332104062-3c872593-5c27-4a02-9955-96715c0fe3a4.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzNTM2MDgsIm5iZiI6MTcxNjM1MzMwOCwicGF0aCI6Ii82MTMwMjMzMy8zMzIxMDQwNjItM2M4NzI1OTMtNWMyNy00YTAyLTk5NTUtOTY3MTVjMGZlM2E0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIyVDA0NDgyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyNGZkMTY0NmRjNGZmYjkxMTI2ZjkzOGQzNzUxNzYzZmQ0Yzg4MjJmMTRlZmIzZjEwNTk0NGQ3NDYxZmU5ZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wk8PyUDDUOcEAo_tChDdrfXzdOPSFZgL6QRMaAekS88) ![22](https://private-user-images.githubusercontent.com/61302333/332104083-8f960bd5-1876-42c9-bfa0-54fc9894416f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzNTM2MDgsIm5iZiI6MTcxNjM1MzMwOCwicGF0aCI6Ii82MTMwMjMzMy8zMzIxMDQwODMtOGY5NjBiZDUtMTg3Ni00MmM5LWJmYTAtNTRmYzk4OTQ0MTZmLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIyVDA0NDgyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyMjIyOGRlMTk4NzQyYjM2M2QyNDZkYjhhMjcyMmVjMjQyNDYxOGI5NmQ4MzFiODJmNjY2ZWQyNTdlYmFmYTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mqZIihp6cKouD2YwwIQSBWUQh-WhjmUPDd1VxVFy7nk)

老大！！你的ps可以接收到预设吗 我用的是ps25.0版本的不能接收到预设

**Comment by rong7932** [comment]
> > This is an excellent plugin! Thank you for creating and providing it! In the future, more and more people will like and use it. At least for me, a post-production photographer, it is tremendously helpful! I believe that with continuous optimization, it will greatly improve my work efficiency! Your workflow has some connection issues, but this is not a big problem, as I can reconnect them myself. However, the plugin currently encounters the following issues:这是一个很棒的插件！感谢您创建并提供它！未来，将会有越来越多的人喜欢并使用它。至少对于我这个后期摄影师来说，这是非常有帮助的！相信随着不断的优化，一定会大大提高我的工作效率！您的工作流程存在一些连接问题，但这不是一个大问题，因为我可以自己重新连接它们。然而，该插件目前遇到以下问题：
> > Issue 1: Photoshop and ComfyUI successfully link, but the green, blue, and disabled group functions cannot be loaded, making it impossible to switch in Photoshop. I hope this can be resolved promptly!
> > Issue 2: The Photoshop plugin's prompt text input box cannot input non-English characters because when typing in other languages, the window automatically hides the input box, which seems to be an animation bug. Although you can paste other language texts into it, it still cannot transmit non-English text information to ComfyUI. (For example, I am from China, and my English is not very good, so I habitually input Chinese and add text translation nodes in my workflow to improve efficiency. Because of this, I discovered that even when I paste Chinese into the Photoshop plugin and click transmit, ComfyUI receives an empty input without content and cannot transmit non-English text!)
> > Issue 3: This should be considered a personal suggestion. It feels like more input options from KSampler could be integrated into the plugin. Maybe your workflow doesn't use these inputs, like steps, scheduler, and sampler, as they might already be fixed in your workflow. However, if the plugin could include these inputs, it would offer more choices and make it more convenient for users to customize their workflows. Providing input interfaces would leave the use of these options to the user's discretion. One last suggestion is to separate the input and image output areas in the plugin for better convenience. (For example, clicking Randomize in the PS plugin currently covers the image output window, which affects the experience. I have made a simple interface for reference, hoping it can be helpful. I mean no offense; I just really like your plugin and want to offer some suggestions for improvement. I hope it becomes even better!)
> > ![11](https://private-user-images.githubusercontent.com/61302333/332104062-3c872593-5c27-4a02-9955-96715c0fe3a4.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzNTM2MDgsIm5iZiI6MTcxNjM1MzMwOCwicGF0aCI6Ii82MTMwMjMzMy8zMzIxMDQwNjItM2M4NzI1OTMtNWMyNy00YTAyLTk5NTUtOTY3MTVjMGZlM2E0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIyVDA0NDgyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEyNGZkMTY0NmRjNGZmYjkxMTI2ZjkzOGQzNzUxNzYzZmQ0Yzg4MjJmMTRlZmIzZjEwNTk0NGQ3NDYxZmU5ZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wk8PyUDDUOcEAo_tChDdrfXzdOPSFZgL6QRMaAekS88) ![22](https://private-user-images.githubusercontent.com/61302333/332104083-8f960bd5-1876-42c9-bfa0-54fc9894416f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzNTM2MDgsIm5iZiI6MTcxNjM1MzMwOCwicGF0aCI6Ii82MTMwMjMzMy8zMzIxMDQwODMtOGY5NjBiZDUtMTg3Ni00MmM5LWJmYTAtNTRmYzk4OTQ0MTZmLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIyVDA0NDgyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyMjIyOGRlMTk4NzQyYjM2M2QyNDZkYjhhMjcyMmVjMjQyNDYxOGI5NmQ4MzFiODJmNjY2ZWQyNTdlYmFmYTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mqZIihp6cKouD2YwwIQSBWUQh-WhjmUPDd1VxVFy7nk)
> 
> 老大！！你的ps可以接收到预设吗 我用的是ps25.0版本的不能接收到预设

不可以哦，我只是自己搭建可以用的，预设暂时不行，等作者更新

**Comment by 907590629** [comment]
兄弟 能加个v   haike931  请教个问题

**Comment by NimaNzrii** [comment]
## Language Support added✨
update the node and reload the sd1.5 workflow

![Untitled-1](https://github.com/user-attachments/assets/2c069975-0f39-4c6a-a87a-116b9bd58f82)
