### ISSUE TITLE
PHOTOSHOP is not conected to comfyUI,img is not sync to photoshop

### ISSUE THREAD

**Issue by xeusvel** [NimaNzrii/comfyui-photoshop#70]
idont know why img was generated in comfyui,but its not displayed in PHOTOSHOP
![Snipaste_2024-05-23_11-21-58](https://github.com/NimaNzrii/comfyui-photoshop/assets/63448292/599856b0-e798-4cf7-a117-376fca9ded6b)
![Snipaste_2024-05-23_11-21-35](https://github.com/NimaNzrii/comfyui-photoshop/assets/63448292/8c49ac40-ee73-4fdd-9a80-f16d1f5bcff2)

**Comment by Anti-Liang** [comment]
![PS-ComfyUI1](https://github.com/NimaNzrii/comfyui-photoshop/assets/166486868/0917a2ed-55ce-497c-af32-4add32cbd437)
![PS-ComfyUI2](https://github.com/NimaNzrii/comfyui-photoshop/assets/166486868/c0ebe874-7e9f-43f0-9ec1-b3bce2c07ea9)
Excuse me, but maybe same issue here. ComfyUI generated the image but cannot send to PS.
Please tell us how to solve this problem, thank you!

**Comment by xeusvel** [comment]
glad to discuss this amazing plugin,i modified this workflow,check this image,i tried input canvas resolution from PS to back org size node,then send this resized image to send to Photoshop,it worked.

modified detail view

full view

result


so we found this fault seems to be send to photoshop node was not read output image from ksampler correctly,now a not perfect method is modify every workflow just like this way,i dont know how to connect it with a global node to output result,looking foward to the answer from the plugin author.




Song&amp;lana'thel
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "NimaNzrii/comfyui-photoshop"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月23日(星期四) 下午4:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [NimaNzrii/comfyui-photoshop] PHOTOSHOP is not conected to comfyUI,img is not sync to photoshop (Issue #70)





 
PS-ComfyUI1.png (view on web)
 PS-ComfyUI2.png (view on web)
 Excuse me, but maybe same issue here. ComfyUI generated the image but cannot send to PS.
 Please tell us how to solve this problem, thank you!

**Comment by xeusvel** [comment]
glad to discuss this amazing plugin,i modified this workflow,check this image,i tried input canvas resolution from PS to back org size node,then send this resized image to send to Photoshop,it worked.

modified detail view
![=image](https://github.com/NimaNzrii/comfyui-photoshop/assets/63448292/a4ea1562-de08-4f3a-ad4a-da2e9db14035)

full view
![=image (1)](https://github.com/NimaNzrii/comfyui-photoshop/assets/63448292/edac1faa-b1e6-4e14-8480-c55043093275)

result
![=image (2)](https://github.com/NimaNzrii/comfyui-photoshop/assets/63448292/7b6810e0-fe0a-43b2-aed4-9df0e85253f4)

so we found this fault seems to be send to photoshop node was not read output image from ksampler correctly,now a not perfect method is modify every workflow just like this way,i dont know how to connect it with a global node to output result,looking foward to the answer from the plugin author.

**Comment by K-O-N-B** [comment]
I guess this problem is because the "to output node"
![image](https://github.com/NimaNzrii/comfyui-photoshop/assets/152141077/aad11d2a-5df3-4981-8758-0ffc34df8c47)
 the input neme is "output" here, but no output slot in this workflow, we can link the image to "back to org size " node,  but it's not prefect.

and, you can also rename the slot to "Output"
![image](https://github.com/NimaNzrii/comfyui-photoshop/assets/152141077/22f1368d-bc3f-44b6-b73c-2fe664efa203)
but the slot name will reset everytime when you restart the comfyui

and btw, I meet this error,   
![image](https://github.com/NimaNzrii/comfyui-photoshop/assets/152141077/e24206af-e6a4-48fc-a901-36dd9dcf2e09)
hope fix it soon,

**Comment by NimaNzrii** [comment]
# Fixed in V1.5.0 ✨
this problem should be fixed in ver 1.5.0
please update plugin and the node and let me know if it helped
