### ISSUE TITLE
Backend.py:132: RuntimeWarning: coroutine 'sleep' was never awaited

### ISSUE THREAD

**Issue by jafin** [NimaNzrii/comfyui-photoshop#73]
```python
Backend.py:132: RuntimeWarning: coroutine 'sleep' was never awaited
  except H as C:A(e);L.sleep(5)
```

The source looks obfuscated/minimized, so can't really gleam much to help.

**Comment by NimaNzrii** [comment]
# Fixed in V1.5.0 ✨
this problem should be fixed in ver 1.5.0
please update plugin and the node and let me know if it helped
