### ISSUE TITLE
an error for comfyui-photoshop

### ISSUE THREAD

**Issue by chanmis** [NimaNzrii/comfyui-photoshop#76]
When I click render, comfyui reports ![微信图片_20240529182444](https://github.com/NimaNzrii/comfyui-photoshop/assets/163379286/59580042-6668-4eaf-ad16-15e8f78357f6): Loop (1661,1680:4,1680:3) with broadcast (401) - not submitting workflow. Did I miss a step in connecting ps to comfyui?

**Comment by NimaNzrii** [comment]
# Fixed in V1.5.0 ✨
this problem should be fixed in ver 1.5.0
please update plugin and the node and let me know if it helped
