### ISSUE TITLE
Error 'bool' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by barbants** [NimaNzrii/comfyui-photoshop#77]
Hi, I'm getting this message as soon as I press render in photoshop plugin. followed install instructions, pressed "update all" in manager, downloaded models+lora put them in the correct folders, photoshop is connected. I have not tried to do a fresh install of comfyUI yet:

Error occurred when executing ImageResize+:

'bool' object has no attribute 'startswith'

File "C:\Users\deedee\Documents\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\deedee\Documents\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\deedee\Documents\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\deedee\Documents\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_essentials\image.py", line 288, in execute
elif method.startswith('fill'):
^^^^^^^^^^^^^^^^^

AttributeError: 'bool' object has no attribute 'startswith'

![error](https://github.com/NimaNzrii/comfyui-photoshop/assets/170995379/6d0142e8-3a22-488e-b88d-524cdf0e3105)

here i "convert to nodes" on Res Limits node to let you see red nodes:

![error 2](https://github.com/NimaNzrii/comfyui-photoshop/assets/170995379/3a897611-baf0-4f4f-a0f0-88e688ccab32)

Please and thanks, very excited to try this out!

**Comment by barbants** [comment]
Did a fresh install of ComfyUI, switched browser to make sure nothing from before preloaded. 
Followed plugin install instructions. Now it is working, in case anyone get's this error.

**Comment by heyshoosh** [comment]
> Hi, I'm getting this message as soon as I press render in photoshop plugin. followed install instructions, pressed "update all" in manager, downloaded models+lora put them in the correct folders, photoshop is connected. I have not tried to do a fresh install of comfyUI yet:
> 
> Error occurred when executing ImageResize+:
> 
> 'bool' object has no attribute 'startswith'
> 
> File "C:\Users\deedee\Documents\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute output_data, output_ui = get_output_data(obj, input_data_all) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\deedee\Documents\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\deedee\Documents\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list results.append(getattr(obj, func)(**slice_dict(input_data_all, i))) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\deedee\Documents\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_essentials\image.py", line 288, in execute elif method.startswith('fill'): ^^^^^^^^^^^^^^^^^
> 
> AttributeError: 'bool' object has no attribute 'startswith'
> 
> ![error](https://private-user-images.githubusercontent.com/170995379/334773027-6d0142e8-3a22-488e-b88d-524cdf0e3105.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczNTkxOTcsIm5iZiI6MTcxNzM1ODg5NywicGF0aCI6Ii8xNzA5OTUzNzkvMzM0NzczMDI3LTZkMDE0MmU4LTNhMjItNDg4ZS1iODhkLTUyNGNkZjBlMzEwNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMlQyMDA4MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iODhhZmFjYTZjMmRkOTI5ZTdjZDMxMDZiNTg5ZjZiNGI5NGE4MTQ3MTlkYWQ1ZDZkYjQ1ZDdjMmU5YWQ1MjAwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.15hJL3AuDiafxC5NmV4jkdmNPjVp8N-xVdRMdLFzhME)
> 
> here i "convert to nodes" on Res Limits node to let you see red nodes:
> 
> ![error 2](https://private-user-images.githubusercontent.com/170995379/334777927-3a897611-baf0-4f4f-a0f0-88e688ccab32.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczNTkxOTcsIm5iZiI6MTcxNzM1ODg5NywicGF0aCI6Ii8xNzA5OTUzNzkvMzM0Nzc3OTI3LTNhODk3NjExLWJhZjAtNGY0Zi1hMGYwLTg4ZTY4OGNjYWIzMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwMlQyMDA4MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYmI0NDdjYzgyNjgxYTc0NTFhY2JlOWEyM2VmODA3OWMwZDkxNzQ3Yzc5YmJhMzViMWQ4Mzk3MzkxNGRkMDBmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.N58oI4_Vbe2lrhmx1ValVl1fCeIptyhMUGF6aSgY8uU)
> 
> Please and thanks, very excited to try this out!

I'm also getting this error and I have tried doing a complete reinstall using the comfy portable (initially was not using portable).

**Comment by Gogy13** [comment]
> Did a fresh install of ComfyUI, switched browser to make sure nothing from before preloaded. Followed plugin install instructions. Now it is working, in case anyone get's this error.

It's the same problem. I did the above steps several times and each time it did not work

**Comment by wonilmax** [comment]
The error was resolved when I changed the "image resize" method to "stretch".
![cccc](https://github.com/NimaNzrii/comfyui-photoshop/assets/58392645/5c3eaf88-1cf2-472e-9deb-6875021f1c42)

**Comment by heyshoosh** [comment]
> The error was resolved when I changed the "image resize" method to "stretch". ![cccc](https://private-user-images.githubusercontent.com/58392645/337981305-5c3eaf88-1cf2-472e-9deb-6875021f1c42.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc5OTA3OTYsIm5iZiI6MTcxNzk5MDQ5NiwicGF0aCI6Ii81ODM5MjY0NS8zMzc5ODEzMDUtNWMzZWFmODgtMWNmMi00NzJlLTlkZWItNjg3NTAyMWYxYzQyLlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEwVDAzMzQ1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4YmFmMmFlZDFmZDZhZjFhOTA4YTliYjU5ZTAwY2Q3YTY4ODczMGMwZDc2N2U5NjMwOWMzOGZmMjA1MjQ3NTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.b2drPE_z-JO279NQsxMsQguW52oprcNxH97ypPnIFr0)

Ohhhhhhh that works, so does keep proportion, thank you!

**Comment by NimaNzrii** [comment]
please update the node and try to load the workflow using the new button on the node

**Comment by kamijie** [comment]
> The error was resolved when I changed the "image resize" method to "stretch". ![cccc](https://private-user-images.githubusercontent.com/58392645/337981305-5c3eaf88-1cf2-472e-9deb-6875021f1c42.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2MjU2ODYsIm5iZiI6MTcxODYyNTM4NiwicGF0aCI6Ii81ODM5MjY0NS8zMzc5ODEzMDUtNWMzZWFmODgtMWNmMi00NzJlLTlkZWItNjg3NTAyMWYxYzQyLlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE3VDExNTYyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5NTBjNGI1OTgwODViMjgwODI2OGYzZWY5ZGJmOTRhMzg1Y2VjMzc3ZTE3MTA1ZWUyMjkwOGQwYWM1YzI3ZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0eMunOK6nZG9l8TqKZWri7PtvHbQCG7O84Ix6JAr94Q)

it‘s work，thanks

**Comment by hss8692** [comment]
> 当我将“图像调整大小”方法指向“拉伸”时，错误得到了解决。 ![cccc](https://private-user-images.githubusercontent.com/58392645/337981305-5c3eaf88-1cf2-472e-9deb-6875021f1c42.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3NjEwNzAsIm5iZiI6MTcxODc2MDc3MCwicGF0aCI6Ii81ODM5MjY0NS8zMzc5ODEzMDUtNWMzZWFmODgtMWNmMi00NzJlLTlkZWItNjg3NTAyMWYxYzQyLlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE5VDAxMzI1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwYzkxNWJlNjNhNGZmMDFjM2M2NjcxZmE4MTgyMWM2ZDQ3YjAwMmVjZWZiNjU2NWRjZWY1NzFhMmFhZDdkODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cQU_EQQUO4vgqPSJHv-XyOFWUmMuDEZNJhn_1reO8BI)

Thank you. Very useful.

**Comment by lauvis1314** [comment]
> 当我将“图像调整大小”方法更改为“拉伸”时，错误得到解决。 ![cccc](https://private-user-images.githubusercontent.com/58392645/337981305-5c3eaf88-1cf2-472e-9deb-6875021f1c42.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzOTQwMDQsIm5iZiI6MTcxOTM5MzcwNCwicGF0aCI6Ii81ODM5MjY0NS8zMzc5ODEzMDUtNWMzZWFmODgtMWNmMi00NzJlLTlkZWItNjg3NTAyMWYxYzQyLlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI2VDA5MjE0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxMGM2OTFjNjI1ZjlkZTZjY2ExNzQ4NjljOTY2MzliODJmNGEwMGIwMzVlMTg3N2ZlZjk1MTM0ODBjYmE2ZmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.q5V-cK_LlC6nKrmDCQwFHnw0fW_JK3TR-Q6Ckhv6V5w)

感谢，问题得到解决，就按你这样处理
