### ISSUE TITLE
Transparent layer issues

### ISSUE THREAD

**Issue by huacuoni** [NimaNzrii/comfyui-photoshop#78]
Hi author, thanks for the plugin, it's excellent, but I'd like to snap a picture, but after the image compression changes, is it not possible to generate a PNG transparent layer? If I want to generate a transparent layer, what should I do?

**Comment by huacuoni** [comment]
Or can you add a snapshot workflow? After all, keying is a very necessary part of daily work.

**Comment by NimaNzrii** [comment]
# Fixed in V1.5.0 ✨
this problem should be fixed in ver 1.5.0
please update plugin and the node and let me know if it helped
