### ISSUE TITLE
I'm getting problem to install it on Macbook M2 Pro Max. Does it work for Mac?

### ISSUE THREAD

**Issue by fabiotgolo** [NimaNzrii/comfyui-photoshop#8]
Traceback (most recent call last):
  File "/Users/fabiogarcia/pinokio/api/comfyui11.git/app/nodes.py", line 1888, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/fabiogarcia/pinokio/api/comfyui11.git/app/custom_nodes/comfyui-photoshop/__init__.py", line 17, in <module>
    subprocess.run(["python.exe", "-m", "pip", "uninstall", "photoshop"])
  File "/Users/fabiogarcia/pinokio/bin/miniconda/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/Users/fabiogarcia/pinokio/bin/miniconda/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Users/fabiogarcia/pinokio/bin/miniconda/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'python.exe'

Import times for custom nodes:
0.0 seconds (IMPORT FAILED): /Users/fabiogarcia/pinokio/api/comfyui11.git/app/custom_nodes/comfyui-photoshop

**Comment by LorenzoDossi** [comment]
change __init__.py with this code

```
import importlib
import subprocess
# import os

# macOS uses forward slashes for paths. Adjust the path to your needs.
# directory_path = "./ComfyUI/custom_nodes/comfyui-popup_preview"

# Checking and cloning the directory if it doesn't exist. Note: Git must be installed.
# if not os.path.exists(directory_path):
#     print("comfyui-popup_preview installing")
#     subprocess.run(["git", "clone", "https://github.com/NimaNzrii/comfyui-popup_preview.git", directory_path])
#     print("comfyui-popup_preview cloned successfully!")
# else:
#     print("Directory already exists!")

try:
    from photoshop import PhotoshopConnection
except ImportError:
    # On macOS, the Python executable is typically 'python3' if Python 3 is installed.
    # Adjust these commands according to your Python environment setup.
    subprocess.run(["python3", "-m", "pip", "uninstall", "-y", "photoshop"])
    subprocess.run(["python3", "-m", "pip", "uninstall", "-y", "photoshop-connection"])
    subprocess.run(["python3", "-m", "pip", "install", "photoshop-connection"])

node_list = [
    "photoshop"
]

NODE_CLASS_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS = {}

for module_name in node_list:
    # Importing modules dynamically. Ensure the module is in the correct location.
    imported_module = importlib.import_module(".{}".format(module_name), package=__name__)

    NODE_CLASS_MAPPINGS = {**NODE_CLASS_MAPPINGS, **imported_module.NODE_CLASS_MAPPINGS}
    NODE_DISPLAY_NAME_MAPPINGS = {**NODE_DISPLAY_NAME_MAPPINGS, **imported_module.NODE_DISPLAY_NAME_MAPPINGS}

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']

```

**Comment by fabiotgolo** [comment]
Hi there!

This file inside the comfy-photoshop __init__.py ?
If yes, I deleted the code there and I pasted your code, but didn't work.
