### ISSUE TITLE
Photoshop not found error when launching ComfyUI

### ISSUE THREAD

**Issue by RunebinderOG** [NimaNzrii/comfyui-photoshop#80]
Hi,

I've got Adobe Creative Cloud Desktop installed and Photoshop and Photoshop Beta installed, the ComfyUI plugin is installed correctly (not showing any errors at least), but every time I start Comfy this pops up in the Terminal:

_PS_ backend_path D:\ComfyUI\custom_nodes\comfyui-photoshop\Backend.py
_PS_ Backend Started
WARNING: Skipping photoshop as it is not installed.
Found existing installation: photoshop-connection 0.2.0
Uninstalling photoshop-connection-0.2.0:
  Would remove:
    c:\users\runeb\appdata\local\programs\python\python310\lib\site-packages\photoshop\*
    c:\users\runeb\appdata\local\programs\python\python310\lib\site-packages\photoshop_connection-0.2.0.dist-info\*
Proceed (Y/n)?

I've tried with both Photoshop open and with Beta open and the plugin started but still the same error. Not sure why it doesn't detect Photoshop.

Update : Forgot to give specs.

OS Windows 11 Pro 23H2. 
Python Version 3.10.11 - ComfyUI installed manually and using Python in a venv.
GPU: RTX 2080Ti
System RAM: 32GB

**Comment by KINGLIFER** [comment]
I get _PS_ Server failed to start after several attempts. Who knows.

**Comment by NimaNzrii** [comment]
> I get _PS_ Server failed to start after several attempts. Who knows.

could you please send me your log file

**Comment by NimaNzrii** [comment]
# Fixed in V1.5.0 ✨
this problem should be fixed in ver 1.5.0
please update plugin and the node and let me know if it helped
