### ISSUE TITLE
A few comments

### ISSUE THREAD

**Issue by devZu9** [NimaNzrii/comfyui-photoshop#84]
Hello Friend. Thank you for such a useful plugin for Photoshop.
I built it into some of my processes and it allowed me to speed up my work.
But in the process of work, I had several comments that I want to share with you.

1. Installation. In my opinion, the installation should be offline without using Creative Cloud. By changing the installation method, the plugin you made will be accessible and popular several times, perhaps even tens of times. I suggest making a simple installer for it. And immediately register it so that it is installed in the following path: C:\Documents and Settings\user_name\Application Data\Adobe\UXP\

2. Make it possible to send prompts not only in Latin. The fact is that in my workflows there is a translation module and I write prompts in Russian, they are translated and already entered into the model in English, but initially I write all the prompts in Russian (since I know Russian and English at a bad level). But when, through the plugin you made, I send a Prompt in Russian from Photoshop, an error occurs, because Russian (Cyrillic) characters become corrupted and corrupted characters that are neither Russian nor English end up in the workflow. Please check if there is a way to fix this. I also tried to send hieroglyphs, but the plugin ruins them too.

3. Jerky (pop-up) interface. It is very uncomfortable. Is it possible to make sure that the randomize button is always in front of your eyes? And in general, so that the interface does not collapse into one button, but rather is always open.

4. The same thing with the disappearing slider. Is it possible to make this slider always visible? Sometimes he disappears and does not want to leave (surface). It's very annoying. I would like the slider to always be on and not disappear.

5. Regarding the slider, I really want the float value to be displayed somewhere directly in numbers. Because I already have exact values ​​for some workflows and it will be very convenient if, when working with the slider, I can see exactly what value I have chosen. Also, regarding the slider, I would like to see some scale (bars) 0, 25%, 50%, 75% and 100% (even more often, if possible)

Thanks friend, I hope you see this message.
I don't know English, but I will use automatic translation into English.

**Comment by noembryo** [comment]
@NimaNzrii Oh, you're back! 🍾 🎆 🥳 
Any news about the [beta](https://github.com/NimaNzrii/comfyui-photoshop/issues/62#issuecomment-2124532346)?

**Comment by NimaNzrii** [comment]
> @NimaNzrii Oh, you're back! 🍾 🎆 🥳 Any news about the [beta](https://github.com/NimaNzrii/comfyui-photoshop/issues/62#issuecomment-2124532346)?

Maybe about 1 or 2 days to realease

**Comment by NimaNzrii** [comment]
@devZu9 liked the update?:)))
