### ISSUE TITLE
Feature request: I want to retrieve data from Photoshop running on Mac with ComfyUI on Windows.

### ISSUE THREAD

**Issue by za-wa-n-go** [NimaNzrii/comfyui-photoshop#89]
I want to connect and operate a Mac on the same network, but the connection seems to fail, probably due to different paths between Mac and Windows. It would be helpful if there is a way to solve this.

**Comment by NimaNzrii** [comment]
Hi I think you want to check here tommorrow:)))

Will realease the next version with the feature you requested

**Comment by NimaNzrii** [comment]
# Fixed in V1.5.0 ✨
this problem should be fixed in ver 1.5.0
please update plugin and the node and let me know if it helped
