### ISSUE TITLE
The workflow is different between the previous and the latest node

### ISSUE THREAD

**Issue by naiyansui2023** [NimaNzrii/comfyui-photoshop#9]
The workflow is different between the previous and the latest node and I don't know how the latest node is used

**Comment by cardenluo** [comment]
how to connnect to the ps ?

**Comment by NimaNzrii** [comment]
Guys just give me 1 day , I'm upliading the new versions tutorial asap

**Comment by NimaNzrii** [comment]
you can test it again
but i will upload a video tutorial too
