### ISSUE TITLE
Error occurred when executing ImageResize+:

### ISSUE THREAD

**Issue by loztm** [NimaNzrii/comfyui-photoshop#90]
**It was working fine but suddenly started getting this error:**
_________________

Error occurred when executing ImageResize+:

'bool' object has no attribute 'startswith'

File "D:\Programas\comfyui\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\Programas\comfyui\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\Programas\comfyui\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\Programas\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_essentials\image.py", line 288, in execute
elif method.startswith('fill'):
^^^^^^^^^^^^^^^^^

**Comment by loztm** [comment]
**When I was trying to solve this, I got another error :(**

Error occurred when executing LoraLoader:

'NoneType' object has no attribute 'lower'

File "D:\Programas\comfyui\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\Programas\comfyui\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\Programas\comfyui\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\Programas\comfyui\ComfyUI_windows_portable\ComfyUI\nodes.py", line 609, in load_lora
lora = comfy.utils.load_torch_file(lora_path, safe_load=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\Programas\comfyui\ComfyUI_windows_portable\ComfyUI\comfy\utils.py", line 13, in load_torch_file
if ckpt.lower().endswith(".safetensors"):
^^^^^^^^^^

**Comment by noembryo** [comment]
Check [this answer](https://github.com/NimaNzrii/comfyui-photoshop/issues/82#issuecomment-2145689758)..

**Comment by loztm** [comment]
Thanks! that solved the problem. I also solved the other error by entering the lora correct name. Now I'm facing the problem that it gets stuck with the first picture in the canvas of photoshop I launch the comfy with, not loading more changes in the canvas of photoshop, any idea how to fix it?

**Comment by noembryo** [comment]
Make sure that the History in Photoshop is changing with your actions.
If not, nothing is changed for the plugin.
I had this problem because I disabled the option to track the visibility of layers there, and when I close a layer, the plugin send the version with the layer enabled.
I have to move a step back and then forward again for it to send the updated version.. 🤷‍♂️

**Comment by loztm** [comment]
> Make sure that the History in Photoshop is changing with your actions. If not, nothing is changed for the plugin. I had this problem because I disabled the option to track the visibility of layers there, and when I close a layer, the plugin send the version with the layer enabled. I have to move a step back and then forward again for it to send the updated version.. 🤷‍♂️

I have the history options enabled but no matter what, I can't make it work, stuck with the first image always :S not detecting changes on the layers, etc. I don't know what else to try
