### ISSUE TITLE
img 2 img (Scribble CN) fix

### ISSUE THREAD

**Issue by noembryo** [NimaNzrii/comfyui-photoshop#91]
This is a fix for an issue with `img 2 img (Scribble CN)` Preset.
Although this preset is working in the demo video, in the workflow it doesn't.
The reason for this is that our great developer forgot to convert a node's widget to input and it always produced 0 as strength. 😛 
![scribble01x](https://github.com/NimaNzrii/comfyui-photoshop/assets/24675403/caba8788-657c-4d8a-b572-2d085037fe4f)
So, all you have to do is convert the "a" widget to input and it will magically get controlled by the Slider in Photoshop.
The lower the Slider value > the closer to the original image..
🙏

**Comment by alperktt** [comment]
im getting this error When loading the graph, the following node types were not found:
workflow/math 4 Slider ( a slider value )
Nodes that have failed to load will show as red on the graph. 

i instaleld every missing custom nodes

**Comment by noembryo** [comment]
When you say "loading the graph" you mean the workflow?
I think the missing nodes are the ComfyUI essentials or something like this.
I can't be certain cause I'm away from my PC..

**Comment by FugueSegue** [comment]
I'm getting the same error. I don't know how to fix this "math 4 Slider".

**Comment by noembryo** [comment]
Is this "math 4 slider" error connected with the current "img 2 img (Scribble CN) fix" issue?
If it is, you have to be a little more specific..
If not, perhaps it will receive better attention if you create a new issue?

**Comment by qiuyangyang0205** [comment]
![image](https://github.com/NimaNzrii/comfyui-photoshop/assets/173628573/9d81f55f-c478-458f-93fe-2303cc990315)
How to solve this problem?
