### ISSUE TITLE
Error occurred when executing ImageResize+:

### ISSUE THREAD

**Issue by Vanhi007** [NimaNzrii/comfyui-photoshop#92]
Hi NimaNzrii
I hope you're having a good day.I'm reaching out to request your assistance with a specific issue I've been encountering. Recently, I've been facing a series of challenges related to,, 
![bool](https://github.com/NimaNzrii/comfyui-photoshop/assets/171527612/dab68274-c6f8-4b10-99dd-26053d2978b8)
and after attempting to troubleshoot on my own without success, I realize I could benefit from your expertise.
Regard,

**Comment by NimaNzrii** [comment]
Hi , please update your node and press on the load workflow button on the node!
![IMG_20240611_112744_799](https://github.com/NimaNzrii/comfyui-photoshop/assets/148809650/169ff0b2-43ac-44e4-8459-9405465d9f93)


Tell me if it worked for you

**Comment by Vanhi007** [comment]
HI Nima
"I have resolved the old issue, however, I am now facing a new problem:
![eerrrr](https://github.com/NimaNzrii/comfyui-photoshop/assets/171527612/c2cd40ff-d22f-4a55-beff-7c709c94533b)


 and I cannot see any images inside Photoshop."

**Comment by NimaNzrii** [comment]
Did you tried restarting pc? Is it still here?

**Comment by NimaNzrii** [comment]
Also did you changed the comfyui input  and output folder?

**Comment by Vanhi007** [comment]
I' am Nima, 
please help - i cant output- i dont change any input output folder 

_[rgthree] Using rgthree's optimized recursive execution.

Error in is_changed_file for E:\Comfy Portable\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\input\PS_canvas.png: [Errno 2] No such file or directory: 'E:\\Comfy Portable\\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\\ComfyUI_windows_portable\\ComfyUI\\input\\PS_canvas.png'

Error in is_changed_file for E:\Comfy Portable\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\input\PS_mask.png: [Errno 2] No such file or directory: 'E:\\Comfy Portable\\new_ComfyUI_windows_portable_nvidia_cu121_or_cpu\\ComfyUI_windows_portable\\ComfyUI\\input\\PS_mask.png'

Prompt executed in 0.00 seconds_

**Comment by Vanhi007** [comment]
Thank you Nima 
after thousand time i remove a re-installed, it's fine work 
Greak for you supporting.

**Comment by NimaNzrii** [comment]
# Fixed in V1.5.0 ✨
this problem should be fixed in ver 1.5.0
please update plugin and the node and let me know if it helped
