### ISSUE TITLE
1.4 Mask cannot be generated. The mask is empty white.

### ISSUE THREAD

**Issue by LiJT** [NimaNzrii/comfyui-photoshop#93]
![Mask Problem](https://github.com/NimaNzrii/comfyui-photoshop/assets/11270197/5804ed9b-17c5-4a69-bcac-519b263e0543)

Plugin 1.4 and with the latest CCX plugin installed inside Photoshop

**Comment by NimaNzrii** [comment]
Could you please tell me which version of Photoshop are you using ? And on which resolution , can you send me ab screenshot of your plugin setting page?

**Comment by LiJT** [comment]
> Could you please tell me which version of Photoshop are you using ? And on which resolution , can you send me ab screenshot of your plugin setting page?
![屏幕截图 2024-06-12 104041](https://github.com/NimaNzrii/comfyui-photoshop/assets/11270197/681a3be4-ce1c-449c-94b2-390118462ab7)

Hello Nima 
Thank you for the fast reply, here is my setting, I am using PS 25.2.0. Have not updated it yet, should I do that?
And as you can clearly see, there is still no Mask being generated even with this basic setup
My resolution is 512x512

**Comment by 907590629** [comment]
兄弟，你的好了吗，我的也这样

**Comment by LiJT** [comment]
> 兄弟，你的好了吗，我的也这样

Its still broken.....

**Comment by qwerdsas** [comment]
Hello. This worked for me:
Plugin searches for events in photoshop history.
So if you change your photoshop language to English it will work.
![image](https://github.com/NimaNzrii/comfyui-photoshop/assets/13279771/1739eee0-62f3-4d68-96a8-985e5ffe4740)
![image](https://github.com/NimaNzrii/comfyui-photoshop/assets/13279771/4d987a7c-08c6-4316-b54b-f8697813cb7c)

**Comment by QL-boy** [comment]
> Hello. This worked for me: Plugin searches for events in photoshop history. So if you change your photoshop language to English it will work. ![image](https://private-user-images.githubusercontent.com/13279771/340470064-1739eee0-62f3-4d68-96a8-985e5ffe4740.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2ODEwMzksIm5iZiI6MTcxODY4MDczOSwicGF0aCI6Ii8xMzI3OTc3MS8zNDA0NzAwNjQtMTczOWVlZTAtNjJmMy00ZDY4LTk2YTgtOTg1ZTVmZmU0NzQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE4VDAzMTg1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyYTc3NWUzMGJmNTA5NWUyZTEwYTQzMjk0NDdhM2QyMzEzNmRhNTNkNmNkYWU2OTg1OGRkZjlmYjZlMjlhOWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YiUwUJ3gECzhldUCL-Ad6_lLwFcI0_6gSqYKLaUSc8U) ![image](https://private-user-images.githubusercontent.com/13279771/340470103-4d987a7c-08c6-4316-b54b-f8697813cb7c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2ODEwMzksIm5iZiI6MTcxODY4MDczOSwicGF0aCI6Ii8xMzI3OTc3MS8zNDA0NzAxMDMtNGQ5ODdhN2MtMDhjNi00MzE2LWI1NGItZjg2OTc4MTNjYjdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE4VDAzMTg1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjMjdmZTBkNGZjMGE0NTNmMTE3ZDY5YjVmOGVmZjdlMjczMDU5YTFiZDhhNDg4OTI4NDRlNTU4MjEyODAxNWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CK1C-ndl6JEFKCRhooGKfRWbF_K3P5mo_fe7w38QgHM)

Indeed it does, it only works in English mode, it doesn't work in any other language, it's a bit hard to understand why that is.
@NimaNzrii

**Comment by koilu** [comment]
+1

**Comment by yhf1407** [comment]
+1

**Comment by NimaNzrii** [comment]
# Fixed in V1.5.0 ✨
Make sure you are using ps v22 or higher ( higher is better)

this problem should be fixed in ver 1.5.0
please update plugin and the node and let me know if it helped

**Comment by xueqing0622** [comment]
It  for me is ,the mask is " gray image and white lasso area" 
![image](https://github.com/user-attachments/assets/b50c02ab-a785-48fe-9901-e393f50d673c)
![image](https://github.com/user-attachments/assets/2efda830-82a0-4fec-8b6f-0fbf2001eb8b)

**Comment by xueqing0622** [comment]
no use lasso, use rectangular is ok,   
![image](https://github.com/user-attachments/assets/b5e9919b-469b-40b4-9150-9ced9c7e1179)
![image](https://github.com/user-attachments/assets/acea7c22-5e14-4fd4-aa19-cc2f6446ff77)
