### ISSUE TITLE
Node display incorrect

### ISSUE THREAD

**Issue by laidingq** [NimaNzrii/comfyui-photoshop#95]
![屏幕截图 2024-06-12 104803](https://github.com/NimaNzrii/comfyui-photoshop/assets/135723102/248d7690-f4f0-4794-9523-621566911ced)
Node display incorrect
Unable to display correctly in both Google Chrome and Photoshop

**Comment by laidingq** [comment]
@NimaNzrii

**Comment by NimaNzrii** [comment]
You can simply disable node preview by right click on it and go to the properties

**Comment by NimaNzrii** [comment]
> 1.My node displays a white background,。 2.I don't think it's necessary to add sd15 and sdxl workflow buttons on nodes, as everyone may need custom workflows to meet their needs @NimaNzrii

About sd1.5 button , you will be able to upload your own workflows abd replace with that button , even if u want we can add an option to delete the button

**Comment by laidingq** [comment]
thank you
