### ISSUE TITLE
new1.4 problem,please

### ISSUE THREAD

**Issue by xeusvel** [NimaNzrii/comfyui-photoshop#97]
workflow report a mistake,could you please tell me how to fix it ?
![image](https://github.com/NimaNzrii/comfyui-photoshop/assets/63448292/03919d0c-af94-4d50-9920-6a89dddd9413)

**Comment by NimaNzrii** [comment]
Simply just enable your ksampler by:

Select the ksampler
Press Ctrl + B

**Comment by xeusvel** [comment]
thankyou,another question,why presets shows couldnt load?
![image](https://github.com/NimaNzrii/comfyui-photoshop/assets/63448292/3e060de8-0476-45b3-b483-7d324dbf7cf7)

**Comment by huacuoni** [comment]
I'm having the same problem, I can't switch workflows at all!

**Comment by huacuoni** [comment]
I can switch mine back to the English version just fine.

**Comment by NimaNzrii** [comment]
Guys are you using translator or any other language on your comfyui or device? @xeusvel @huacuoni

**Comment by xeusvel** [comment]
I saw a prompt about. env in the background,Sorry, I didn't send you any screenshots now to show you,i reset my pc two days ago,Now it can work normally，i use chinese in my 3 diffrent devices,now they working good @NimaNzrii

**Comment by 907590629** [comment]
兄弟 加我v  haike931  请教个问题

**Comment by NimaNzrii** [comment]
# Fixed in V1.5.0 ✨
this problem should be fixed in ver 1.5.0
please update plugin and the node and let me know if it helped
